(function (app) {
    'use strict';

    app.config(['$translateProvider', function ($translateProvider) {
        $translateProvider.translations('en', {
            ACCOUNT_HEADING: 'Account',
            ACCOUNT_CHANGE_PASSWORD: 'Change Password',
            ACCOUNT_CHANGE_CREDIT_CARD: 'Change Credit Card',
            ACCOUNT_UPGRADE_SUBSCRIPTION: 'Upgrade Subscription',
            ACCOUNT_CANCEL_SUBSCRIPTION: 'Cancel Subscription',
            ACCOUNT_REACTIVATE_SUBSCRIPTION: 'Re-activate Subscription',
            ACCOUNT_PREFERENCES: 'Preferences',
            ACCOUNT_CONTACT_US: 'Contact Us',
            ACCOUNT_CANCEL_SUBSCRIPTION_CONFIRMATION: 'Are you sure you want to cancel your subscription?',
            ACCOUNT_CANCEL_SUBSCRIPTION_FAILURE: 'Cancel subscription failed. Please contact customer support at',
            ACCOUNT_CANCEL_SUBSCRIPTION_ACCOUNT_REFRESH_ERROR: 'Please close and re-open the YipTV application browser window',
            ADMIN_HEADING: 'Admin',
            ADMIN_USER_DETAILS: 'User Details',
            ADMIN_CHANGE_PASSWORD: 'Change Password',
            ADMIN_ALL_USERS: 'All Users',
            ADMIN_CHANGE_PASSWORD_HEADING: 'Change Password',
            ADMIN_CHANGE_PASSWORD_EMAIL: 'Email',
            ADMIN_CHANGE_PASSWORD_EMAIL_REQUIRED: 'Enter the email address',
            ADMIN_CHANGE_PASSWORD_EMAIL_INVALID: 'Enter a valid email address',
            ADMIN_CHANGE_PASSWORD_NEW_PASSWORD: 'New Password',
            ADMIN_CHANGE_PASSWORD_NEW_PASSWORD_REQUIRED: 'Enter your password',
            ADMIN_CHANGE_PASSWORD_NEW_PASSWORD_NOT_COMPLEX: 'Password needs to be at least 8 characters, contain 1 uppercase & 1 lowercase letter, 1 number & 1 special character',
            ADMIN_CHANGE_PASSWORD_BUTTON: 'Submit',
            ADMIN_CHANGE_PASSWORD_SUCCESS: 'Password changed successfully',
            ADMIN_CHANGE_PASSWORD_ERROR: 'Error changing the password',
            ADMIN_CHANGE_PASSWORD_USER_NOT_FOUND: 'User not found',
            ALL_USERS_HEADING: 'All Users',
            ALL_USERS_USER_LOAD_ERROR: 'Error loading users',
            ALL_USERS_EMAIL: 'Email',
            ALL_USERS_NAME: 'Name',
            ALL_USERS_TYPE: 'Type',
            ALL_USERS_STATUS: 'Status',
            BANNER_1_MOBILE_P: '<a href="http://www.yipnow.com/en/sweepstakes/"><img src="../images/banners/mobile/en/mobile-portrait-1.jpg" alt="desktop Image"></a>',
            BANNER_2_MOBILE_P: '<img src="../images/banners/mobile/en/mobile-portrait-2.jpg" usemap="#map2" alt="beIN_MobilePort"><map name="map2" id="map2"><area alt="" title="" href="/sign-up/paid" shape="rect" coords="5, 216, 357, 294" /></map>',
            BANNER_3_MOBILE_P: '<img src="../images/banners/mobile/en/mobile-portrait-3.jpg" usemap="#map3" alt="beIN_MobilePort"><map name="map3" id="map3"><area shape="rect" href="https://itunes.apple.com/us/app/yiptv/id972197370?mt=8&ign-mpt=uo%3D4" coords="186, 85, 357, 296" /><area shape="rect" href="https://play.google.com/store/apps/details?id=com.yiptv.android.client2" coords="7, 89, 182, 294" /></map>',
            BANNER_4_MOBILE_P: '<img src="../images/banners/mobile/en/mobile-portrait-4.jpg" usemap="#map4" alt="beIN_MobilePort"><map name="map4" id="map4"><area alt="" title="" href="/sign-up/free" shape="rect" coords="5, 227, 357, 313" /></map>',
            BANNER_1_MOBILE_L: '<a href="http://www.yipnow.com/en/sweepstakes/"><img src="../images/banners/mobile/en/mobile-landscape-1.jpg" alt="desktop Image"></a>',
            BANNER_2_MOBILE_L: '<img src="../images/banners/mobile/en/mobile-landscape-2.jpg" usemap="#map2" alt="beIN_MobilePort"><map name="map2" id="map2"><area alt="" title="" href="/sign-up/paid" shape="rect" coords="9, 173, 266, 329" /></map>',
            BANNER_3_MOBILE_L: '<img src="../images/banners/mobile/en/mobile-landscape-3.jpg" usemap="#map3" alt="beIN_MobilePort"><map name="map3" id="map3"><area shape="rect" href="https://itunes.apple.com/us/app/yiptv/id972197370?mt=8&ign-mpt=uo%3D4" coords="320, 185, 527, 330" /><area shape="rect" href="https://play.google.com/store/apps/details?id=com.yiptv.android.client2" coords="85, 191, 317, 328" /></map>',
            BANNER_4_MOBILE_L: '<img src="../images/banners/mobile/en/mobile-landscape-4.jpg" usemap="#map4" alt="beIN_MobilePort"><map name="map4" id="map4"><area alt="" title="" href="/sign-up/free" shape="rect" coords="397, 204, 636, 335" /></map>',
            BANNER_1_TABLET: '<a href="http://www.yipnow.com/en/sweepstakes/"><img src="../images/banners/tablet/en/tablet-1.jpg" alt="desktop Image"></a>',
            BANNER_2_TABLET: '<img src="../images/banners/tablet/en/tablet-2.jpg" usemap="#map2" alt="tablet Image"><map name="map2" id="map2"><area alt="" title="" href="/sign-up/paid" shape="rect" coords="20, 158, 262, 330" /></map>',
            BANNER_3_TABLET: '<img src="../images/banners/tablet/en/tablet-3.jpg" usemap="#map3" alt="tablet Image"><map name="map3" id="map3"><area shape="rect" href="https://itunes.apple.com/us/app/yiptv/id972197370?mt=8&ign-mpt=uo%3D4" coords="196, 161, 362, 333" /><area shape="rect" href="https://play.google.com/store/apps/details?id=com.yiptv.android.client2" coords="32, 162, 192, 332" /></map>',
            BANNER_4_TABLET: '<img src="../images/banners/tablet/en/tablet-4.jpg" usemap="#map4" alt="tablet Image"><map name="map4" id="map4"><area alt="" title="" href="/sign-up/free" shape="rect" coords="19, 163, 263, 333" /></map>',
            BANNER_1_DESKTOP: '<a href="http://www.yipnow.com/en/sweepstakes/"><img src="../images/banners/desktop/en/desktop-1.jpg" alt="desktop Image"></a>',
            BANNER_2_DESKTOP: '<img src="../images/banners/desktop/en/desktop-2.jpg" usemap="#map2" alt="desktop Image"><map name="map2" id="map2"><area alt="" title="" href="/sign-up/paid" shape="rect" coords="42, 229, 316, 413" /></map>',
            BANNER_3_DESKTOP: '<img src="../images/banners/desktop/en/desktop-3.jpg" usemap="#map3" alt="desktop Image"><map name="map3" id="map3"><area shape="rect" href="https://itunes.apple.com/us/app/yiptv/id972197370?mt=8&ign-mpt=uo%3D4" coords="244, 270, 411, 335" /><area shape="rect" href="https://play.google.com/store/apps/details?id=com.yiptv.android.client2" coords="69, 272, 240, 335" /></map>',
            BANNER_4_DESKTOP: '<img src="../images/banners/desktop/en/desktop-4.jpg" usemap="#map4" alt="desktop Image"><map name="map4" id="map4"><area alt="" title="" href="/sign-up/free" shape="rect" coords="46, 215, 309, 297" /></map>',
            CANCEL_SUBSCRIPTION_SUCCESS_HEADING: 'Subscription Canceled',
            CANCEL_SUBSCRIPTION_SUCCESS_MESSAGE: 'Your subscription has been successfully canceled.',
            CHANGE_CREDIT_CARD_HEADING: 'Change Credit Card',
            CHANGE_CREDIT_CARD_BILLING_INFO: 'Enter your new credit card details. If you need help call',
            CHANGE_CREDIT_CARD_CARD_NAME: 'Name on Credit Card',
            CHANGE_CREDIT_CARD_CARD_NAME_REQUIRED: 'Enter name as on your credit card',
            CHANGE_CREDIT_CARD_ADDRESS: 'Billing Address',
            CHANGE_CREDIT_CARD_ADDRESS_REQUIRED: 'Enter address as on your credit card',
            CHANGE_CREDIT_CARD_CITY: 'City',
            CHANGE_CREDIT_CARD_CITY_REQUIRED: 'Enter city as on your credit card',
            CHANGE_CREDIT_CARD_STATE: 'State',
            CHANGE_CREDIT_CARD_STATE_REQUIRED: 'Enter state as on your credit card',
            CHANGE_CREDIT_CARD_STATE_LOAD_ERROR: 'Error loading state list',
            CHANGE_CREDIT_CARD_STATE_SELECT: 'Select One',
            CHANGE_CREDIT_CARD_CARD_NUMBER: 'Credit Card Number',
            CHANGE_CREDIT_CARD_CARD_NUMBER_REQUIRED: 'Enter your credit card number',
            CHANGE_CREDIT_CARD_CARD_NUMBER_ERROR: 'Enter a valid credit card number',
            CHANGE_CREDIT_CARD_CVV: 'CVV',
            CHANGE_CREDIT_CARD_CVV_REQUIRED: 'Enter your CVV',
            CHANGE_CREDIT_CARD_CARD_NUMBER_CVV_ERROR: 'Enter a valid CVV',
            CHANGE_CREDIT_CARD_EXPIRY_DATE: 'Expiration Date (MM/YYYY)',
            CHANGE_CREDIT_CARD_EXPIRY_DATE_REQUIRED: 'Enter your card expiration date',
            CHANGE_CREDIT_CARD_EXPIRY_DATE_INVALID: 'Enter a valid card expiration date',
            CHANGE_CREDIT_CARD_ZIP_CODE: 'Zip Code',
            CHANGE_CREDIT_CARD_ZIP_CODE_REQUIRED: 'Enter zip code as on your credit card',
            CHANGE_CREDIT_CARD_ZIP_CODE_INVALID: 'Enter a valid zip code',
            CHANGE_CREDIT_CARD_CARD_NAME_INVALID: 'Enter a valid name',
            CHANGE_CREDIT_CARD_ADDRESS_INVALID: 'Enter a valid address',
            CHANGE_CREDIT_CARD_CITY_INVALID: 'Enter a valid city',
            CHANGE_CREDIT_CARD_SUBMIT_BUTTON: 'Submit',
            CHANGE_CREDIT_CARD_FAILED: 'Unable to change your credit card. Please contact customer support at',
            CHANGE_CREDIT_CARD_PROBLEM: 'Having trouble changing your credit card? Contact customer support at',
            CHANGE_CREDIT_CARD_ACCESS_ERROR: 'You cannot change your credit card. Please contact customer support at',
            CHANGE_CREDIT_CARD_PAYMENT_ERROR: 'We were unable to process payment on your card. Please check your credit card information.',
            CHANGE_CREDIT_CARD_FREE_USER_ERROR: 'Trial users cannot add a credit card to their account',
            CHANGE_CREDIT_CARD_SUCCESS_HEADING: 'Credit Card Changed',
            CHANGE_CREDIT_CARD_SUCCESS_MESSAGE: 'Your credit card has been changed successfully',
            CHANGE_PASSWORD_HEADING: 'Change password',
            CHANGE_PASSWORD_CURRENT_PASSWORD: 'Current password',
            CHANGE_PASSWORD_NEW_PASSWORD: 'New password',
            CHANGE_PASSWORD_CONFIRM_PASSWORD: 'Confirm new password',
            CHANGE_PASSWORD_BUTTON: 'Submit',
            CHANGE_PASSWORD_CURRENT_PASSWORD_REQUIRED: 'Enter your current password',
            CHANGE_PASSWORD_NEW_PASSWORD_REQUIRED: 'Enter new password',
            CHANGE_PASSWORD_NEW_PASSWORD_NOT_COMPLEX: 'Password needs to be at least 8 characters, contain 1 uppercase & 1 lowercase letter, 1 number & 1 special character',
            CHANGE_PASSWORD_NEW_PASSWORD_SAME: 'New Password cannot be the same as the current password',
            CHANGE_PASSWORD_CONFIRM_PASSWORD_REQUIRED: 'Confirm your password',
            CHANGE_PASSWORD_CONFIRM_PASSWORD_NO_MATCH: 'Passwords do not match',
            CHANGE_PASSWORD_ERROR: 'Error occurred while changing the password',
            CHANGE_PASSWORD_INCORRECT_PASSWORD: 'Current Password entered is incorrect',
            CHANGE_PASSWORD_SUCCESS_HEADING: 'Password Changed',
            CHANGE_PASSWORD_SUCCESS_MESSAGE: 'Your password has been changed successfully',
            CMS_URL_ABOUT_US: 'index.php/about-us/',
            CMS_URL_FAQS: 'index.php/faqs/',
            CMS_URL_MAIN: 'index.php/yip-now/',
            CMS_URL_PRIVACY_POLICY: 'index.php/privacy-policy/',
            CMS_URL_TOUS: 'index.php/terms-of-service/',
            CMS_URL_EULA: 'index.php/end-user-license-agreement/',
            CMS_URL_NETWORKS: 'index.php/en/tv-channels/',
            COMP_SIGN_UP_HEADING: 'Sign Up',
            COMP_SIGN_UP_MESSAGE: 'Sign up for your complimentary YipTV account.',
            COMP_SIGN_UP_VERIFYING: 'Verifying...',
            COMP_SIGN_UP_CODE_EXPIRED: 'Your invitation code is either invalid or has expired!',
            COMP_SIGN_UP_FIRST_NAME: 'First Name',
            COMP_SIGN_UP_FIRST_NAME_REQUIRED: 'Enter your first name',
            COMP_SIGN_UP_LAST_NAME_REQUIRED: 'Enter your last name',
            COMP_SIGN_UP_FIRST_NAME_INVALID: 'Enter a valid first name',
            COMP_SIGN_UP_LAST_NAME_INVALID: 'Enter a valid last name',
            COMP_SIGN_UP_EMAIL: 'Email',
            COMP_SIGN_UP_TELEPHONE: 'Telephone',
            COMP_SIGN_UP_TELEPHONE_INVALID: 'Enter a valid US telephone number',
            COMP_SIGN_UP_TELEPHONE_REQUIRED: 'Enter your telephone number',
            COMP_SIGN_UP_LAST_NAME: 'Last Name',
            COMP_SIGN_UP_EMAIL_INVALID: 'Enter a valid email address',
            COMP_SIGN_UP_EMAIL_EXISTS: 'You already have an account with us. Please sign in.',
            COMP_SIGN_UP_EMAIL_REQUIRED: 'Enter your email address',
            COMP_SIGN_UP_PASSWORD: 'Password',
            COMP_SIGN_UP_PASSWORD_REQUIRED: 'Enter your password',
            COMP_SIGN_UP_PASSWORD_NOT_COMPLEX: 'Password needs to be at least 8 characters, contain 1 uppercase & 1 lowercase letter, 1 number & 1 special character',
            COMP_SIGN_UP_CONFIRM_PASSWORD: 'Confirm Password',
            COMP_SIGN_UP_CONFIRM_PASSWORD_REQUIRED: 'Confirm your password',
            COMP_SIGN_UP_CONFIRM_PASSWORD_NO_MATCH: 'Passwords do not match',
            COMP_SIGN_UP_TERMS_OF_USE: 'Terms of Use',
            COMP_SIGN_UP_AND: 'and',
            COMP_SIGN_UP_SUBMIT_BUTTON: 'Sign Up',
            COMP_SIGN_UP_HAVE_ACCOUNT: 'Already have an account?',
            COMP_SIGN_UP_SIGN_IN: 'Sign In',
            COMP_SIGN_UP_DISCLAIMER: 'I agree to the YipTV',
            COMP_SIGN_UP_DISCLAIMER_END: '',
            COMP_SIGN_UP_DISCLAIMER_REQUIRED: 'In order to use YipTV services you need to accept our Terms of Use and Privacy Policy',
            COMP_SIGN_UP_PRIVACY_POLICY: 'Privacy Policy',
            COMP_SIGN_UP_USER_EXISTS: 'This email is already registered with YipTV. Please use another email address.',
            COMP_SIGN_UP_REUSE_CODE: 'You have already used this invitation code',
            COMP_SIGN_UP_FAILED: 'User sign up failed. Please contact customer support at',
            COMP_SIGN_UP_PROBLEM: 'Having trouble signing up? Contact customer support at',
            CONTACT_US_HEADING: 'Contact Us',
            CONTACT_US_NAME: 'Name',
            CONTACT_US_INTEREST: 'Interest',
            CONTACT_US_INTEREST_SELECT: 'Select One',
            CONTACT_US_INTEREST_INVESTOR: 'Become a YipTV investor',
            CONTACT_US_INTEREST_TECHNICAL: 'Technical Support',
            CONTACT_US_INTEREST_BILLING: 'Billing Support',
            CONTACT_US_EMAIL: 'Email',
            CONTACT_US_TELEPHONE: 'Telephone',
            CONTACT_US_TELEPHONE_INVALID: 'Enter a valid US telephone number',
            CONTACT_US_DETAILS: 'How can we assist you?',
            CONTACT_US_COUNTRY: 'Country',
            CONTACT_US_COUNTRY_SELECT: 'Select One',
            CONTACT_US_COUNTRY_REQUIRED: 'Select your country',
            CONTACT_US_SUBMIT_BUTTON: 'Submit',
            CONTACT_US_NAME_REQUIRED: 'Enter your name',
            CONTACT_US_INTEREST_REQUIRED: 'Enter your interest type',
            CONTACT_US_EMAIL_REQUIRED: 'Enter your email address',
            CONTACT_US_EMAIL_INVALID: 'Enter a valid email address',
            CONTACT_US_DETAILS_REQUIRED: 'Tell us how we can help you?',
            CONTACT_US_TELEPHONE_REQUIRED: 'Enter your telephone number',
            CONTACT_US_ERROR: 'Error submitting your request',
            CONTACT_US_COUNTRY_LOAD_ERROR: 'Error loading country list',
            CONTACT_US_SUCCESS_HEADING: 'Request Submitted',
            CONTACT_US_SUCCESS_MESSAGE: 'Your request has been submitted successfully.',
            CUSTOMER_SUPPORT_HEADING: 'Customer Support',
            CUSTOMER_SUPPORT_MESSAGE: 'Please contact customer support at',
            DOWNLOAD_MOBILE_APP: 'Free Mobile App for YipTV customers!',
            DOWNLOAD_PARA: 'After signing up, take YipTV with you anywhere! Watch indoors or outside anywhere you get Wi-Fi or a cellular connection on your phone or tablet.',
            DOWNLOAD_BULLET_1: 'Sign up for a YipTV account <a href=\'/sign-up/paid\'>here</a>',
            DOWNLOAD_BULLET_2: 'Go to the App Store or Google Play to download the free app',
            DOWNLOAD_BULLET_3: 'Start enjoying YipTV on your device immediately. No other hardware is required.',
            DOWNLOAD_FINE_PRINT: '*Data rates from your wireless carrier may apply when not using Wi-Fi.  YipTV has been engineered to work flawlessly over any broadband connection, whether wired, Wi-Fi LTE, 4G or even 3G cellular landlines.',
            ERROR_HEADING: 'Error',
            ERROR_MESSAGE: 'An unexpected error has occurred. Please try again. If error persists please contact customer support at',
            FORGOT_PASSWORD_HEADING: 'Forgot Password',
            FORGOT_PASSWORD_EMAIL: 'Enter your email and we will send a link to reset your password',
            FORGOT_PASSWORD_BUTTON: 'Submit',
            FORGOT_PASSWORD_EMAIL_INVALID: 'Enter a valid email address',
            FORGOT_PASSWORD_EMAIL_REQUIRED: 'Enter your email address',
            FORGOT_PASSWORD_ERROR: 'Error sending reset password link. Please contact customer support at',
            FORGOT_PASSWORD_SUCCESS_HEADING: 'Email Sent',
            FORGOT_PASSWORD_SUCCESS_MESSAGE: 'Password reset link and instructions have been sent to your email address',
            FOOTER_HEADER_CAPTION: 'Watch live news, sports & events from around the world',
            FOOTER_JOIN_BUTTON: 'Join Now',
            FOOTER_TRIAL_BUTTON: 'Try for 7 Days',
            FOOTER_CONTACT_US: 'Contact Us',
            FOOTER_ABOUT_US: 'About Us',
            FOOTER_LEADERSHIP: 'Leadership',
            FOOTER_BLOG: 'Blog',
            FOOTER_PRIVACY_POLICY: 'Privacy Policy',
            FOOTER_TERMS_OF_USE: 'Terms of Use',
            FOOTER_FAQ: 'FAQs',
            FOOTER_END_USER_LICENSE_AGREEMENT: 'End User License Agreement',
            FOOTER_SOCIAL_MEDIA: '<a target="_blank" href="https://www.facebook.com/pages/Yiptv/670093559720356?fref=ts"><img src="images/facebook.png" alt=""/></a><a target="_blank" href="https://twitter.com/YipTV"><img src="images/twitter.png" alt=""/></a>',
            FREE_SIGN_UP_HEADING: 'Sign Up',
            FREE_SIGN_UP_MESSAGE: 'Start your 7 day free trial now! No credit card required.',
            FREE_SIGN_UP_FIRST_NAME: 'First Name',
            FREE_SIGN_UP_FIRST_NAME_REQUIRED: 'Enter your first name',
            FREE_SIGN_UP_LAST_NAME_REQUIRED: 'Enter your last name',
            FREE_SIGN_UP_FIRST_NAME_INVALID: 'Enter a valid first name',
            FREE_SIGN_UP_LAST_NAME_INVALID: 'Enter a valid last name',
            FREE_SIGN_UP_EMAIL: 'Email',
            FREE_SIGN_UP_TELEPHONE: 'Telephone',
            FREE_SIGN_UP_TELEPHONE_INVALID: 'Enter a valid US telephone number',
            FREE_SIGN_UP_TELEPHONE_REQUIRED: 'Enter your telephone number',
            FREE_SIGN_UP_LAST_NAME: 'Last Name',
            FREE_SIGN_UP_EMAIL_INVALID: 'Enter a valid email address',
            FREE_SIGN_UP_EMAIL_EXISTS: 'You already have an account with us. Please sign in.',
            FREE_SIGN_UP_EMAIL_REQUIRED: 'Enter your email address',
            FREE_SIGN_UP_PASSWORD: 'Password',
            FREE_SIGN_UP_PASSWORD_REQUIRED: 'Enter your password',
            FREE_SIGN_UP_PASSWORD_NOT_COMPLEX: 'Password needs to be at least 8 characters, contain 1 uppercase & 1 lowercase letter, 1 number & 1 special character',
            FREE_SIGN_UP_CONFIRM_PASSWORD: 'Confirm Password',
            FREE_SIGN_UP_CONFIRM_PASSWORD_REQUIRED: 'Confirm your password',
            FREE_SIGN_UP_CONFIRM_PASSWORD_NO_MATCH: 'Passwords do not match',
            FREE_SIGN_UP_TERMS_OF_USE: 'Terms of Use',
            FREE_SIGN_UP_AND: 'and',
            FREE_SIGN_UP_SUBMIT_BUTTON: 'Sign Up',
            FREE_SIGN_UP_HAVE_ACCOUNT: 'Already have an account?',
            FREE_SIGN_UP_SIGN_IN: 'Sign In',
            FREE_SIGN_UP_DISCLAIMER: 'I agree to the YipTV',
            FREE_SIGN_UP_DISCLAIMER_END: '',
            FREE_SIGN_UP_DISCLAIMER_REQUIRED: 'In order to use YipTV services you need to accept our Terms of Use and Privacy Policy',
            FREE_SIGN_UP_PRIVACY_POLICY: 'Privacy Policy',
            FREE_SIGN_UP_USER_EXISTS: 'This email is already registered with YipTV. Please use another email address.',
            FREE_SIGN_UP_FAILED: 'User sign up failed. Please contact customer support at',
            FREE_SIGN_UP_PROBLEM: 'Having trouble signing up? Contact customer support at',
            INDEX_OTHER_LANGUAGE: 'Español',
            INDEX_ABOUT_US: 'About Us',
            INDEX_SIGN_IN: 'Sign In',
            INDEX_JOIN_NOW: 'Join Now',
            INDEX_TRY_FREE: 'Try for 7 Days',
            INDEX_WATCH_NOW: 'Watch Now',
            INDEX_NETWORKS: 'Networks',
            INDEX_SHOWS_BY_CATEGORY: 'Shows by Category',
            INDEX_ACCOUNT: 'Account',
            INDEX_ADMIN: 'Admin',
            INDEX_FAQ_ACRONYM: 'FAQ',
            INDEX_SIGN_OUT: 'Sign Out',
            INDEX_WELCOME: 'Welcome',
            INDEX_OK_BUTTON: 'OK',
            INDEX_YES_BUTTON: 'Yes',
            INDEX_NO_BUTTON: 'No',
            INDEX_LANGUAGE_DROPDOWN: 'Language',
            INDEX_WP_BUTTON: 'Network',
            INDEX_WP_HREF: '<a href="http://www.yiptv.com/live-tv/index.php/en/tv-channels/" access-level="accessLevels.anon">Network</a>',
            INDEX_CONTACT_NUMBER: 'Call us toll free: <a href=\'tel:+18559194788\'>855-919-4788</a>',
            INDEX_USER_DROPDOWN: 'Login/Join',
            INDEX_COPYRIGHT: 'Copyright ® 2012-2015 YipTV. User of the YipTV service and this web site constitutes acceptance of our terms of use and privacy policy.',
            LEADERSHIP_HEADING: 'Leadership',
            LEADERSHIP_DESCRIPTION: 'Our management team is an experienced group, and we’ve disrupted old industries before, but we still think like young people. We get to the point and stay focused on what matters most to customers. When we listed out the things we wanted for our own families in a distributor of TV channels, we realized that no company did all of those things yet. Then we knew we had to try to build that company ourselves. So we did. Our Board of Directors is comprised of industry giants and brilliant minds. We’re lucky to have them. Ditto for our investors. Our team may be distinguished, but no one here takes themselves too seriously. That’s how you build a company that people want to join. Here’s a little bit more about our collective backgrounds.',
            LEADERSHIP_EXECUTIVES_TITLE: 'Our Executives',
            LEADERSHIP_CHAIRMAN_NAME: 'Michael Tribolet, Chairman, Co-Founder, & CEO',
            LEADERSHIP_CHAIRMAN_DESCRIPTION: 'Michael Tribolet is a result driven entrepreneur with extensive experience in building & selling fast growth high-tech small business, enterprise networks and consumer based businesses. His competency includes administration, business development, customer care, marketing, operations, sales, strategy and overall management of companies. With over 20+ years experience building privately and publicly owned companies with cross border operations, Michael has been instrumental in developing strategy and achieving the tactical milestones necessary to manage company growth. Most recently, Michael served as CEO/Managing Director of ACN Europe, where he was responsible for $500M+ Annual Revenues in direct marketing sales of telecommunications, broadband and energy products. Prior to ACN, he was brought on to serve as President at VONAGE growing the company to 2.6 million paying customers increasing revenues from $2M – $900M in less than 5 years. Michael participated in the raising of $1Billion dollars during his tenure at Vonage and responsibilities included overseeing sales, marketing, customer care and a variety of operational functions such as system operations & applications management, carrier relations, network operations, logistics and quality assurance. Prior to joining Vonage, Mr. Tribolet served as Vice President of Operations at Dialpad Communications which sold to Yahoo. Prior to Dialpad, Mr. Tribolet served as President of Data Products International where he oversaw the global build-out of Internet telephony services.',
            LEADERSHIP_EVP_NAME: 'Carmen Tribolet, Co-Founder & Executive VP',
            LEADERSHIP_EVP_DESCRIPTION: 'Carmen Tribolet has over 15 years of proven Telecommunications and Leadership experience. She served as Director of The Americas for Telecom Italia Sparkle where she was responsible for managing their International Data/IP sales and marketing efforts. During her tenure, she successfully brought in key global accounts, tripling revenues among their Latin America, Europe and Asian Markets. Telecom Italia is one of the largest telecom companies in the world with annual revenues of $31Billion. Prior to TIS, Carmen held various positions throughout her 7-year tenure at IDT Telecom where she played a key role within their cost saving objectives and international commercial initiatives from the company¹s inception leading up to their IPO. IDT is a pioneer and leader of prepaid International calling around the world with annual revenues is $1.6Billion. In her spare time, Carmen enjoys traveling the globe with her husband, camera, and three children. She is also an avid supporter of the Arts and an active participant with various cultural and film organizations throughout the state of Florida.',
            LEADERSHIP_CLO_NAME: 'Chuck Gaspari, Co-Founder & CLO',
            LEADERSHIP_CLO_DESCRIPTION: 'Chuck Gaspari has a strong background in strategic business operations, capital sourcing and strategic relationships, encompassing startup development, marketing, sales, mergers and acquisitions, and corporate policies and practices. He founded G&G Sports and Entertainment Group, Inc., and has worked with Motorola, Comcast and teams and clients in the NBA, NHL, PGA, LPGA and Major League Baseball. Gaspari also served as a White House staff assistant to then Vice President George H.W. Bush and as a judicial law clerk for a U.S. Magistrate for the Southern District of Florida.',
            LEADERSHIP_CFO_NAME: 'Mark Holodnak, CFO',
            LEADERSHIP_CFO_DESCRIPTION: 'Mark Holodnak has had an extensive career spanning from IBM, GE Capital, Tetra Pak, Inter- Tel and most notably as the founding VP Finance/Controller for Vonage (pre-IPO). At Vonage he was instrumental in creating the Finance department and implementing systems and processes that became the foundation for its exponential growth and eventual IPO. His record of achievement includes establishing a World-class finance operation including financial reporting, cash management, treasury, risk management, budgeting and forecasting, contract negotiation and inventory management. Since Vonage he has advised various companies on acquisitions, due diligence, and system implementations. In this capacity, he has assisted both buyers and sellers and has significant experience working with private equity firms and investment bankers. Most recently, He managed a two year-long turnaround, investment valuation, equity sale and eventual wind-down of a diversified media venture. He holds an MBA from Rider University in Lawrenceville NJ has lived in the New York City area for many years and now resides in Phoenix, AZ with his family.',
            LEADERSHIP_CMO_NAME: 'Ian Wismann, Chief Marketing Officer',
            LEADERSHIP_CMO_DESCRIPTION: 'Ian Wismann’s career has spanned two decades at Fortune 100 firms including Citibank and Chase, and nimble start ups including Vonage and Snackable Media. A digital marketing veteran, he has generated a half billion dollars in start up revenues. At Vonage he conceived and executed the online acquisition plan that acquired the majority of the firm&#39;s customers between 2002 - 2005, and also launched the brand internationally. At Snackable Media, Ian spearheaded partnerships with MTV Networks, Endemol, and other television stakeholders to generate revenue streams that capitalized on television content extensions to mobile devices. In 2010 Ian billed nearly 1% of all mobile premium SMS revenues in the United States, and his VH1 Text 2 Win product was nominated for a Mobile Excellence Award for Best Category Extension in Television. Ian is a former Partner at the advertising agency Ogilvy & Mather and has served on the Board of Directors of the Bankers Conseco Life Insurance Company since 2001. Additionally he serves on the Board of Directors of Seven Minds, a mobile software developer that produces assistive technology for special needs children on three continents. Ian is married with four children, and holds an MBA in Information Systems from Fordham University.',
            LEADERSHIP_CIO_NAME: 'Giancarlo Paolillo, Chief Information Officer',
            LEADERSHIP_CIO_DESCRIPTION: 'Giancarlo Paolillo has held positions ranging from CIO at ACN, CTO at X Plus One, and Head of Emerging Technologies for Household International (now HSBC) where he was responsible for the design and support of over 30 million credit card customers within their E-commerce solutions in EU and USA. In addition Giancarlo was the Senior VP of Engineering for Vonage where he scaled the infrastructure and software development solutions from 6 points of presence to 36 in under two years with clients from less than 100k to greater than 2 million. His responsibilities and experience encompass Network infrastructure, Systems engineering, Capacity planning, Network security, Ecommerce infrastructure, Data Base and data warehouse solutions, backup strategies, Storage Area Networks and NOC; building, redesigning, security within the Infrastructure and software engineering of each organization dealing with Network, Systems, and Applications and has created security teams trained by him. During the span of his career, Giancarlo has built data centers; ground up Security teams; disaster recovery sites; migrated companies to meet SOX/AS5 compliance; Storage Life Management solutions; Re-vamped software architectures to scale; while reducing overall complexity and increasing our ROI.',
            LEADERSHIP_VPE_NAME: 'Tomasz Sarnowski, VP Engineering',
            LEADERSHIP_VPE_DESCRIPTION: 'Tomasz brings over 14 years of experience designing, building, and troubleshooting large-scale telecommunications systems and mobile applications.  His specific expertise is in vendor software and hardware implementation and integration, business intelligence, quality assurance, and customer care within the telecommunications industry. He has extensive background in VoIP, Mobile and PSTN systems (Public Switched Telephone Network). Prior to joining YipTV, Tomasz was one of Vonage\'s first employees, rose to the level of Senior Engineer and was also the Core Engineer as part of the original Vonage Mobile subsidiary (Novega). After Vonage, Tomasz served as Senior Architect at Telcordia Technologies, Inc. (Iconectiv) where he provided technical solutions and held leadership positions for multiple telecommunications products such as Mobile ID and Resolver. In his spare time, he founded Message Sprout, a web based SMS, Voice and Email messaging system for small to medium businesses. Tomasz has been an issued a patent titled: "Method and Apparatus for Telecommunication Session Authentication Using DTMF Signaling."',
            LEADERSHIP_VPCA_NAME: 'Victor Iasprizza, VP Content Acquisition',
            LEADERSHIP_VPCA_DESCRIPTION: 'Victor Iasprizza brings over 15 years of telecommunications sales and management experience in both Latin America and Europe, where he was responsible for growing Latinode’s international wholesale and retail voice business. His responsibilities included P & L accountability, expansion of LATAM & EMEA regions along with development of emerging markets.Victor&#39;s leadership led to the successful growth of 35% with over $180M annual revenues and included notable recognition as Hispanic Business Fastest-Growing Company in 2004, 2005 and 2006.',
            LEADERSHIP_VPBD_NAME: 'Sekar Desamangalam, VP of Business Development',
            LEADERSHIP_VPBD_DESCRIPTION: 'Sekar Desamangalam most recently served as Director with Virtus Global Partners where he worked on US-India cross border initiatives - M&A, JV and Alliances. He brings over 20 years of experience in Engineering & Technology industry. Prior to Virtus Global, Sekar was responsible for CPE product development and Corporate Business Development at Vonage. In this capacity, he also worked on new market entry initiatives including an India Entry Strategy for Vonage. Sekar&#39;s past experience also includes stints at General Electric and Bechtel Power Corporation working on global projects that spanned UK, China and Europe, besides the North American market. Sekar holds an MBA from New York University, Stern School of Business, an MS from the University of South Florida, Tampa and a BE from the Birla Institute of Technology & Science, Pilani, India.',
            LEADERSHIP_DIRECTORS_TITLE: 'Our Board of Directors',
            LEADERSHIP_BA1_NAME: 'Michael Snyder, Board Member',
            LEADERSHIP_BA1_DESCRIPTION: 'Michael Snyder, has over 30 years of experience at the most senior levels of management, transforming and growing companies in the service and technology sectors. From 1997 to February 2006, he served as the President and Chief Operating Officer at ADT Security Services, Inc, North America, building the strategies, teams, programs, and infrastructure that grew that business from $ 690m to $4.0B in revenue with cash flows approaching $1.0b. Mike joined ADT in 1977 and served in various Sales, Sales  Management, Marketing, and Operations roles prior to 1997. Mike left ADT in 2006 to become Chief Executive Officer and Director of Vonage Holdings Inc.. In his tenure at Vonage, Mr. Snyder was responsible for recruiting and building teams, transforming marketing, and delivery systems, to produce scalability for this high growth opportunity. Vonage revenues during his tenure tripled to over $900m with a clear path to short term profitability. Also during his tenure Mike led a successful IPO effort, generating $642m and listing on he NYSE. Mike left Vonage late in 2007. Since  then he has built a successful operational consulting practice that has led to variety of successful and varied postings.He has been Executive Chairman of Castlerock Security Holdings, Inc. He was the Operational Consultant for the $2.0 acquisition of Securitas by Bain Capital in 2010. He serves as a Director of CitraPAc. He served as Advisory Board member at Proximex prior to its sale to TYCO Intl. He serves as a Board Member for the National Crime Prevention Council. Mike served as a Director of Talon International, Inc. from July 2010 to April 9, 2012. He identified and  led the effort to acquire Red Hawk Fire and Security from United Technologies on behalf of a PE firm, serving as CEO during the successful nine month transition of that company. He has also been involved in many operational, and operational diligence activities with PE and Investment banking firms over the last several years. Mr. Snyder holds a B.A. degree from The State University of New York at Oswego, Oswego, NY. He also serves on the nonprofit Boards of the National Crime Prevention Council and International Swimming Hall of Fame where he also served as Chairman.',
            LEADERSHIP_BA2_NAME: 'Peter Foyo, Board Member',
            LEADERSHIP_BA2_DESCRIPTION: 'Peter Foyo served as CEO and Chairman of Nextel de México S. A., C. V., from 1998 through December 2013. During his tenure, Mr. Foyo was responsible for the complete functioning of the company&#39;s operations. Additionally, Mr. Foyo has held various senior management positions within AT&T Corporation, responsible for the company’s management and operations in various countries throughout Latin America. Peter was also a member of the board of directors of the Compañia de Telefonos del Interior and also  Corporate Strategy Director of Alestra, S.A. de C.V., a joint venture between AT&T and a local Mexican partner; and president of AT&T Argentina. Peter currently sits on a number of international and domestic boards including: Marquette Companies; Abraaj Group (UAE); World Fund (Mexico); and Sirran Communications amongst others. Peter’s expertise in the expansion and development of both international and domestic businesses has been widely recognized. He is extremely passionate about the business purpose of these organizations and the results his involvement provides. During  this past year he has developed an Urgent Care Plaza in Mexico that will provide healthcare for those in need; he has also driven revenues over $3.6mm for a security company that has been in business less than a year. Foyo studied International Business, Economics, Military Science and Engineering at Benedictine University and Wheaton College in Illinois.',
            LEADERSHIP_BA3_NAME: 'Brian Mass, Board Member',
            LEADERSHIP_BA3_DESCRIPTION: 'Brian Mass has been involved in the investment banking and information technology industry for over fifteen years. Brian was a Director in Citigroup’s Global Technology Investment Banking Group and specialized in providing corporate finance and advisory services for Global Services and IT Infrastructure companies. During Brian’s tenure with Citigroup he executed over $70 billion in transactions including $6.5 billion in financings and $10 billion in acquisitions for IBM, the $14 billion sale of EDS to HP,  the $8 billion sale of ACS to Xerox, $1.5 billion in financings plus the $550 million acquisition of Headstrong for Genpact, and various other financing and advisory engagements for companies such as Accenture, EXL Service, Hewitt, interxion, SAIC, SRA, TeleTech, Unisys, West and Wipro. Prior to Citigroup, Brian was an Analyst at Rho Ventures, a venture capital firm with over $2 billion under management. Brian received a BA in Economics from Northwestern University and is FINRA Series 7 (General Securities Representative) and Series 63 (Uniform Securities Agent) registered.',
            LEADERSHIP_BA4_NAME: 'Judith Aidoo, Board Member',
            LEADERSHIP_BA4_DESCRIPTION: 'Judith Aidoo is a private investor (Caswell Capital Partners, LLC) and media and entertainment entrepreneur (Caswell Communications, Inc.) with holdings in radio broadcasting; television syndication; publishing; and feature film and theater production. Judith began her career as an investment banker in 1987 with Goldman, Sachs & Co., where she specialized in structured finance. Upon leaving Goldman in 1991, she started her own firm to both advise and invest in technology; telecommunications and media; and  financial services. She has co-managed a hedge fund with over $200 million in broadcast and entertainment assets. Ms. Aidoo has been honored for her business accomplishments and philanthropy as a board member of the following institutions: co-chair of Harvard Law School’s Class of 1987 20th Reunion Committee; WNYC, the City of New York&#39;s public radio station group chaired at the time by Mrs. Billie Tisch; President Clinton&#39;s Transition Team, responsible for covering the Federal Reserve System of the US, and as a member of his U.S. Trade Advisory Committee chaired by the US  Trade Representative at the time, Ms. Charlene Barshefsky; the US-South Africa Business Development Committee co-chaired by the US Secretaries of Commerce Brown and Daley; the Constituency for Africa; and the 2001 class of Henry Crown Fellows at the Aspen Institute which emphasizes values-based leadership in business. Most recently, Judith was nominated by her peers to the Governing Council of the Ghana Stock Exchange until 2004. Ms. Aidoo is also a founding member of the African Women’s Development Fund; the Dean of the Faculty of Arts and Sciences at Rutgers University’s  Advisory Board; and an investor and Chief Executive Officer of Capital Alliance Co., a boutique merchant bank; Caswell Communications, Inc., the operator of WPAL-FM, and one time owner and joint operator of WZJY 1480 AM, both in Charleston, SC. Judith graduated Phi Beta Kappa and with high honors from Rutgers College in 1984 and from Harvard Law School in 1987. She has been a television contributor for MSNBC and CNN, and has been profiled and quoted in major business publications on investment matters including the Wall Street Journal, Forbes, the Financial Times and Black  Enterprise.',
            LEADERSHIP_BA5_NAME: 'Ed Rodriquez, Board Advisor',
            LEADERSHIP_BA5_DESCRIPTION: 'Ed Rodriguez has over 14 years of Hi-Tech Sales, Product Management and Consulting Services experience. He currently leads Citrix Systems (CTXS) Inside Sales division for North and South America, encompassing their small business and mid-market segments in addition to their Subscription and Hardware Maintenance Renewals teams which exceeds $500M in annual revenues. In prior roles at Citrix, Ed helped pave the way for new products leading product development releases, participating in Board meetings and  building sales teams focused on emerging markets and vertical channels. He has a degree in Computer Science and started his career at a boutique Consulting organization before joining Citrix and spending 5 years Consulting with Fortune 1000 companies on Virtualization and Mobility initiatives.',
            LEADERSHIP_BA6_NAME: 'Dan Lovatt, Board Advisor',
            LEADERSHIP_BA6_DESCRIPTION: 'Dan Lovatt has over 30 years of experience in multi-national telecommunication and telecommunications manufacturing in the United States as well as Internationally. Most Recently, Dan served as Chief Executive Officer for PCCW Global where he was responsible for managing the Company&#39;s International Business outside of their home Market of China. Prior to PCCW, he worked as the International CFO for Lucent Technologies as well a number of Services Partners, Content Providers, Telecom Authorities and  Governmental Agencies where he held various management positions.',
            LEADERSHIP_BA7_NAME: 'Bryan Buckley, Board Advisor',
            LEADERSHIP_BA7_DESCRIPTION: 'Oscar Nominated Director Bryan Buckley has been dubbed the \'King of the Super Bowl\' by the New York Times. Directing over 50 commercials for the big game since 2000. Many pieces of Buckley’s work have been inducted into the Museum Of Modern Art’s permanent collection and he is an esteemed recipient of the DGA award, Emmy’s and over 50 Cannes Lions. A 2010 Adweek Readers Poll named Buckley the Commercial Director of the decade and he was also chosen as one of the 50 best Creative Minds in the last 25 years by Creativity Magazine. Buckley\'s directing career started in 1994 when he directed the Emmy Award winning \'This is SportsCenter\' Campaign. In 1997, Buckley co-found Hungryman along with \'This is SportsCenter\' creator, Hank Perlman. By 2004, the company won the Cannes Festival\'s Palme D\'or as the top commercial production company in the world and has finished in the top ten for more than ten consecutive years, the first production company to do so. Buckley wrote and directed the short film ASAD. The film was shot in Africa with an all Somali, refugee cast and screened at over 50 film festivals worldwide, taking top honors at the TriBeCa Film Festival, Austin Film Festival, Florida Film Festival and Michael Moore\'s Traverse City Film Festival, to name a few. In 2013, Buckley was nominated for an Academy Award for ASAD. Buckley\'s first feature film, The Bronze, opened the 2015 Sundance Film Festival. The film stars The Big Bang Theory\'s Melissa Rauch as a foul-mouthed former gymnastics bronze medalist who must fight for her local celebrity status when a new young athlete\'s star rises in town. In 2015 Buckley will direct Men Are From Mars, Women Are From Venus, starring Reese Witherspoon. The film will be an adaptation of Dr. John Gray\'s book, which has sold more copies than any other non-fiction book other than the Bible and Koran.',
            MAIN_ERROR_APP_CONFIG: 'Error fetching application configuration',
            MAIN_ERROR_AIO_SSO: 'Error opening video portal',
            MAIN_FREE_PREVIEW_ENDED: 'Your free preview has ended!',
            MAIN_SIGN_OUT_CONFIRMATION: 'Are you sure you want to sign out of YipTV?',
            MAIN_VIDEO_PORTAL_ALREADY_OPEN: 'Video Portal is already open in another tab',
            MAIN_LANGUAGE_CHANGE_SAVE_CHECK: 'Do you want to change your preferred language to ',
            MAIN_LANGUAGE_CHANGE_SAVE_SUCCESS: 'Language preference saved successfully',
            MAIN_LANGUAGE_CHANGE_SAVE_ERROR: 'Unable to change your language preference. Please contact customer support at',
            NOT_FOUND_HEADING: 'Page Not Found',
            NOT_FOUND_MESSAGE: 'The page you are looking for does not exist.',
            PREFERENCES_HEADING: 'Preferences',
            PREFERENCES_PREFERRED_LANGUAGE: 'Select your preferred language',
            PREFERENCES_PREFERRED_LANGUAGE_REQUIRED: 'Select your preferred language',
            PREFERENCES_SUBMIT_BUTTON: 'Submit',
            PREFERENCES_FETCH_ERROR: 'Unable to fetch your preferences. Please contact customer support at',
            PREFERENCES_SAVE_ERROR: 'Unable to save your preferences. Please contact customer support at',
            PREFERENCES_SUCCESS_HEADING: 'Preferences Saved',
            PREFERENCES_SUCCESS_MESSAGE: 'Your preferences have been saved successfully.',
            RAF_HEADING: 'Refer a friend',
            RAF_MESSAGE: 'Spread the word about YipTV to all of your friends and everybody gets FREE TV. For each one of your friends who sign up as a new customer, you’ll each get a month FREE. Invite them all to join because the offer is unlimited!',
            RAF_FINE_PRINT: '<sup>*</sup>If you (the "Referrer") refer another person (the "Referree") to YIPTV and the Referree completes a valid registration process for a subscription, the Referrer will receive a credit for one-month of their monthly service fee and the Referree will receive a credit for one-month  their monthly service fee (up to $14.99 of credit, per month) if and after the Referree has maintained a paid subscription with YipTV for sixty-one (61) consecutive days. Credit excludes additional charges, including, but not limited to, premium services or features. Cancellation by either Referrer or Referree before sixty-one (61) consecutive days from the date Referree subscribes to YipTV will result in the loss of and/or chargeback of associated credits. In the event that the Referrer or Referree has a balance due, then a credit will be applied. Credits earned have an equivalent non-cash value of one month of service, regardless of past or future subscription price changes to the service. If the customer cancels service with referral credits remaining, than those credits, if any, are forfeited. Credit has no cash value, is nonrefundable and nontransferable. Certain types of referrals, including, but not limited to, referring yourself or someone living in the same residence as you, are prohibited. Offer, prices and charges are subject to change without notice. Other terms and conditions may apply. See terms of use for more information. Void where prohibited. Offer cannot be combined and is subject to restrictions and limitations.',
            RAF_MY_EMAIL: 'My Email',
            RAF_EMAIL_REQUIRED: 'Enter your email address',
            RAF_EMAIL_INVALID: 'Enter a valid email address',
            RAF_IMPORT_CONTACT_LIST: 'Import My Contact List',
            RAF_LOADING: 'Loading...',
            RAF_OR: 'or',
            RAF_ENTER_FRIENDS_EMAIL: 'Enter Friends\' Email Addresses Separated By Commas',
            RAF_SEND_INVITE: 'Send Invite',
            RAF_EMAIL_SEND_ERROR: 'Unable to send YipTV invites to your friends',
            RAF_EMAIL_LIST_REQUIRED: 'Enter at least a single email address',
            RAF_EMAIL_LIST_INVALID: 'One or more email addresses are invalid',
            RAF_SUCCESS_HEADING: 'Invite Sent',
            RAF_SUCCESS_MESSAGE: 'We have sent an invite to your friends',
            REACTIVATE_SUBSCRIPTION_HEADING: 'Re-activate Subscription',
            REACTIVATE_SUBSCRIPTION_MESSAGE: 'Your credit card will be charged $14.99 every month. You can cancel your subscription any time by going to Account > Cancel Subscription',
            REACTIVATE_SUBSCRIPTION_BILLING_INFO: 'Enter your credit card details. If you need help call',
            REACTIVATE_SUBSCRIPTION_CARD_NAME: 'Name on Credit Card',
            REACTIVATE_SUBSCRIPTION_CARD_NAME_REQUIRED: 'Enter name as on your credit card',
            REACTIVATE_SUBSCRIPTION_ADDRESS: 'Billing Address',
            REACTIVATE_SUBSCRIPTION_ADDRESS_REQUIRED: 'Enter address as on your credit card',
            REACTIVATE_SUBSCRIPTION_CITY: 'City',
            REACTIVATE_SUBSCRIPTION_CITY_REQUIRED: 'Enter city as on your credit card',
            REACTIVATE_SUBSCRIPTION_STATE: 'State',
            REACTIVATE_SUBSCRIPTION_STATE_REQUIRED: 'Enter state as on your credit card',
            REACTIVATE_SUBSCRIPTION_STATE_LOAD_ERROR: 'Error loading state list',
            REACTIVATE_SUBSCRIPTION_STATE_SELECT: 'Select One',
            REACTIVATE_SUBSCRIPTION_CARD_NUMBER: 'Credit Card Number',
            REACTIVATE_SUBSCRIPTION_CARD_NUMBER_REQUIRED: 'Enter your credit card number',
            REACTIVATE_SUBSCRIPTION_CARD_NUMBER_ERROR: 'Enter a valid credit card number',
            REACTIVATE_SUBSCRIPTION_CVV: 'CVV',
            REACTIVATE_SUBSCRIPTION_CVV_REQUIRED: 'Enter your CVV',
            REACTIVATE_SUBSCRIPTION_CARD_NUMBER_CVV_ERROR: 'Enter a valid CVV',
            REACTIVATE_SUBSCRIPTION_EXPIRY_DATE: 'Expiration Date (MM/YYYY)',
            REACTIVATE_SUBSCRIPTION_EXPIRY_DATE_REQUIRED: 'Enter your card expiration date',
            REACTIVATE_SUBSCRIPTION_EXPIRY_DATE_INVALID: 'Enter a valid card expiration date',
            REACTIVATE_SUBSCRIPTION_ZIP_CODE: 'Zip Code',
            REACTIVATE_SUBSCRIPTION_ZIP_CODE_REQUIRED: 'Enter zip code as on your credit card',
            REACTIVATE_SUBSCRIPTION_ZIP_CODE_INVALID: 'Enter a valid zip code',
            REACTIVATE_SUBSCRIPTION_CARD_NAME_INVALID: 'Enter a valid name',
            REACTIVATE_SUBSCRIPTION_ADDRESS_INVALID: 'Enter a valid address',
            REACTIVATE_SUBSCRIPTION_CITY_INVALID: 'Enter a valid city',
            REACTIVATE_SUBSCRIPTION_SUBMIT_BUTTON: 'Re-activate Subscription',
            REACTIVATE_SUBSCRIPTION_FAILED: 'Reactivate subscription failed. Please contact customer support at',
            REACTIVATE_SUBSCRIPTION_PROBLEM: 'Having trouble re-activating subscription? Contact customer support at',
            REACTIVATE_SUBSCRIPTION_ACCOUNT_REFRESH_ERROR: 'Please close and re-open the YipTV application browser window',
            REACTIVATE_SUBSCRIPTION_ACCESS_ERROR: 'You cannot re-activate your subscription or your account is already re-activated. Please contact customer support at',
            REACTIVATE_SUBSCRIPTION_ALREADY_ACTIVE: 'Cannot re-activate subscription as you already have an active subscription',
            REACTIVATE_SUBSCRIPTION_SUCCESS_HEADING: 'Subscription Re-activated',
            REACTIVATE_SUBSCRIPTION_SUCCESS_MESSAGE: 'Your subscription has been successfully re-activated.',
            REDIRECT_MESSAGE: 'Redirecting...',
            RESEND_VERIFICATION_HEADING: 'Resend Verification Email',
            RESEND_VERIFICATION_EMAIL: 'Enter your email and we will send a link to verify your account',
            RESEND_VERIFICATION_EMAIL_INVALID: 'Enter a valid email address',
            RESEND_VERIFICATION_EMAIL_REQUIRED: 'Enter your email address',
            RESEND_VERIFICATION_BUTTON: 'Submit',
            RESEND_VERIFICATION_SUCCESS_HEADING: 'Email Sent',
            RESEND_VERIFICATION_SUCCESS_MESSAGE: 'We have sent you the account verification link. Please check your email.',
            RESEND_VERIFICATION_USER_ERROR: 'Account not found or account already activated',
            RESEND_VERIFICATION_ERROR: 'Error sending account verification link. Please contact customer support at',
            RESET_PASSWORD_HEADING: 'Reset Password',
            RESET_PASSWORD_NEW_PASSWORD: 'New Password',
            RESET_PASSWORD_CONFIRM_PASSWORD_REQUIRED: 'Confirm your password',
            RESET_PASSWORD_CONFIRM_PASSWORD: 'Confirm Password',
            RESET_PASSWORD_NEW_PASSWORD_NOT_COMPLEX: 'Password needs to be at least 8 characters, contain 1 uppercase & 1 lowercase letter, 1 number & 1 special character',
            RESET_PASSWORD_NEW_PASSWORD_REQUIRED: 'Enter your password',
            RESET_PASSWORD_CONFIRM_PASSWORD_NO_MATCH: 'Passwords do not match',
            RESET_PASSWORD_BUTTON: 'Submit',
            RESET_PASSWORD_USER_ERROR: 'Unable to change your password. Please contact customer support at',
            RESET_PASSWORD_CODE_ERROR: 'The reset password link has expired and is no longer valid',
            RESET_PASSWORD_SUCCESS_HEADING: 'Password Changed',
            RESET_PASSWORD_SUCCESS_MESSAGE: 'Your password has been changed successfully.',
            SHOWS_TITLE_SPORTS: 'international sports',
            SHOWS_TITLE_NEWS: 'Latin American and Global News',
            SHOWS_TITLE_ENTERTAINMENT: 'Entertainment',
            SHOWS_SPORTS_PNL_1_TITLE: 'Spanish Primera Division Soccer',
            SHOWS_SPORTS_PNL_1_DESC: 'beIN Sports | es,en',
            SHOWS_SPORTS_PNL_1_DESC_CNTNT: 'From Santiago Bernabeu Stadium in Madrid, Spain.',
            SHOWS_SPORTS_PNL_2_TITLE: 'Boxeo',
            SHOWS_SPORTS_PNL_2_DESC: 'TYC Sports',
            SHOWS_SPORTS_PNL_2_DESC_CNTNT: 'Mas de 60 combates nacionales e internacionales por año',
            SHOWS_SPORTS_PNL_3_TITLE: 'Copa America Chile',
            SHOWS_SPORTS_PNL_3_DESC: 'beIN Sports',
            SHOWS_SPORTS_PNL_3_DESC_CNTNT: 'Watch Live on beIN Sports.',
            SHOWS_SPORTS_PNL_4_TITLE: 'Super Bike',
            SHOWS_SPORTS_PNL_4_DESC: 'beIN Sports',
            SHOWS_SPORTS_PNL_4_DESC_CNTNT: 'Watch live on beIN Sports.',
            SHOWS_SPORTS_PNL_5_TITLE: 'Automovilismo',
            SHOWS_SPORTS_PNL_5_DESC: 'TYC Sports',
            SHOWS_SPORTS_PNL_5_DESC_CNTNT: 'TC 2000, Super TC 200 y Top Race v-6',
            SHOWS_SPORTS_PNL_6_TITLE: 'Futbol Argentino - Primera Division',
            SHOWS_SPORTS_PNL_6_DESC: 'TYC Sports',
            SHOWS_SPORTS_PNL_6_DESC_CNTNT: 'Vealo en vivo en beIN Sports',
            SHOWS_NEWS_PNL_1_TITLE: 'tele Fórmula',
            SHOWS_NEWS_PNL_1_DESC: 'teleFórmula',
            SHOWS_NEWS_PNL_1_DESC_CNTNT: 'Mantente al dia con todo actual en Mexico y en el mundo por teleFórmula',
            SHOWS_NEWS_PNL_2_TITLE: 'La Tarde',
            SHOWS_NEWS_PNL_2_DESC: 'NTN24',
            SHOWS_NEWS_PNL_2_DESC_CNTNT: 'El análisis, investigación y la actualidad agenda informativa',
            SHOWS_NEWS_PNL_3_TITLE: 'Planeta Gente',
            SHOWS_NEWS_PNL_3_DESC: 'NTN24',
            SHOWS_NEWS_PNL_3_DESC_CNTNT: 'Las noticias del mundo del entretenimiento',
            SHOWS_NEWS_PNL_4_TITLE: 'NTN24 Nuestra Tele Noticias',
            SHOWS_NEWS_PNL_4_DESC: 'NTN24',
            SHOWS_NEWS_PNL_4_DESC_CNTNT: 'De latinos para latinos',
            SHOWS_NEWS_PNL_5_TITLE: 'Noticias De La Mañana',
            SHOWS_NEWS_PNL_5_DESC: 'Antena 3',
            SHOWS_NEWS_PNL_5_DESC_CNTNT: '',
            SHOWS_NEWS_PNL_6_TITLE: 'Espejo Publico Prsentadores',
            SHOWS_NEWS_PNL_6_DESC: 'Antena 3',
            SHOWS_NEWS_PNL_6_DESC_CNTNT: '',
            SHOWS_ENT_PNL_1_TITLE: 'Seinfeld',
            SHOWS_ENT_PNL_1_DESC: 'JBN',
            SHOWS_ENT_PNL_1_DESC_CNTNT: 'Amigos que viven en Manhattan se obsesionan con las cosas pequeñas',
            SHOWS_ENT_PNL_2_TITLE: 'Tu Cara Me Suena España',
            SHOWS_ENT_PNL_2_DESC: 'COMING SOON',
            SHOWS_ENT_PNL_2_DESC_CNTNT: 'COMING SOON',
            SHOWS_ENT_PNL_3_TITLE: 'El Secreto',
            SHOWS_ENT_PNL_3_DESC: 'COMING SOON',
            SHOWS_ENT_PNL_3_DESC_CNTNT: 'COMING SOON',
            SHOWS_ENT_PNL_4_TITLE: 'The Regional Mexican Music Channel',
            SHOWS_ENT_PNL_4_DESC: 'Video Rola',
            SHOWS_ENT_PNL_4_DESC_CNTNT: 'Conciertos, especiales, videos, exclusivos!',
            SHOWS_ENT_PNL_5_TITLE: 'La Ruleta Séptimo Aniversario',
            SHOWS_ENT_PNL_5_DESC: 'COMING SOON',
            SHOWS_ENT_PNL_5_DESC_CNTNT: 'COMING SOON',
            SHOWS_ENT_PNL_6_TITLE: 'El Tiempo Entre Costuras',
            SHOWS_ENT_PNL_6_DESC: 'COMING SOON',
            SHOWS_ENT_PNL_6_DESC_CNTNT: 'COMING SOON',
            SIGN_IN_HEADING: 'Sign In',
            SIGN_IN_MESSAGE: 'Welcome back to YipTV. Login below to watch your favorite shows.',
            SIGN_IN_EMAIL: 'Email',
            SIGN_IN_EMAIL_REQUIRED: 'Enter your email address',
            SIGN_IN_EMAIL_INVALID: 'Enter a valid email address',
            SIGN_IN_PASSWORD: 'Password',
            SIGN_IN_PASSWORD_REQUIRED: 'Enter your password',
            SIGN_IN_SUBMIT_BUTTON: 'Sign In',
            SIGN_IN_FORGOT_PASSWORD: 'Forgot Password?',
            SIGN_IN_RESET_PASSWORD: 'Reset Password',
            SIGN_IN_NOT_REGISTERED: 'Not Registered Yet?',
            SIGN_IN_SIGN_UP: 'Sign Up',
            SIGN_IN_FAILED_NOT_VERIFIED: 'Sign In failed as your account has not been verified yet',
            SIGN_IN_FAILED: 'Sign In failed',
            SIGN_IN_NO_VERIFICATION_EMAIL: 'Did not receive verification email?',
            SIGN_IN_RESEND_VERIFICATION: 'Request Again',
            SIGN_IN_UPGRADE_SUBSCRIPTION: 'You need to sign in before you can upgrade your subscription.',
            SIGN_IN_REACTIVATE_SUBSCRIPTION: 'You need to sign in before you can re-activate your subscription.',
            SIGN_IN_CANCELED_SUBSCRIPTION_MESSAGE: 'You do not have an active subscription. Do you want to re-activate your subscription?',
            SIGN_IN_TRIAL_ENDED_MESSAGE: 'Your free trial has ended. Do you want to upgrade your subscription?',
            SIGN_IN_COMP_ENDED_MESSAGE: 'Your complimentary subscription has ended. Do you want to upgrade your subscription?',
            SIGN_IN_PAYMENT_PENDING_MESSAGE: 'Payment is pending on your account. CMSWould you like to update your credit card information?',
            SIGN_UP_HEADING: 'Sign Up',
            SIGN_UP_MESSAGE: 'Signing up is easy! There is no contract and you can cancel any time. You’re moments away from getting high quality TV from around the globe. Get ready to see the future of television.',
            SIGN_UP_PROMO: '<img src="images/pages/en/signup-1499.jpg" />',
            SIGN_UP_FIRST_NAME: 'First Name',
            SIGN_UP_FIRST_NAME_REQUIRED: 'Enter your first name',
            SIGN_UP_LAST_NAME_REQUIRED: 'Enter your last name',
            SIGN_UP_FIRST_NAME_INVALID: 'Enter a valid first name',
            SIGN_UP_LAST_NAME_INVALID: 'Enter a valid last name',
            SIGN_UP_CARD_NAME_INVALID: 'Enter a valid name',
            SIGN_UP_ADDRESS_INVALID: 'Enter a valid address',
            SIGN_UP_CITY_INVALID: 'Enter a valid city',
            SIGN_UP_EMAIL: 'Email',
            SIGN_UP_TELEPHONE: 'Telephone',
            SIGN_UP_TELEPHONE_INVALID: 'Enter a valid US telephone number',
            SIGN_UP_TELEPHONE_REQUIRED: 'Enter your telephone number',
            SIGN_UP_LAST_NAME: 'Last Name',
            SIGN_UP_EMAIL_INVALID: 'Enter a valid email address',
            SIGN_UP_EMAIL_EXISTS: 'You already have an account with us. Please sign in.',
            SIGN_UP_EMAIL_REQUIRED: 'Enter your email address',
            SIGN_UP_PASSWORD: 'Password',
            SIGN_UP_PASSWORD_REQUIRED: 'Enter your password',
            SIGN_UP_PASSWORD_NOT_COMPLEX: 'Password needs to be at least 8 characters, contain 1 uppercase & 1 lowercase letter, 1 number & 1 special character',
            SIGN_UP_CONFIRM_PASSWORD: 'Confirm Password',
            SIGN_UP_CONFIRM_PASSWORD_REQUIRED: 'Confirm your password',
            SIGN_UP_CONFIRM_PASSWORD_NO_MATCH: 'Passwords do not match',
            SIGN_UP_BILLING_INFO: 'Billing Information. Need help? Call',
            SIGN_UP_CARD_NAME: 'Name on Credit Card',
            SIGN_UP_CARD_NAME_REQUIRED: 'Enter name as on your credit card',
            SIGN_UP_ADDRESS: 'Billing Address',
            SIGN_UP_ADDRESS_REQUIRED: 'Enter address as on your credit card',
            SIGN_UP_CITY: 'City',
            SIGN_UP_CITY_REQUIRED: 'Enter city as on your credit card',
            SIGN_UP_STATE: 'State',
            SIGN_UP_STATE_REQUIRED: 'Enter state as on your credit card',
            SIGN_UP_STATE_LOAD_ERROR: 'Error loading state list',
            SIGN_UP_STATE_SELECT: 'Select One',
            SIGN_UP_CARD_NUMBER: 'Credit Card Number',
            SIGN_UP_CARD_NUMBER_REQUIRED: 'Enter your credit card number',
            SIGN_UP_CARD_NUMBER_ERROR: 'Enter a valid credit card number',
            SIGN_UP_CVV: 'CVV',
            SIGN_UP_CVV_REQUIRED: 'Enter your CVV',
            SIGN_UP_CARD_NUMBER_CVV_ERROR: 'Enter a valid CVV',
            SIGN_UP_EXPIRY_DATE: 'Expiration Date (MM/YYYY)',
            SIGN_UP_EXPIRY_DATE_REQUIRED: 'Enter your card expiration date',
            SIGN_UP_EXPIRY_DATE_INVALID: 'Enter a valid card expiration date',
            SIGN_UP_ZIP_CODE: 'Zip Code',
            SIGN_UP_ZIP_CODE_REQUIRED: 'Enter zip code as on your credit card',
            SIGN_UP_ZIP_CODE_INVALID: 'Enter a valid zip code',
            SIGN_UP_TERMS_OF_USE: 'Terms of Use',
            SIGN_UP_AND: 'and',
            SIGN_UP_SUBMIT_BUTTON: 'Sign Up',
            SIGN_UP_HAVE_ACCOUNT: 'Already have an account?',
            SIGN_UP_SIGN_IN: 'Sign In',
            SIGN_UP_DISCLAIMER: 'I agree to the YipTV',
            SIGN_UP_DISCLAIMER_END: '',
            SIGN_UP_DISCLAIMER_REQUIRED: 'In order to use YipTV services you need to accept our Terms of Use and Privacy Policy',
            SIGN_UP_PRIVACY_POLICY: 'Privacy Policy',
            SIGN_UP_USER_EXISTS: 'This email is already registered with YipTV. Please use another email address.',
            SIGN_UP_FAILED: 'User sign up failed. Please contact customer support at',
            SIGN_UP_PROBLEM: 'Having trouble signing up? Contact customer support at',
            SIGN_UP_SUCCESS_HEADING: 'Congrats!',
            SIGN_UP_SUCCESS_MESSAGE: 'You are successfully signed up with YipTV. Please click the button or link in the email we have just sent you to verify your account.',
            SIGN_UP_SUCCESS_LOGIN_HEADING: 'Congrats!',
            SIGN_UP_SUCCESS_LOGIN_MESSAGE: 'You have successfully signed up with YipTV. <a class="underline-text" href="/sign-in">Sign In</a> to YipTV now.',
            SIGN_UP_SUCCESS_PAYMENT_PENDING_HEADING: 'Congrats!',
            SIGN_UP_SUCCESS_PAYMENT_PENDING_MESSAGE: 'You have successfully signed up with YipTV but we were unable to process payment on your credit card. Please click the button or link in the email we have just sent you to verify your account, then Sign In and update your credit card information.',
            UNDER_CONSTRUCTION_HEADING: 'Under Construction',
            UNDER_CONSTRUCTION_MESSAGE: 'The page you are looking is under construction and will be available shortly',
            UPGRADE_SUBSCRIPTION_HEADING: 'Upgrade Subscription',
            UPGRADE_SUBSCRIPTION_MESSAGE: 'You are upgrading to a paid account. Your credit card will be charged $14.99 every month. You can cancel your subscription any time by going to Account > Cancel Subscription.',
            UPGRADE_SUBSCRIPTION_BILLING_INFO: 'Enter your credit card details. If you need help call',
            UPGRADE_SUBSCRIPTION_CARD_NAME: 'Name on Credit Card',
            UPGRADE_SUBSCRIPTION_CARD_NAME_REQUIRED: 'Enter name as on your credit card',
            UPGRADE_SUBSCRIPTION_ADDRESS: 'Billing Address',
            UPGRADE_SUBSCRIPTION_ADDRESS_REQUIRED: 'Enter address as on your credit card',
            UPGRADE_SUBSCRIPTION_CITY: 'City',
            UPGRADE_SUBSCRIPTION_CITY_REQUIRED: 'Enter city as on your credit card',
            UPGRADE_SUBSCRIPTION_STATE: 'State',
            UPGRADE_SUBSCRIPTION_STATE_REQUIRED: 'Enter state as on your credit card',
            UPGRADE_SUBSCRIPTION_STATE_LOAD_ERROR: 'Error loading state list',
            UPGRADE_SUBSCRIPTION_STATE_SELECT: 'Select One',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER: 'Credit Card Number',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER_REQUIRED: 'Enter your credit card number',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER_ERROR: 'Enter a valid credit card number',
            UPGRADE_SUBSCRIPTION_CVV: 'CVV',
            UPGRADE_SUBSCRIPTION_CVV_REQUIRED: 'Enter your CVV',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER_CVV_ERROR: 'Enter a valid CVV',
            UPGRADE_SUBSCRIPTION_EXPIRY_DATE: 'Expiration Date (MM/YYYY)',
            UPGRADE_SUBSCRIPTION_EXPIRY_DATE_REQUIRED: 'Enter your card expiration date',
            UPGRADE_SUBSCRIPTION_EXPIRY_DATE_INVALID: 'Enter a valid card expiration date',
            UPGRADE_SUBSCRIPTION_ZIP_CODE: 'Zip Code',
            UPGRADE_SUBSCRIPTION_ZIP_CODE_REQUIRED: 'Enter zip code as on your credit card',
            UPGRADE_SUBSCRIPTION_ZIP_CODE_INVALID: 'Enter a valid zip code',
            UPGRADE_SUBSCRIPTION_CARD_NAME_INVALID: 'Enter a valid name',
            UPGRADE_SUBSCRIPTION_ADDRESS_INVALID: 'Enter a valid address',
            UPGRADE_SUBSCRIPTION_CITY_INVALID: 'Enter a valid city',
            UPGRADE_SUBSCRIPTION_SUBMIT_BUTTON: 'Upgrade',
            UPGRADE_SUBSCRIPTION_FAILED: 'Upgrade subscription failed. Please contact customer support at',
            UPGRADE_SUBSCRIPTION_PROBLEM: 'Having trouble upgrading? Contact customer support at',
            UPGRADE_SUBSCRIPTION_ACCOUNT_REFRESH_ERROR: 'Please close and re-open the YipTV application browser window',
            UPGRADE_SUBSCRIPTION_ALREADY_UPGRADED: 'Cannot upgrade subscription as you are already a paid user.',
            UPGRADE_SUBSCRIPTION_COMP_ACTIVE_USER: 'Cannot upgrade subscription as you have a complimentary subscription.',
            UPGRADE_SUBSCRIPTION_SUCCESS_HEADING: 'Account Upgraded',
            UPGRADE_SUBSCRIPTION_SUCCESS_MESSAGE: 'Congrats! You have been upgraded to a paid user.',
            USER_HOME_WATCH_NOW: 'Watch Now',
            USER_HOME_UPGRADE_SUBSCRIPTION: 'Upgrade Subscription',
            USER_HOME_REACTIVATE_SUBSCRIPTION: 'Re-activate Subscription',
            USER_HOME_ACCOUNT: 'Account',
            USER_HOME_REFER_FRIEND: 'Refer a Friend',
            USER_HOME_CONTACT_US: 'Contact Us',
            USER_DETAILS_HEADING: 'User Details',
            USER_DETAILS_USER_FETCH_ERROR: 'Error fetching user details',
            USER_DETAILS_SUBMIT_BUTTON: 'Submit',
            USER_DETAILS_EMAIL: 'Email',
            USER_DETAILS_EMAIL_REQUIRED: 'Enter the email address',
            USER_DETAILS_EMAIL_INVALID: 'Enter a valid email address',
            USER_DETAILS_FIRST_NAME: 'First Name',
            USER_DETAILS_LAST_NAME: 'Last Name',
            USER_DETAILS_TELEPHONE: 'Telephone',
            USER_DETAILS_CREATED_AT: 'Created At',
            USER_DETAILS_STATUS: 'Status',
            USER_DETAILS_TYPE: 'Type',
            USER_DETAILS_AIO_ACCOUNT_ID: 'AIO Account ID',
            USER_DETAILS_FREESIDE_CUSTOMER_NUMBER: 'FreeSide Customer Number',
            USER_DETAILS_REFERRAL_CODE: 'Referral Code',
            USER_DETAILS_USER_NOT_FOUND: 'User not found',
            VERIFY_USER_HEADING_SUCCESS: 'Account Verified',
            VERIFY_USER_HEADING_ERROR: 'Error',
            VERIFY_USER_MESSAGE_SUCCESS: 'Your account has been successfully verified. You can sign into YipTV using the Sign In button above.',
            VERIFY_USER_MESSAGE_ERROR: 'Unable to verify your account or account is already verified. Please contact customer support at',
        });
    }]);
}(angular.module('app')));
