(function (app) {
    'use strict';

    app.config(['$translateProvider', function ($translateProvider) {
        $translateProvider.translations('es', {
            ACCOUNT_HEADING: 'Cuenta',
            ACCOUNT_CHANGE_PASSWORD: 'Cambio de contrasena',
            ACCOUNT_CHANGE_CREDIT_CARD: 'Cambio de tarjeta de credito',
            ACCOUNT_UPGRADE_SUBSCRIPTION: 'Actualizar suscripcion',
            ACCOUNT_CANCEL_SUBSCRIPTION: 'Cancelar suscripcion',
            ACCOUNT_REACTIVATE_SUBSCRIPTION: 'Reactivar suscripcion',
            ACCOUNT_PREFERENCES: 'Preferencias',
            ACCOUNT_CONTACT_US: 'Contactenos',
            ACCOUNT_CANCEL_SUBSCRIPTION_CONFIRMATION: 'Seguro que desea cancelar su suscripcion?',
            ACCOUNT_CANCEL_SUBSCRIPTION_FAILURE: 'Cancelacion de suscripcion fallo. Por favor pongase en contacto con atencion al cliente',
            ACCOUNT_CANCEL_SUBSCRIPTION_ACCOUNT_REFRESH_ERROR: 'Por favor cierre y vuelva a abrir la ventana del navegador de la aplicacion YipTV',
            ACCOUNT_CANCEL_ON: 'Su suscripción de YipTV ha sido cancelada. Su servicio continuará hasta el final de su ciclo de facturación actual',
            BANNER_1_MOBILE_PORTRAIT: '<a href="/sign-up/paid"><img src="../images/banners/mobile/es/mobile-portrait-1.jpg" alt="banner-1"></a>',
            BANNER_1_MOBILE_LANDSCAPE: '<a href="/sign-up/paid"><img src="../images/banners/mobile/es/mobile-landscape-1.jpg" alt="banner-1"></a>',
            BANNER_1_TABLET: '<a href="/sign-up/paid"><img src="../images/banners/tablet/es/tablet-1.jpg" alt="banner-1"></a>',
            BANNER_1_DESKTOP: '<a href="/sign-up/paid"><img src="../images/banners/desktop/es/desktop-1.jpg" alt="banner-1"></a>',
            CANCEL_SUBSCRIPTION_SUCCESS_HEADING: 'Suscripcion cancelada',
            CANCEL_SUBSCRIPTION_SUCCESS_MESSAGE: 'Su suscripcion ha sido cancelada con exito.',
            CHANGE_CREDIT_CARD_HEADING: 'Cambio de Tarjeta de Credito',
            CHANGE_CREDIT_CARD_BILLING_INFO: 'Introduzca sus nuevos datos de la tarjeta de crédito. Si necesita ayuda llame al',
            CHANGE_CREDIT_CARD_CARD_NAME: 'Nombre en tarjeta de crédito',
            CHANGE_CREDIT_CARD_CARD_NAME_REQUIRED: 'Ingrese nombre como aparece en su tarjeta de credito',
            CHANGE_CREDIT_CARD_ADDRESS: 'Dirección de facturación',
            CHANGE_CREDIT_CARD_ADDRESS_REQUIRED: 'Ingrese direccion como aparece en su tarjeta de credito',
            CHANGE_CREDIT_CARD_CITY: 'Ciudad',
            CHANGE_CREDIT_CARD_CITY_REQUIRED: 'Ingrese ciudad como aparece en su tarjeta de credito',
            CHANGE_CREDIT_CARD_STATE: 'Estado',
            CHANGE_CREDIT_CARD_STATE_REQUIRED: 'Ingrese estado como aparece en su tarjeta de credito',
            CHANGE_CREDIT_CARD_STATE_LOAD_ERROR: 'Error al cargar lista de estados',
            CHANGE_CREDIT_CARD_STATE_SELECT: 'Seleccione uno',
            CHANGE_CREDIT_CARD_CARD_NUMBER: 'Número de tarjeta de crédito',
            CHANGE_CREDIT_CARD_CARD_NUMBER_REQUIRED: 'Introduzca su numero de tarjeta de credito',
            CHANGE_CREDIT_CARD_CARD_NUMBER_ERROR: 'Introduzca un numero de tarjeta de credito valido',
            CHANGE_CREDIT_CARD_CVV: 'Código CVV',
            CHANGE_CREDIT_CARD_CVV_REQUIRED: 'Introduzca codigo CVV',
            CHANGE_CREDIT_CARD_CARD_NUMBER_CVV_ERROR: 'Introduzca codigo CVV valido',
            CHANGE_CREDIT_CARD_EXPIRY_DATE: 'Fecha de expiración (MM/AAAA)',
            CHANGE_CREDIT_CARD_EXPIRY_DATE_REQUIRED: 'Introduzca fecha de expiracion de su tarjeta de credito',
            CHANGE_CREDIT_CARD_EXPIRY_DATE_INVALID: 'Introduzca fecha de expiracion valida',
            CHANGE_CREDIT_CARD_ZIP_CODE: 'Código postal',
            CHANGE_CREDIT_CARD_ZIP_CODE_REQUIRED: 'Introduzca su codigo postal',
            CHANGE_CREDIT_CARD_ZIP_CODE_INVALID: 'Introduzca codigo postal valido',
            CHANGE_CREDIT_CARD_CARD_NAME_INVALID: 'Introduzca nombre valido',
            CHANGE_CREDIT_CARD_ADDRESS_INVALID: 'Introduzca direccion valida',
            CHANGE_CREDIT_CARD_CITY_INVALID: 'Introduzca ciudad valida',
            CHANGE_CREDIT_CARD_SUBMIT_BUTTON: 'Presentar',
            CHANGE_CREDIT_CARD_FAILED: 'Error al cambiar su tarjeta de credito. Por favor pongase en contacto con atencion al cliente',
            CHANGE_CREDIT_CARD_PROBLEM: 'Problemas al cambiar su tarjeta de credito? Pongase en contacto con atencion al cliente',
            CHANGE_CREDIT_CARD_ACCESS_ERROR: 'Usted no puede cambiar su tarjeta de credito. Por favor pongase en contacto con servicio al cliente',
            CHANGE_CREDIT_CARD_PAYMENT_ERROR: 'We were unable to process payment on your card. Please check your credit card information.',
            CHANGE_CREDIT_CARD_FREE_USER_ERROR: 'Trial users cannot add a credit card to their account',
            CHANGE_CREDIT_CARD_ACCOUNT_REFRESH_ERROR: 'Por favor cierre y vuelva a abrir la ventana del navegador de la aplicacion YipTV.',
            CHANGE_CREDIT_CARD_SUCCESS_HEADING: 'Tarjeta de credito cambiada',
            CHANGE_CREDIT_CARD_SUCCESS_MESSAGE: 'Su tarjeta de credito ha sido cambiada con exito',
            CHANGE_PASSWORD_HEADING: 'Cambio de Contrasena',
            CHANGE_PASSWORD_CURRENT_PASSWORD: 'Contrasena actual',
            CHANGE_PASSWORD_NEW_PASSWORD: 'Contrasena nueva',
            CHANGE_PASSWORD_CONFIRM_PASSWORD: 'Confirme contrasena nueva',
            CHANGE_PASSWORD_BUTTON: 'Presentar',
            CHANGE_PASSWORD_CURRENT_PASSWORD_REQUIRED: 'Introduzca su contrasena actual',
            CHANGE_PASSWORD_NEW_PASSWORD_REQUIRED: 'Introduzca contrasena nueva',
            CHANGE_PASSWORD_NEW_PASSWORD_NOT_COMPLEX: 'Contrasena debe tener al menos 6 caracteres, 1 letra mayuscula y 1 numero',
            CHANGE_PASSWORD_NEW_PASSWORD_SAME: 'Contrasena nueva no puede ser la misma contrasena actual',
            CHANGE_PASSWORD_CONFIRM_PASSWORD_REQUIRED: 'Confirme su contrasena',
            CHANGE_PASSWORD_CONFIRM_PASSWORD_NO_MATCH: 'Contrasenas no coinciden',
            CHANGE_PASSWORD_ERROR: 'Se produjo un error al cambiar la contrasena',
            CHANGE_PASSWORD_INCORRECT_PASSWORD: 'Contrasena introducida es incorrecta',
            CHANGE_PASSWORD_SUCCESS_HEADING: 'Contrasena Cambiada',
            CHANGE_PASSWORD_SUCCESS_MESSAGE: 'Su contrasena ha sido cambiada con exito',
            CMS_URL_ABOUT_US: 'index.php/nosotros/',
            CMS_URL_FAQS: 'index.php/preguntas-frecuentes/',
            CMS_URL_MAIN: 'index.php/yip-now/',
            CMS_URL_PRIVACY_POLICY: 'index.php/privacy-policy-2/',
            CMS_URL_TOUS: 'index.php/terms-of-service-2/',
            CMS_URL_EULA: 'index.php/acuerdo-de-licencia/',
            CMS_URL_NETWORKS: 'index.php/es/redes-y-canales/',
            CMS_BANNER_3: 'index.php/copa-america-2/',
            COMP_SIGN_UP_HEADING: 'Registrarse',
            COMP_SIGN_UP_MESSAGE: 'Regístrate para obtener una cuenta gratuito a YipTV.',
            COMP_SIGN_UP_VERIFYING: 'Verificación...',
            COMP_SIGN_UP_CODE_EXPIRED: 'Su código de invitación no es válido o ha expirado!',
            COMP_SIGN_UP_FIRST_NAME: 'Nombre',
            COMP_SIGN_UP_FIRST_NAME_REQUIRED: 'Ingrese su nombre',
            COMP_SIGN_UP_LAST_NAME_REQUIRED: 'Ingrese su apellido',
            COMP_SIGN_UP_FIRST_NAME_INVALID: 'Introduzca nombre valido',
            COMP_SIGN_UP_LAST_NAME_INVALID: 'Introduzca apellido valido',
            COMP_SIGN_UP_EMAIL: 'Dirección de correo electrónico',
            COMP_SIGN_UP_TELEPHONE: 'Teléfono',
            COMP_SIGN_UP_TELEPHONE_INVALID: 'Introduzca un numero de telefono valido de EE.UU',
            COMP_SIGN_UP_TELEPHONE_REQUIRED: 'Introduzca su numero de telefono',
            COMP_SIGN_UP_LAST_NAME: 'Apellido',
            COMP_SIGN_UP_EMAIL_INVALID: 'Introduzca una dirreccion de correo electronico valida',
            COMP_SIGN_UP_EMAIL_EXISTS: 'Usted ya tiene cuenta con nosotros. Por favor ingresar.',
            COMP_SIGN_UP_EMAIL_REQUIRED: 'Introduzca su direccion de correo electronico',
            COMP_SIGN_UP_PASSWORD: 'Contraseña',
            COMP_SIGN_UP_PASSWORD_REQUIRED: 'Introduzca su contrasena',
            COMP_SIGN_UP_PASSWORD_NOT_COMPLEX: 'Contrasena debe tener al menos 6 caracteres, 1 letra mayuscula y 1 numero',
            COMP_SIGN_UP_CONFIRM_PASSWORD: 'Confirmar contraseña',
            COMP_SIGN_UP_CONFIRM_PASSWORD_REQUIRED: 'Confirme su contrasena',
            COMP_SIGN_UP_CONFIRM_PASSWORD_NO_MATCH: 'Contrasenas no coinciden',
            COMP_SIGN_UP_TERMS_OF_USE: 'Términos de uso',
            COMP_SIGN_UP_AND: 'y la',
            COMP_SIGN_UP_SUBMIT_BUTTON: 'Registrarse',
            COMP_SIGN_UP_HAVE_ACCOUNT: 'Ya tienes una cuenta?',
            COMP_SIGN_UP_SIGN_IN: 'Ingresar',
            COMP_SIGN_UP_DISCLAIMER: 'Acepto los',
            COMP_SIGN_UP_DISCLAIMER_END: 'de YipTV.',
            COMP_SIGN_UP_DISCLAIMER_REQUIRED: 'Para utilizar los servicios YipTV usted necesita aceptar nuestras condiciones de uso y politica de privacidad',
            COMP_SIGN_UP_PRIVACY_POLICY: 'Política de privacidad',
            COMP_SIGN_UP_USER_EXISTS: 'Esta direccion de correo electronico ya esta registrada con YipTV. Por favor, use otra direccion de correo electronico',
            COMP_SIGN_UP_REUSE_CODE: 'Usted ya utilizó este código de invitación',
            COMP_SIGN_UP_FAILED: 'Error al contratar Usuario. Por favor pongase en contacto con servico al cliente',
            COMP_SIGN_UP_PROBLEM: '¿Tiene problemas para registrarse? Comuníquese con el servicio al cliente al',
            CONTACT_US_HEADING: 'Contáctenos',
            CONTACT_US_NAME: 'Nombre',
            CONTACT_US_INTEREST: 'Interés',
            CONTACT_US_INTEREST_SELECT: 'Seleccione uno',
            CONTACT_US_INTEREST_INVESTOR: 'Ser un inversionista de YipTV',
            CONTACT_US_INTEREST_TECHNICAL: 'Soporte técnico',
            CONTACT_US_INTEREST_BILLING: 'Soporte de facturación',
            CONTACT_US_EMAIL: 'Dirección de correo electrónico',
            CONTACT_US_TELEPHONE: 'Teléfono',
            CONTACT_US_TELEPHONE_INVALID: 'Introduzca un numero de telefono valido de EE.UU',
            CONTACT_US_DETAILS: '¿Cómo podemos ayudarlo?',
            CONTACT_US_COUNTRY: 'País',
            CONTACT_US_COUNTRY_SELECT: 'Seleccione uno',
            CONTACT_US_COUNTRY_REQUIRED: 'Seleccione su Pais',
            CONTACT_US_SUBMIT_BUTTON: 'Enviar',
            CONTACT_US_NAME_REQUIRED: 'Introduzca su nombre',
            CONTACT_US_INTEREST_REQUIRED: 'Introduzca su tipo de interes',
            CONTACT_US_EMAIL_REQUIRED: 'Introduzca su Email',
            CONTACT_US_EMAIL_INVALID: 'Introduzca Email valido',
            CONTACT_US_DETAILS_REQUIRED: 'Como podemos ayudarle?',
            CONTACT_US_TELEPHONE_REQUIRED: 'Introduzca su numero de telefono',
            CONTACT_US_ERROR: 'Error al enviar su solicitud',
            CONTACT_US_COUNTRY_LOAD_ERROR: 'Error al cargar la lista de paises',
            CONTACT_US_SUCCESS_HEADING: 'Solicitud Presentada',
            CONTACT_US_SUCCESS_MESSAGE: 'Su solicitud ha sido enviado con exito',
            CUSTOMER_SUPPORT_HEADING: 'Atencion al Cliente',
            CUSTOMER_SUPPORT_MESSAGE: 'Por favor pongase en contacto con el departamento de atencion al cliente',
            DOWNLOAD_MOBILE_APP: '¡Aplicación para móvil gratis para clientes YipTV!',
            DOWNLOAD_PARA: 'Clientes registrados obtienen nuestra aplicación de TV gratis para ver YipTV en vivo en cualquier lugar en teléfonos inteligentes y tablets. ¡Comience ahora!',
            DOWNLOAD_BULLET_1: 'Regístrate para YipTV <a href=\'/sign-up/paid\'>aquí</a>',
            DOWNLOAD_BULLET_2: 'Baja nuestra aplicación del App Store o Google Play',
            DOWNLOAD_BULLET_3: 'Ve TV en vivo en su dispositivo por Wi-Fi, 3G, 4G o LTE.',
            DOWNLOAD_FINE_PRINT: '* Es necesario tener acceso al Internet. Pueden aplicar tarifas de datos',
            ERROR_HEADING: 'Error',
            ERROR_MESSAGE: 'Se ha producido un error inesperado. Por favor, vuelva a intentarlo. Si el error persiste, pongase en contacto con atencion al cliente',
            FORGOT_PASSWORD_HEADING: 'Olvidado Contrasena',
            FORGOT_PASSWORD_EMAIL: 'Introduzca su direccion de correo electronico y le enviaremos un enlace para restablecer su contrasena',
            FORGOT_PASSWORD_BUTTON: 'Presentar',
            FORGOT_PASSWORD_EMAIL_INVALID: 'Introduzca email valido',
            FORGOT_PASSWORD_EMAIL_REQUIRED: 'Introduzca su email',
            FORGOT_PASSWORD_ERROR: 'Error al enviar el enlace de restablecimiento de contrasena. Por favor pongase en contacto con servico al cliente',
            FORGOT_PASSWORD_SUCCESS_HEADING: 'Email Enviado',
            FORGOT_PASSWORD_SUCCESS_MESSAGE: 'Enlace de restablecimiento de contrasena y instrucciones han sido enviado a su direccion de email',
            FOOTER_HEADER_CAPTION: 'Noticias vivas del reloj, deportes',
            FOOTER_JOIN_BUTTON: 'Crearte una cuenta',
            FOOTER_TRIAL_BUTTON: 'Probar por 7 días',
            FOOTER_CONTACT_US: 'Contáctenos',
            FOOTER_ABOUT_US: 'Sobre nosotros',
            FOOTER_LEADERSHIP: 'Liderazgo',
            FOOTER_BLOG: 'Blog',
            FOOTER_PRIVACY_POLICY: 'Política de privacidad',
            FOOTER_TERMS_OF_USE: 'Términos de uso',
            FOOTER_FAQ: 'Preguntas frecuentes',
            FOOTER_END_USER_LICENSE_AGREEMENT: 'Acuerdo de Licencia de software para Usuario',
            FOOTER_SOCIAL_MEDIA: '<a target="_blank" href="https://www.facebook.com/yiptvespanol"><img src="images/facebook.png" alt=""/></a><a target="_blank" href="https://twitter.com/YipTV"><img src="images/twitter.png" alt=""/></a>',
            FOOTER_CHANNEL_SPORTS: 'deportes',
            FOOTER_CHANNEL_SPORTS_1: 'index.php/es/redes-y-canales/deportes/bein-sports-2/',
            FOOTER_CHANNEL_SPORTS_2: 'index.php/es/redes-y-canales/deportes/bein-sports-n-2/',
            FOOTER_CHANNEL_SPORTS_3: 'index.php/es/redes-y-canales/deportes/tyc-sports/',
            FOOTER_CHANNEL_SPORTS_4: 'index.php/es/redes-y-canales/deportes/pxtv-action-latam/',
            FOOTER_CHANNEL_SPORTS_5: 'index.php/es/redes-y-canales/deportes/aym-sports/',
            FOOTER_CHANNEL_KIDS: 'Niños',
            FOOTER_CHANNEL_KIDS_1: 'index.php/es/redes-y-canales/ninos/smile-of-a-child-2/',
            FOOTER_CHANNEL_GENERAL: 'general',
            FOOTER_CHANNEL_GENERAL_1: 'index.php/es/redes-y-canales/general/bolivia-tv-2/',
            FOOTER_CHANNEL_GENERAL_2: 'index.php/es/redes-y-canales/general/canal-america-2/',
            FOOTER_CHANNEL_GENERAL_3: 'index.php/es/redes-y-canales/general/promovision/',
            FOOTER_CHANNEL_GENERAL_4: 'index.php/es/redes-y-canales/general/tv-chile/',
            FOOTER_CHANNEL_GENERAL_5: 'index.php/es/redes-y-canales/general/cbtv-2/',
            FOOTER_CHANNEL_NEWS: 'noticias',
            FOOTER_CHANNEL_NEWS_1: 'index.php/es/redes-y-canales/noticias/canal-tiempo-2/',
            FOOTER_CHANNEL_NEWS_2: 'index.php/es/redes-y-canales/noticias/cb24/',
            FOOTER_CHANNEL_NEWS_3: 'index.php/es/redes-y-canales/noticias/maya-tv-2/',
            FOOTER_CHANNEL_NEWS_4: 'index.php/es/redes-y-canales/noticias/meionorte-2/',
            FOOTER_CHANNEL_NEWS_5: 'index.php/es/redes-y-canales/noticias/ntn24-2/',
            FOOTER_CHANNEL_NEWS_6: 'index.php/es/redes-y-canales/noticias/one-america-news-2/',
            FOOTER_CHANNEL_NEWS_7: 'index.php/es/redes-y-canales/noticias/rt-espanol-2/',
            FOOTER_CHANNEL_NEWS_8: 'index.php/es/redes-y-canales/noticias/rt-news-2/',
            FOOTER_CHANNEL_NEWS_9: 'index.php/es/redes-y-canales/noticias/telesur-2/',
            FOOTER_CHANNEL_MUSIC: 'musica',
            FOOTER_CHANNEL_MUSIC_1: 'index.php/es/redes-y-canales/musica/az-clic-2/',
            FOOTER_CHANNEL_MUSIC_2: 'index.php/es/redes-y-canales/musica/clubbing-tv-2/',
            FOOTER_CHANNEL_MUSIC_3: 'index.php/es/redes-y-canales/musica/el-cantinazo-2/',
            FOOTER_CHANNEL_MUSIC_4: 'index.php/es/redes-y-canales/musica/jctv-2/',
            FOOTER_CHANNEL_MUSIC_5: 'index.php/es/redes-y-canales/musica/mi-gente-2/',
            FOOTER_CHANNEL_MUSIC_6: 'index.php/es/redes-y-canales/musica/mi-musica-2/',
            FOOTER_CHANNEL_MUSIC_7: 'index.php/es/redes-y-canales/musica/video-rola-2/',
            FOOTER_CHANNEL_EDUCATION: 'Educacional',
            FOOTER_CHANNEL_EDUCATION_1: 'index.php/es/redes-y-canales/entretenimiento/hitn-3/',
            FOOTER_CHANNEL_EDUCATION_2: 'index.php/es/redes-y-canales/educacional/yes-2/',
            FOOTER_CHANNEL_EDUCATION_3: 'index.php/es/redes-y-canales/educacional/zoom/',
            FOOTER_CHANNEL_LIFESTYLE: 'Estilo de Vida',
            FOOTER_CHANNEL_LIFESTYLE_1: 'index.php/es/redes-y-canales/estilo-de-vida/destinos-tv-2/',
            FOOTER_CHANNEL_LIFESTYLE_2: 'index.php/es/redes-y-canales/estilo-de-vida/trendy-2/',
            FOOTER_CHANNEL_FAITH: 'fe',
            FOOTER_CHANNEL_FAITH_1: 'index.php/es/redes-y-canales/fe/enlace-juvenil-2/',
            FOOTER_CHANNEL_FAITH_2: 'index.php/es/redes-y-canales/fe/tbn/',
            FOOTER_CHANNEL_FAITH_3: 'index.php/es/redes-y-canales/fe/tbn-enlance/',
            FOOTER_CHANNEL_FAITH_4: 'index.php/es/redes-y-canales/fe/tele-vid/',
            FOOTER_CHANNEL_FAITH_5: 'index.php/es/redes-y-canales/fe/the-church-channel-2/',
            FOOTER_CHANNEL_ENTERTAINMENT: 'entretenimiento',
            FOOTER_CHANNEL_ENTERTAINMENT_1: 'index.php/es/redes-y-canales/entretenimiento/hola-tv-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_2: 'index.php/es/redes-y-canales/entretenimiento/rcn-novelas-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_3: 'index.php/es/redes-y-canales/entretenimiento/caribvision-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_4: 'index.php/es/redes-y-canales/entretenimiento/la-telenovela-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_5: 'index.php/es/redes-y-canales/entretenimiento/canal-52-mx-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_6: 'index.php/es/redes-y-canales/entretenimiento/tvc-latino-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_7: 'index.php/es/redes-y-canales/entretenimiento/tv-quisqueya-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_8: 'index.php/es/redes-y-canales/entretenimiento/tempo-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_9: 'index.php/es/redes-y-canales/entretenimiento/a3-series-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_10: 'index.php/es/redes-y-canales/entretenimiento/teleformula-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_11: 'index.php/es/redes-y-canales/entretenimiento/telepacifico-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_12: 'index.php/es/redes-y-canales/entretenimiento/tele-medellin/',
            FOOTER_CHANNEL_ENTERTAINMENT_13: 'index.php/es/redes-y-canales/entretenimiento/tele-caribe-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_14: 'index.php/es/redes-y-canales/entretenimiento/teleantioquia-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_15: 'index.php/es/redes-y-canales/entretenimiento/jbn-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_16: 'index.php/es/redes-y-canales/entretenimiento/hitn-3/',
            FOOTER_CHANNEL_ENTERTAINMENT_17: 'index.php/es/redes-y-canales/entretenimiento/cosmovision-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_18: 'index.php/es/redes-y-canales/entretenimiento/canal-tro-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_19: 'index.php/es/redes-y-canales/entretenimiento/canal-sur-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_20: 'index.php/es/redes-y-canales/entretenimiento/canal-antiestres-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_21: 'index.php/es/redes-y-canales/entretenimiento/antena3-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_22: 'index.php/es/redes-y-canales/entretenimiento/az-corazon-2/',
            FOOTER_CHANNEL_ENTERTAINMENT_23: 'index.php/es/redes-y-canales/entretenimiento/telemicro-internacional-3/',
            FOOTER_SOCIAL_MEDIA_LINK: 'COPA AMERICA 2015 SCHEDULE AND SCORES',
            FOOTER_CAPTION_PARAGRAPH: 'YipTV loves soccer, and we know you do too! We want to keep you up-to-date on upcoming games and scores….',
            FOOTER_CAPTION_LINK: 'index.php/copa-america-2015-schedule-and-scores-2/',
            FOOTER_YIP_NOW:'YipNow',
            FOOTER_READ_MORE: 'Read more',
            FREE_SIGN_UP_HEADING: 'Registrarse',
            FREE_SIGN_UP_MESSAGE: 'Comience su prueba gratuita de 7 días ahora! No es necesaria una tarjeta de crédito.',
            FREE_SIGN_UP_FIRST_NAME: 'Nombre',
            FREE_SIGN_UP_FIRST_NAME_REQUIRED: 'Ingrese su nombre',
            FREE_SIGN_UP_LAST_NAME_REQUIRED: 'Ingrese su apellido',
            FREE_SIGN_UP_FIRST_NAME_INVALID: 'Introduzca nombre valido',
            FREE_SIGN_UP_LAST_NAME_INVALID: 'Introduzca apellido valido',
            FREE_SIGN_UP_EMAIL: 'Dirección de correo electrónico',
            FREE_SIGN_UP_TELEPHONE: 'Teléfono',
            FREE_SIGN_UP_TELEPHONE_INVALID: 'Introduzca un numero de telefono valido de EE.UU',
            FREE_SIGN_UP_TELEPHONE_REQUIRED: 'Introduzca su numero de telefono',
            FREE_SIGN_UP_LAST_NAME: 'Apellido',
            FREE_SIGN_UP_EMAIL_INVALID: 'Introduzca una dirreccion de correo electronico valida',
            FREE_SIGN_UP_EMAIL_EXISTS: 'Usted ya tiene cuenta con nosotros. Por favor ingresar.',
            FREE_SIGN_UP_EMAIL_REQUIRED: 'Introduzca su direccion de correo electronico',
            FREE_SIGN_UP_PASSWORD: 'Contraseña',
            FREE_SIGN_UP_PASSWORD_REQUIRED: 'Introduzca su contrasena',
            FREE_SIGN_UP_PASSWORD_NOT_COMPLEX: 'Contrasena debe tener al menos 6 caracteres, 1 letra mayuscula y 1 numero',
            FREE_SIGN_UP_CONFIRM_PASSWORD: 'Confirmar contraseña',
            FREE_SIGN_UP_CONFIRM_PASSWORD_REQUIRED: 'Confirme su contrasena',
            FREE_SIGN_UP_CONFIRM_PASSWORD_NO_MATCH: 'Contrasenas no coinciden',
            FREE_SIGN_UP_TERMS_OF_USE: 'Términos de uso',
            FREE_SIGN_UP_AND: 'y la',
            FREE_SIGN_UP_SUBMIT_BUTTON: 'Registrarse',
            FREE_SIGN_UP_HAVE_ACCOUNT: 'Ya tienes una cuenta?',
            FREE_SIGN_UP_SIGN_IN: 'Ingresar',
            FREE_SIGN_UP_DISCLAIMER: 'Acepto los',
            FREE_SIGN_UP_DISCLAIMER_END: 'de YipTV.',
            FREE_SIGN_UP_DISCLAIMER_REQUIRED: 'Para utilizar los servicios YipTV usted necesita aceptar nuestras condiciones de uso y politica de privacidad',
            FREE_SIGN_UP_PRIVACY_POLICY: 'Política de privacidad',
            FREE_SIGN_UP_USER_EXISTS: 'Esta direccion de correo electronico ya esta registrada con YipTV. Por favor, use otra direccion de correo electronico',
            FREE_SIGN_UP_FAILED: 'Error al contratar Usuario. Por favor pongase en contacto con servico al cliente',
            FREE_SIGN_UP_PROBLEM: '¿Tiene problemas para registrarse? Comuníquese con el servicio al cliente al',
            IDT_SIGN_UP_QUESTIONS: 'Preguntas? Llama a servicio al cliente a',
            IDT_SIGN_UP_MESSAGE: 'Inscribete y empiece a ver mas de 60 canales inmediato! Ve desde tu móvil, PC, TV inteligente o tablet en cualquier lugar que tenga internet. Cable, ni otros dispositivos necesarios . Comparte tu cuenta YipTV con la familia en un máximo de 5 dispositivos.',
            IDT_SIGN_UP_ORDER_SUMMARY: 'Resumen de Orden',
            IDT_SIGN_UP_ORDER: 'Orden:',
            IDT_SIGN_UP_ORDER_DETAILS: '1 mes de Yiptv - Comparte con la Familia - hasta 5 dispositivos',
            IDT_SIGN_UP_FEE: 'Cuota mensual fija:',
            IDT_SIGN_UP_FEE_DETAILS: '<span class="bolder-text">$14.99</span> (No cargos ocultos)',
            IDT_SIGN_UP_TERMS: 'Terminos:',
            IDT_SIGN_UP_TERMS_DETAILS: 'No contratos, cancela en cualquier momento.',
            IDT_SIGN_UP_FIRST_NAME: 'Nombre',
            IDT_SIGN_UP_FIRST_NAME_REQUIRED: 'Ingrese su nombre',
            IDT_SIGN_UP_LAST_NAME_REQUIRED: 'Ingrese su apellido',
            IDT_SIGN_UP_FIRST_NAME_INVALID: 'Introduzca nombre valido',
            IDT_SIGN_UP_LAST_NAME_INVALID: 'Introduzca apellido valido',
            IDT_SIGN_UP_CARD_NAME_INVALID: 'Introduzca nombre valido',
            IDT_SIGN_UP_ADDRESS_INVALID: 'Introduzca direccion valida',
            IDT_SIGN_UP_CITY_INVALID: 'Introduzca ciudad valida',
            IDT_SIGN_UP_EMAIL: 'Correo electrónico',
            IDT_SIGN_UP_TELEPHONE: 'Teléfono',
            IDT_SIGN_UP_TELEPHONE_INVALID: 'Introduzca un numero de telefono valido de EE.UU',
            IDT_SIGN_UP_TELEPHONE_REQUIRED: 'Introduzca su numero de telefono',
            IDT_SIGN_UP_LAST_NAME: 'Apellido',
            IDT_SIGN_UP_EMAIL_INVALID: 'Introduzca una dirreccion de correo electronico valida',
            IDT_SIGN_UP_EMAIL_EXISTS: 'Usted ya tiene cuenta con nosotros. Por favor ingresar.',
            IDT_SIGN_UP_EMAIL_REQUIRED: 'Introduzca su direccion de correo electronico',
            IDT_SIGN_UP_PASSWORD: 'Contraseña',
            IDT_SIGN_UP_PASSWORD_REQUIRED: 'Introduzca su contrasena',
            IDT_SIGN_UP_PASSWORD_NOT_COMPLEX: 'Contrasena debe tener al menos 6 caracteres, 1 letra mayuscula y 1 numero',
            IDT_SIGN_UP_CONFIRM_PASSWORD: 'Confirmar contraseña',
            IDT_SIGN_UP_CONFIRM_PASSWORD_REQUIRED: 'Confirme su contrasena',
            IDT_SIGN_UP_CONFIRM_PASSWORD_NO_MATCH: 'Contrasenas no coinciden',
            IDT_SIGN_UP_BILLING_INFO: 'Información De Facturación',
            IDT_SIGN_UP_ACCOUNT_INFO: 'Información de la cuenta',
            IDT_SIGN_UP_CARD_NAME: 'Nombre en la tarjeta de crédito',
            IDT_SIGN_UP_CARD_NAME_REQUIRED: 'Ingrese nombre como aparece en su tarjeta de credito',
            IDT_SIGN_UP_ADDRESS: 'Dirección de facturación',
            IDT_SIGN_UP_ADDRESS_REQUIRED: 'Ingrese direccion como aparece en su tarjeta de credito',
            IDT_SIGN_UP_CITY: 'Ciudad',
            IDT_SIGN_UP_CITY_REQUIRED: 'Ingrese ciudad como aparece en su tarjeta de credito',
            IDT_SIGN_UP_STATE: 'Estado',
            IDT_SIGN_UP_STATE_REQUIRED: 'Ingrese estado como aparece en su tarjeta de credito',
            IDT_SIGN_UP_STATE_LOAD_ERROR: 'Error al cargar lista de estados',
            IDT_SIGN_UP_STATE_SELECT: 'Seleccione uno',
            IDT_SIGN_UP_CARD_NUMBER: 'Número de tarjeta de crédito',
            IDT_SIGN_UP_CARD_NUMBER_REQUIRED: 'Introduzca su numero de tarjeta de credito',
            IDT_SIGN_UP_CARD_NUMBER_ERROR: 'Introduzca un numero de tarjeta de credito valido',
            IDT_SIGN_UP_CVV: 'Código de seguridad',
            IDT_SIGN_UP_CVV_REQUIRED: 'Introduzca codigo CVV',
            IDT_SIGN_UP_CARD_NUMBER_CVV_ERROR: 'Introduzca codigo CVV valido',
            IDT_SIGN_UP_EXPIRY_DATE: 'Fecha de vencimiento',
            IDT_SIGN_UP_EXPIRY_DATE_REQUIRED: 'Introduzca fecha de expiracion de su tarjeta de credito',
            IDT_SIGN_UP_EXPIRY_DATE_INVALID: 'Introduzca fecha de expiracion valida',
            IDT_SIGN_UP_ZIP_CODE: 'Código Postal',
            IDT_SIGN_UP_ZIP_CODE_REQUIRED: 'Introduzca su codigo postal',
            IDT_SIGN_UP_ZIP_CODE_INVALID: 'Introduzca codigo postal valido',
            IDT_SIGN_UP_TERMS_OF_USE: 'términos de uso',
            IDT_SIGN_UP_AND: 'de YipTV y',
            IDT_SIGN_UP_SUBMIT_BUTTON: 'Ingresar mi orden',
            IDT_SIGN_UP_DISCLAIMER: 'Acepto los',
            IDT_SIGN_UP_DISCLAIMER_END: '',
            IDT_SIGN_UP_DISCLAIMER_REQUIRED: 'Para utilizar los servicios YipTV usted necesita aceptar nuestras condiciones de uso y politica de privacidad',
            IDT_SIGN_UP_PRIVACY_POLICY: 'póliza de privacidad',
            IDT_SIGN_UP_USER_EXISTS: 'Esta direccion de correo electronico ya esta registrada con YipTV. Por favor, use otra direccion de correo electronico',
            IDT_SIGN_UP_FAILED: 'Error al contratar Usuario. Por favor pongase en contacto con servico al cliente',
            IDT_SIGN_UP_PROBLEM: 'Tiene problemas al inscribirse? Llame sevicio al cliente a:',
            INDEX_OTHER_LANGUAGE: 'English',
            INDEX_ABOUT_US: 'Nosotros',
            INDEX_SIGN_IN: 'Ingresar',
            INDEX_JOIN_NOW: 'Únase Ahora',
            INDEX_TRY_FREE: 'Probar por 7 días',
            INDEX_WATCH_NOW: 'Mirar ahora',
            INDEX_NETWORKS: 'Redes y Canales',
            INDEX_SHOWS_BY_CATEGORY: 'Programación por Categoria',
            INDEX_ACCOUNT: 'Cuenta',
            INDEX_ADMIN: 'Administracion',
            INDEX_FAQ_ACRONYM: 'Preguntas frecuentes',
            INDEX_SIGN_OUT: 'Desconectar',
            INDEX_WELCOME: 'Bienvenida',
            INDEX_OK_BUTTON: 'Okay',
            INDEX_YES_BUTTON: 'Sí',
            INDEX_NO_BUTTON: 'No',
            INDEX_LANGUAGE_DROPDOWN: 'Idioma',
            INDEX_CONTACT_NUMBER: 'Llámanos gratis: <a href=\'tel:+18559194788\'>855-919-4788</a>',
            INDEX_USER_DROPDOWN: 'Ingresar',
            INDEX_COPYRIGHT: 'Derechos de Autor ® 2012-2015 YIPTV. Uso de el servicio de YIPTV y de esta pagina web constituye aceptación de nuestros términos de uso y póliza de privacidad.',
            LEADERSHIP_HEADING: 'Liderazgo',
            LEADERSHIP_DESCRIPTION: 'Nuestro equipo de gestion es un grupo experimentado, y hemos interrumpido industrias viejas antes, pero todavia pensamos como los jovenes. Llegamos al punto y nos mantenemos enfocado en lo que mas importa a los clientes. Cuando nosotros escribimos una lista conteniendo las cosas que queriamos para nuestras propias familias en un distribuidor de canales de television, nos dimos cuenta de que ninguna empresa habia realizado esas cosas todavia. Entonces nos dimos cuenta de que teniamos que tratar de construir esa compania a nosotros mismos. Y eso es lo que hemos hecho. Nuestro Consejo de Administracion esta integrado por gigantes en la industria y mentes brillantes. Tenemos suerte de tenerlos. Igualmente nuestros inversores. Nuestro equipo se puede distinguir, pero aqui nadie toma demasiado en serio. Asi se construye una empresa que la gente quiere unirse a. Aqui les presentamos mas informacion acerca de nuestros fondos colectivos.',
            LEADERSHIP_EXECUTIVES_TITLE: 'Nuestros Executivos',
            LEADERSHIP_CHAIRMAN_NAME: 'Michael Tribolet, Presidente, Co-Fundador, Director Ejecutivo',
            LEADERSHIP_CHAIRMAN_DESCRIPTION: 'Michael Tribolet es un empresario con amplia experiencia en la construccion y venta de rapido crecimiento de alta tecnologia en empresas pequenas, las redes empresariales y de negocios basado en consumo. Su competencia incluye la administracion, el desarrollo empresarial, la atencion al cliente, mercadeo, operaciones, ventas, estrategia y gestión general de empresas. Con mas de 20 anos de experiencia de construccion de empresas privadas y publica con operaciones transfronterizas, Michael ha sido fundamental en el desarrollo de la estrategia y la consecucion de las tacticas necesarias para gestionar el crecimiento de la empresa. Recientemente, Michael se desempeno como CEO/Director General de ACN de Europa, donde fue responsable de ingresos anuales en exceso de $500M en ventas de mercadeo de telecomunicaciones, broadband y productos energeticos. Antes de CAN, servio como presidente de VONAGE ayudando en el desarroyo de la compañía a 2.6 millones de clientes, creciendo ingresos de le empresa desde $2 millones a $900M en menos de 5 años. Michael participo en la crianza de $1 mil millon de dolares durante su gestion en Vonage. Sus responsabilidades incluyeron la supervision de ventas, mercadeo, atencion al cliente y una gran variedad de funciones operativas, tales como las operaciones de sistema y la gestion de aplicaciones, y relaciones con operadores, las operaciones de la red, logistica y control de calidad. Antes de unirse a Vonage, el Sr. Tribolet se desempeno como Vicepresidente de Operaciones en Dialpad Comunicaciones que vendió a Yahoo. Antes de Dialpad, el Sr. Tribolet desempeno como Presidente de Data Products International donde superviso la construccion de salida global de servicios de telefonia por Internet.',
            LEADERSHIP_EVP_NAME: 'Carmen Tribolet, Co-Fundadora, Vicepresidente Ejecutiva',
            LEADERSHIP_EVP_DESCRIPTION: 'Carmen Tribolet, con una gran experiencia de 15 anos en la dirección de Telecomunicaciones, ha trabajado como Directora de Telecom Italia Sparkle para las Americas, siendo responsable de supervisar la venta y comercialización de Data/IP International, logrando exitosamente incrementar y triplicar las ganancias a niveles mundiales como America Latina, Europa y Asia.   Telecom Italia es una de las mayores compañias de Telecomunicación del mundo; llegando a tener ganancias de hasta $31 Billones de dólares anuales. Anteriormente a TIS, Carmen tuvo varias posiciones de liderazco en IDT Telecom donde jugo un roll muy importante sobre los objetivos e iniciativas  de gastos y ahorros comerciales. IDT Telecom tiene ganancias anuales de $1.6 billones y son los líderes en la implementación y venta de tarjetas de llamadas pre-pagadas en los Estados Unidos.  Carmen, ademas de ser una excelente professional, es madre de 3 hijos y junto a ellos y esposo disfruta de viajar; ama los deportes y como hobby practica la fotografía. También ayuda y participa en actos culturales, obras de arte y filmografía en el estado de la Florida.',
            LEADERSHIP_CLO_NAME: 'Chuck Gaspari, Co-Fundador, Director Legal',
            LEADERSHIP_CLO_DESCRIPTION: 'Chuck Gaspari tiene una gran experiencia en las operaciones de negocio estratégico, emisión de capital y las relaciones estratégicas, que abarca el desarrollo de inicio, mercadeo, ventas, fusiones y adquisiciones, y las políticas corporativas y prácticas. Fundó G&G Sports and Entertainment Group, Inc., y ha trabajado con Motorola, Comcast y equipos y clientes en la NBA, NHL, PGA, LPGA y la Major League Baseball. Gaspari también sirvió como asistente personal de la Casa Blanca para vicepresidente George H.W. Bush y como asistente legal judicial por un magistrado federal para el Distrito Sur de Florida.',
            LEADERSHIP_CFO_NAME: 'Mark Holodnak, Director de Finanzas',
            LEADERSHIP_CFO_DESCRIPTION: 'Mark Holodnak ha tenido una extensa carrera que abarca desde IBM, GE Capital, Tetra Pak, Inter-Tel y mas notablemente como la fundacion de VP Finanzas/Controller para Vonage. En Vonage jugo un papel decisivo en la creacion del departamento de Finanzas y los sistemas y procesos que se convirtieron en la base para su crecimiento exponencial y la eventual salida a bolsa de ejecucion. Su historial de logros incluye el establecimiento de una operacion de financiacion de clase mundial incluyendo informacion financiera, gestion de efectivo, tesoreria, gestion de riesgos, presupuestos y previsiones, negociacion de contratos y gestion de inventario. Desde Vonage ha asesorado a diversas empresas en las adquisiciones, due diligence y la implementacion de sistemas. En esta capacidad, el ha ayudado a los compradores y vendedores y tiene experiencia trabajando con empresas de capital privado y los bancos de inversion. Mas recientemente, gestiono una empresa de comunicacion diversificada por dos anos en cual gestiono valoracion de inversiones, la equidad y la venta eventual de la empresa. El tiene un MBA de la Universidad Rider de Lawrenceville NJ ha vivido en la ciudad de Nueva York durante muchos anos y ahora reside en Phoenix, AZ con su familia.',
            LEADERSHIP_CIO_NAME: 'Giancarlo Paolillo, Director de Informacion',
            LEADERSHIP_CIO_DESCRIPTION: 'Giancarlo Paolillo ha ocupado cargos que van desde CIO de ACN, director de tecnologia de X Plus One, y Jefe de Tecnologias Emergentes de Household International (ahora HSBC), donde fue responsable del diseno y el apoyo de mas de 30 millones de clientes de tarjetas de credito dentro de su E-commerce soluciones en la UE y EE.UU. Ademas Giancarlo era el vicepresidente senior de Ingenieria de Vonage donde escalo las soluciones de desarrollo de software y infraestructura de 6 puntos de presencia a 36 en menos de dos anos con los clientes de menos de 100 mil a mas de 2 millones. Sus responsabilidades y experiencia abarcan la infraestructura de red, ingenieria de sistemas, planificacion de capacidad, seguridad de red, infraestructura de comercio electronico, base de datos y soluciones de almacenamiento de datos, estrategias de copia de seguridad, redes de almacenamiento y NOC; construccion, remodelacion, la seguridad dentro de la infraestructura y software de ingenieria de cada organizacion que trata con la red, sistemas y aplicaciones y ha creado equipos de seguridad entrenados por el. Durante el transcurso de su carrera, Giancarlo ha construido centros de datos; tierra de equipos de seguridad; sitios de recuperacion de desastres; empresas migraron para satisfacer el cumplimiento de SOX/AS5; Soluciones de almacenamiento de gestion de vida; arquitecturas de software a escala; al tiempo que reduce la complejidad general y aumentando nuestra ROI.',
            LEADERSHIP_VPE_NAME: 'Tomasz Sarnowski, VP Ingenieria',
            LEADERSHIP_VPE_DESCRIPTION: 'Tomasz aporta mas de 14 anos de experiencia en el diseno, construccion, y la solucion de problemas de sistemas de telecomunicaciones a gran escala y las aplicaciones moviles. Su experiencia especifica en proveedor de software y hardware de implementacion e integracion, inteligencia de negocios, control de calidad y atencion al cliente dentro de la industria de las telecomunicaciones. Tiene una amplia experiencia en VoIP, movil y sistemas PSTN (Public Switched Telephone Network). Antes de unirse a YipTV, Tomasz fue uno de los primeros empleados de Vonage, se elevo al nivel de Ingeniero Superior y tambien fue el ingeniero principal como parte de la filial de Vonage Mobile originales (Novega). Despues de Vonage, Tomasz desempeno como Arquitecto Senior en Telcordia Technologies, Inc. (Iconectiv) en la que ofrecio soluciones tecnicas y posiciones de liderazgo en poder de varios productos de telecomunicaciones tales como Mobile ID y Resolver. En su tiempo libre, fundo Message Sprout, un SMS basado en web, de voz y sistema de mensajes de correo electronico para pequenas y medianas empresas. Tomasz ha sido emitio un patente titulado "Method and Apparatus for Telecommunication Session Authentication Using DTMF Signaling."',
            LEADERSHIP_VPCA_NAME: 'Victor Iasprizza, Director de Adquisicion de Contenidos',
            LEADERSHIP_VPCA_DESCRIPTION: 'Victor Iasprizza lleva mas de 15 anos en ventas de telecomunicaciones y la experiencia de gestion, tanto en Amarica Latina y Europa, donde fue responsable del crecimiento de negocio de voz mayorista y minorista internacional de Latinode. Sus responsabilidades incluyen P&L de rendicion de cuentas , la expansion de las regiones LATAM y EMEA, junto con el desarrollo de los mercados emergentes. El liderazgo de Victor llevo al crecimiento de exito del 35% con mas de $180 millones de ingresos anuales y incluye notable reconocimiento como empresaria hispana de mayor crecimiento en 2004, 2005 y 2006.',
            LEADERSHIP_VPBD_NAME: 'Sekar Desamangalam, Vicepresidente de Desarollo de Negocio',
            LEADERSHIP_VPBD_DESCRIPTION: 'Sekar Desamangalam recientemente se desempeno como Director de Virtus Global Partners, donde trabajo en iniciativas transfronterizas entre Estados Unidos y la India - M & A, JV y Alliances. Aporta mas de 20 anos de experiencia en ingenieria y tecnologia de la industria. Antes de Virtus Global, Sekar fue responsable de el desarrollo de productos CPE y Desarrollo Corporativo de Negocios de Vonage. En esta capacidad, tambien trabajo en nuevas iniciativas de acceso al mercado, incluyendo una Estrategia de la entrada para Vonage en India. La experiencia pasada de Sekar tambien incluye periodos en General Electric y Bechtel Power Corporation que trabajan en proyectos de alcance mundial que se extendio por el Reino Unido, China y Europa, ademas del mercado de Amarica del Norte. Sekar tiene un MBA de la Universidad de Nueva York, Stern School of Business, una maestria de la Universidad de South Florida, Tampa y BE del Instituto Birla de Tecnologia y Ciencia, Pilani, India.',
            LEADERSHIP_DIRECTORS_TITLE: 'Nuestra Junta Directiva',
            LEADERSHIP_BA1_NAME: 'Michael Snyder, Asesor de Junta Directiva',
            LEADERSHIP_BA1_DESCRIPTION: 'Michael Snyder , ha sido consultor de Fusiones y Adquisiciones en Patient Portal Technologies, Inc. desde Mayo de 2008. Mike se desempeno como Director General de Red Hawk Fire & Security, LLC. Desde el ano 2007, Michael tambien ha sido consultor en varias empresas. Era un ejecutivo Operando a AUA Private Equity Partners, LLC. Sr. Snyder fue responsable de Servicios comerciales y inversiones del sector. Mike Snyder se desempeno como Consejero Delegado a Vonage Holdings Corp. desde 8 de Febrero 2006 a 11 de Abril 2007, y tambien se desempeno como director de la firma de Marzo 2006 a Abril 2007. Michael se desempeno como Director Ejecutivo de Vonage Red de Nueva Jersey Inc. (anteriormente, Vonage Network Inc.) y Vonage Network LLC . Desde Febrero de 2006, se desempeno como Consejero Delegado en Sungjee Construction Co. , Ltd. Tiene mas de 30 anos de experiencia en la industria. Desde 1997 a Febrero de 2006, se desempeno como Presidente y Director de Operaciones de ADT Security Services, Inc , America del Norte. Mike se unio a ADT en 1977 y sirvio en varias posiciones antes de 1997. Ha sido Presidente Ejecutivo de Castlerock Seguridad Holdings, Inc. desde Septiembre de 2010. Mike se desempena como Director de Seguridad Castlerock Holdings, Inc. Se desempena como Director de CitraPAc . Tambien se desempena como miembro de la Junta Asesora en Proximex, Paciente Portal Technologies, Inc., y Seguro de canales de TV, Inc. Se desempena como miembro del consejo para el Consejo Nacional de Prevencion del Delito. Sr. Snyder sirvio como Director de Sungjee Construction Co., Ltd., desde Marzo de 2006. Mike sirvio como Director de Talon International, Inc. a partir de Julio de 2010 y el 9 de Abril de 2012. Se desempeno como Director del Patient Portal Technologies, Inc. desde Mayo de 2008. El Sr. Snyder tiene un BA de la Universidad Estatal de Nueva York en Oswego, Nueva York.Technologies, Inc., and Safe & Secure TV Channel, Inc.',
            LEADERSHIP_BA2_NAME: 'Peter Foyo, Assesor de Junta Directiva',
            LEADERSHIP_BA2_DESCRIPTION: 'Peter Foyo se desempeno como CEO y Presidente de Nextel de Mexico S.A., C.V., desde 1998 hasta Diciembre de 2013. Durante su mandato, Sr. Foyo era responsable del funcionamiento completo de las operaciones de la compania. Ademas, Sr. Foyo ha ocupado diversos cargos de alta direccion dentro de AT&T Corporation, responsable de la gestion y las operaciones de la compania en diversos paises de America Latina. Peter tambien fue miembro de la junta de directores de la Compania de Telefonos del Interior y tambien Director Corporativo de Estrategia de Alestra, S.A., C.V., una empresa conjunta entre AT&T y un socio local Mexicano; y presidente de AT&T Argentina. Peter actualmente se encuentra en una serie de juntas directivas internacionales y nacionales, incluyendo: Marquette Empresas; Abraaj Group (Emiratos Arabes Unidos); World Fund (Mexico); y Sirran Communications, entre otros. La experiencia de Peter en la expansion y el desarrollo de los negocios internacionales y nacionales ha sido ampliamente reconocida. El es muy apasionado sobre el proposito de negocio de estas organizaciones y los resultados de su participacion. Durante este ultimo ano ha desarrollado una Plaza de Cuidado urgente en Mexico que presta atencion sanitaria a los necesitados; tambien ha impulsado los ingresos de mas de $3.6mm para una empresa de seguridad que ha estado en accion menos de un ano. Foyo estudio Negocios Internacionales, Economia, Ciencia Militar y Ingenieria en la Universidad Benedictina y Wheaton College en Illinois',
            LEADERSHIP_BA3_NAME: 'Brian Mass, Asesor de Junta Directiva',
            LEADERSHIP_BA3_DESCRIPTION: 'Brian Mass ha estado involucrado en la industria de la tecnologia de informacion bancaria y de inversion por mas de quince anos. Brian fue un director en Citigroup\'s Global Technology Investment Banking Group con especializad en la prestacion de las finanzas corporativas y servicios de asesoramiento para los servicios globales de IT y empresas de infraestructura. Durante su mandato con Citigroup ejecuto mas de $70 mil millones en transacciones incluyendo $6.5mm en financiamientos y $ 10mm en adquisiciones de IBM, la venta de EDS a HP por $14mm, la venta de ACS a Xerox por $8mm, $1.5mm en financiamientos mas la adquisicion de Headstrong para Genpact por $550 millones, y varios otros de financiacion y asesoramiento compromisos para empresas como Accenture, Servicio EXL, Hewitt, Interxion, SAIC, SRA, TeleTech, Unisys, West y Wipro. Antes de Citigroup, Brian fue un analista de Rho Ventures, una firma de capital de riesgo con mas de $2mm bajo gestion. Brian recibio una licenciatura en Economia de Northwestern University y es registrado con FINRA Serie 7 (General de Valores Representante) y Serie 63 (agente Uniforme de Valores).',
            LEADERSHIP_BA4_NAME: 'Judith Aidoo, Asesor de Junta Directiva',
            LEADERSHIP_BA4_DESCRIPTION: 'Judith Aidoo es una inversora privada (Caswell Capital Partners, LLC) y empresaria en los medios de comunicacion y entretenimiento (Caswell Communications, Inc.) con participaciones en la radiodifusion; sindicacion de television; editorial; y de cine y produccion teatral. Judith comenzo su carrera como banquera de inversion en 1987 con Goldman, Sachs & Co., donde se especializo en finanzas estructuradas. Al salir de Goldman en 1991, comenzo su propia firma para asesorar y invertir en tecnologia; las telecomunicaciones y los medios de comunicacion; y servicios financieros. Ha co-gestionado un fondo de cobertura con mas de $200 millones en activos de transmision y de entretenimiento. Sra Aidoo ha sido premiado por sus logros empresariales y la filantropia como un miembro de la junta de las siguientes instituciones: co-presidente de la clase de la Escuela de Derecho de Harvard de 1987 20a Reunion del Comite; WNYC, el grupo de estaciones de radio publico de Nueva York presidida en ese momento por la senora Billie Tisch; Equipo de Transicion del Presidente Clinton, responsable por cubrir el sistema de la Reserva Federal de los EE.UU., y como miembro de su Comite Asesor de Comercio de Estados Unidos presidido por el representante de Comercio de Estados Unidos en ese momento, Sra. Charlene Barshefsky; el Comite de Desarrollo de Negocios de EEUU-Sur Africa co-presidido por los secretarios de Comercio Brown y Daley; el distrito electoral para Africa; y la clase 2001 de Henry Crown Fellows en el Instituto Aspen que hace hincapie en el liderazgo en el negocio basado en valores. Mas recientemente, Judith fue nominada por sus companeros en el Consejo de la Bolsa de Valores de Ghana hasta el 2004. La Sra Aidoo tambien es miembra fundadora del Fondo de Desarrollo de las Mujeres Africanas; el Decano de la Facultad de Artes y Ciencias de la Junta Consultiva de la Universidad de Rutgers; y una inversora y consejera delegada de Capital Alliance Co., un banco de negocios con encanto; Caswell Communications, Inc., el operador de WPAL-FM, y uno de los propietarios de tiempo y titulares conjuntos de WZJY 1480 AM, tanto en Charleston, Carolina del Sur. Judith se graduo Phi Beta Kappa y con altos honores de la universidad de Rutgers en 1984 y de la Escuela de Derecho de Harvard en 1987. Ha sido colaborador de television para MSNBC y CNN, y se ha perfilado y citado en las principales publicaciones de negocios en materia de inversion, incluyendo el Wall Street Journal, Forbes, el Financial Times y Black Enterprise.',
            LEADERSHIP_BA5_NAME: 'Ed Rodriguez, Asesor de Junta Directiva',
            LEADERSHIP_BA5_DESCRIPTION: 'Ed Rodriguez tiene mas de 14 anos de experiencia de ventas de alta tecnologia, gestion de productos y experiencia de servicios de consultoria. Actualmente dirige Citrix Systems (CTXS) dentro de la division de ventas para Norteamerica y Sudamerica, abarcando sus segmentos de pequenas empresas y del mercado medio, ademas de su Subscription y Hardware Maintenance Renewals equipos que excede $500M en ingresos anuales. En los papeles previos de Citrix , Ed ayudo a allanar el camino para nuevos productos que llevan las versiones de desarrollo de productos, la participacion en las reuniones del Consejo y de los equipos de ventas de construccion se centraron en los mercados emergentes y los canales verticales. Es licenciado en Ciencias de Computacion y comenzo su carrera en una organizacion de consultoria boutique, antes de incorporarse a Citrix y el gasto de 5 anos de consultoria con empresas de Fortune 1000 sobre las iniciativas de virtualizacion y movilidad.',
            LEADERSHIP_BA6_NAME: 'Dan Lovatt, Asesor de Junta Directiva',
            LEADERSHIP_BA6_DESCRIPTION: 'Dan Lovatt tiene mas de 30 anos de experiencia en telecomunicaciones multinacional y telecomunicaciones de fabricacion en los Estados Unidos como a nivel Internacional. Mas recientemente, Dan se desempeno como Director Ejecutivo de PCCW Global, donde fue responsable de la gestion internacional de negocios de la compania fuera de su mercado nacional de China. Antes de PCCW, trabajo como director financiero internacional para Lucent Technologies, asi como un numero de socios de servicios, proveedores de contenidos, las autoridades de telecomunicaciones y agencias gubernamentales, donde ocupo diversos puestos de direccion.',
            LEADERSHIP_BA7_NAME: 'Bryan Buckley, Asesor de Junta Directiva',
            LEADERSHIP_BA7_DESCRIPTION: 'Bryan Buckley, director nominado a los Oscar, ha sido nombrado \'El rey del Super Bowl\' por el New York Times. Ha dirigido más de 50 comerciales para el gran juego desde el año 2000. Muchas de las piezas de Buckley han sido incluidas en la colección permanente del Museo de Arte Moderno, y ha sido galardonado con los premios DGA, Emmy y más de 50 Cannes Lions. En 2010, una encuesta de los lectores de Adweek nombró a Buckley el Director de Comerciales de la década y fue igualmente nombrado entre las 50 mejores Mentes Creativas de los últimos 25 años por Creativity Magazine. La carrera de Buckley como director comenzó en 1994 cuando dirigió \'This is SportsCenter\', campaña publicitaria ganadora del premio Emmy. En 1997, Buckley cofundó Hungry Man junto al creador de \'This is SportsCenter\', Hank Perlman. En 2004, la compañía ganó la Palma de Oro del Festival de Cannes a la mejor compañía de producción de comerciales del mundo y ha quedado entre las diez mejores por más de diez años consecutivos, siendo la primera en lograrlo. Buckley escribió y dirigió el cortometraje \'ASAD\'. La película fue filmada en África con un elenco compuesto, en su totalidad, de refugiados de Somalia, y fue presentada en más de 50 festivales de cine a nivel mundial, alcanzando grandes honores en el TriBeCa Film Festival, Austin Film Festival, Florida Film Festival y el Traverse City Film Festival de Michael Moore, por solo nombrar algunos. En 2013, Buckley fue nominado a un premio de la Academia por \'ASAD\'. El primer largometraje de Buckley, \'The Bronze\', abrió el Sundance Film Festival en 2015. La película la protagoniza Melissa Rauch, actriz de \'The Big Bang Theory\', quien interpreta a una vulgar exgimnasta, medallista de bronce, que tiene que luchar por su estatus de celebridad local cuando surge una nueva estrella deportiva en el pueblo. En 2015 Buckley dirigirá \'Men Are from Mars, Women Are from Venus\', protagonizada por Reese Witherspoon. La película será una adaptación del libro del Dr. John Gray, que ha sido el libro con más copias vendidas del género de no ficción aparte de la Biblia y el Corán. ',
            MAIN_ERROR_APP_CONFIG: 'Error frente configuracion de la aplicacion',
            MAIN_ERROR_AIO_SSO: 'Error con el portal de video',
            MAIN_FREE_PREVIEW_ENDED: 'Su preestreno gratis ha concluido',
            MAIN_SIGN_OUT_CONFIRMATION: 'Seguro que deseas salir de YipTV?',
            MAIN_VIDEO_PORTAL_ALREADY_OPEN: 'Portal de Video ya esta abierto en otra pestana',
            MAIN_LANGUAGE_CHANGE_SAVE_CHECK: 'Desea cambiar su idioma preferido a',
            MAIN_LANGUAGE_CHANGE_SAVE_SUCCESS: 'Preferencia de idioma guardado con exito',
            MAIN_LANGUAGE_CHANGE_SAVE_ERROR: 'Error al cambiar su preferencia de idioma. Por favor pongase en contacto con servicio al cliente',
            NOT_FOUND_HEADING: 'Pagina no disponible',
            NOT_FOUND_MESSAGE: 'La pagina que usted busca no existe',
            PREFERENCES_HEADING: 'Preferencias',
            PREFERENCES_PREFERRED_LANGUAGE: 'Elige su idioma preferido',
            PREFERENCES_PREFERRED_LANGUAGE_REQUIRED: 'Elige su idioma preferido',
            PREFERENCES_SUBMIT_BUTTON: 'Presentar',
            PREFERENCES_FETCH_ERROR: 'No se pudo obtener sus preferencias. Por favor pongase en contacto con servicio al cliente',
            PREFERENCES_SAVE_ERROR: 'Error al guardar sus preferencias. Por favor pongase en contacto con servicio al cliente',
            PREFERENCES_SUCCESS_HEADING: 'Preferencias guardada',
            PREFERENCES_SUCCESS_MESSAGE: 'Sus preferencias han sido guardada con exito.',
            PROCESSING_ORDER_HEADING: 'Registrarse',
            PROCESSING_ORDER_MESSAGE: 'Processing your order...',
            RAF_HEADING: 'Recomendar a un amigo',
            RAF_MESSAGE: 'Da a conocer YipTV a todos tus amigos y todos recibirán TV GRATIS. Por cada uno de tus amigos que se inscriban como nuevo cliente, cada uno de ustedes recibirá un mes GRATIS. ¡Invítalos a todos a inscribirse, porque esta oferta es ilimitada!',
            RAF_FINE_PRINT: '<sup>*</sup>If you (the "Referrer") refer another person (the "Referree") to YIPTV and the Referree completes a valid registration process for a subscription, the Referrer will receive a credit for one-month of their monthly service fee and the Referree will receive a credit for one-month  their monthly service fee (up to $14.99 of credit, per month) if and after the Referree has maintained a paid subscription with YipTV for sixty-one (61) consecutive days. Credit excludes additional charges, including, but not limited to, premium services or features. Cancellation by either Referrer or Referree before sixty-one (61) consecutive days from the date Referree subscribes to YipTV will result in the loss of and/or chargeback of associated credits. In the event that the Referrer or Referree has a balance due, then a credit will be applied. Credits earned have an equivalent non-cash value of one month of service, regardless of past or future subscription price changes to the service. If the customer cancels service with referral credits remaining, than those credits, if any, are forfeited. Credit has no cash value, is nonrefundable and nontransferable. Certain types of referrals, including, but not limited to, referring yourself or someone living in the same residence as you, are prohibited. Offer, prices and charges are subject to change without notice. Other terms and conditions may apply. See terms of use for more information. Void where prohibited. Offer cannot be combined and is subject to restrictions and limitations.',
            RAF_MY_EMAIL: 'Mi dirección de correo electrónico',
            RAF_EMAIL_REQUIRED: 'Ingrese su Email',
            RAF_EMAIL_INVALID: 'Ingrese un Email valido',
            RAF_IMPORT_CONTACT_LIST: 'Importar mi lista de contactos',
            RAF_LOADING: 'Cargando...',
            RAF_OR: 'o',
            RAF_ENTER_FRIENDS_EMAIL: 'Ingresar las direcciones de correo electrónico de mis amigos separadas por comas',
            RAF_SEND_INVITE: 'Enviar invitación',
            RAF_EMAIL_SEND_ERROR: 'Error al enviar invitacion de YipTV a sus amigos',
            RAF_EMAIL_LIST_REQUIRED: 'Ingrese por lo menos una direccion de correo electronico',
            RAF_EMAIL_LIST_INVALID: 'Uno o mas direcciones de correo electronico no son valida',
            RAF_SUCCESS_HEADING: 'Invitacion enviada',
            RAF_SUCCESS_MESSAGE: 'Hemos enviado una invitacion a sus amigos',
            REACTIVATE_SUBSCRIPTION_HEADING: 'Reactivar Suscripcion',
            REACTIVATE_SUBSCRIPTION_MESSAGE: 'Su tarjeta de credito sera cargada $14.99 cada mes. Usted puede cancelar su suscripcion en cualquier momento yendo a Cuenta > Cancelar Suscripcion',
            REACTIVATE_SUBSCRIPTION_BILLING_INFO: 'Introduzca sus datos de su tarjeta de credito. Si necesita ayuda, llame',
            REACTIVATE_SUBSCRIPTION_CARD_NAME: 'Nombre en tarjeta de crédito',
            REACTIVATE_SUBSCRIPTION_CARD_NAME_REQUIRED: 'Ingrese nombre como aparece en su tarjeta de credito',
            REACTIVATE_SUBSCRIPTION_ADDRESS: 'Dirección de facturación',
            REACTIVATE_SUBSCRIPTION_ADDRESS_REQUIRED: 'Ingrese direccion como aparece en su tarjeta de credito',
            REACTIVATE_SUBSCRIPTION_CITY: 'Ciudad',
            REACTIVATE_SUBSCRIPTION_CITY_REQUIRED: 'Ingrese ciudad como aparece en su tarjeta de credito',
            REACTIVATE_SUBSCRIPTION_STATE: 'Estado',
            REACTIVATE_SUBSCRIPTION_STATE_REQUIRED: 'Ingrese estado como aparece en su tarjeta de credito',
            REACTIVATE_SUBSCRIPTION_STATE_LOAD_ERROR: 'Error al cargar lista de estados',
            REACTIVATE_SUBSCRIPTION_STATE_SELECT: 'Seleccione uno',
            REACTIVATE_SUBSCRIPTION_CARD_NUMBER: 'Número de tarjeta de crédito',
            REACTIVATE_SUBSCRIPTION_CARD_NUMBER_REQUIRED: 'Introduzca su numero de tarjeta de credito',
            REACTIVATE_SUBSCRIPTION_CARD_NUMBER_ERROR: 'Introduzca un numero de tarjeta de credito valido',
            REACTIVATE_SUBSCRIPTION_CVV: 'Código CVV',
            REACTIVATE_SUBSCRIPTION_CVV_REQUIRED: 'Introduzca codigo CVV',
            REACTIVATE_SUBSCRIPTION_CARD_NUMBER_CVV_ERROR: 'Introduzca codigo CVV valido',
            REACTIVATE_SUBSCRIPTION_EXPIRY_DATE: 'Fecha de expiración (MM/AAAA)',
            REACTIVATE_SUBSCRIPTION_EXPIRY_DATE_REQUIRED: 'Introduzca fecha de expiracion de su tarjeta de credito',
            REACTIVATE_SUBSCRIPTION_EXPIRY_DATE_INVALID: 'Introduzca fecha de expiracion valida',
            REACTIVATE_SUBSCRIPTION_ZIP_CODE: 'Código postal',
            REACTIVATE_SUBSCRIPTION_ZIP_CODE_REQUIRED: 'Introduzca su codigo postal',
            REACTIVATE_SUBSCRIPTION_ZIP_CODE_INVALID: 'Introduzca codigo postal valido',
            REACTIVATE_SUBSCRIPTION_CARD_NAME_INVALID: 'Introduzca nombre valido',
            REACTIVATE_SUBSCRIPTION_ADDRESS_INVALID: 'Introduzca direccion valida',
            REACTIVATE_SUBSCRIPTION_CITY_INVALID: 'Introduzca ciudad valida',
            REACTIVATE_SUBSCRIPTION_SUBMIT_BUTTON: 'Reactivar Suscripcion',
            REACTIVATE_SUBSCRIPTION_FAILED: 'Reactivar suscripcion fallo. Por favor pongase en contacto con servicio al cliente',
            REACTIVATE_SUBSCRIPTION_PROBLEM: 'Problemas al reactivar su suscripcion? Pongase en contacto con servicio al cliente',
            REACTIVATE_SUBSCRIPTION_ACCOUNT_REFRESH_ERROR: 'Por favor cierre y vuelva a abrir la ventana del navegador de la aplicacion YipTV.',
            REACTIVATE_SUBSCRIPTION_ACCESS_ERROR: 'No se puede reactivar su suscripcion o su cuenta ya esta reactivada. Por favor pongase en contacto con servicio al cliente',
            REACTIVATE_SUBSCRIPTION_ALREADY_ACTIVE: 'No se puede reactivar su suscripcion como usted ya tiene una suscripcion activa',
            REACTIVATE_SUBSCRIPTION_SUCCESS_HEADING: 'Suscripcion Reactivada',
            REACTIVATE_SUBSCRIPTION_SUCCESS_MESSAGE: 'Su suscripcion ha sido reactivada con exito',
            REACTIVATE_SUBSCRIPTION_SUCCESS_PAYMENT_PENDING_HEADING: 'Suscripcion Reactivada',
            REACTIVATE_SUBSCRIPTION_SUCCESS_PAYMENT_PENDING_MESSAGE: 'Your subscription has been re-activated but we were unable to process payment on your card. Go to Account > Change Credit Card and re-enter your credit card details',
            REDIRECT_MESSAGE: 'Redireccionamiento...',
            RESEND_VERIFICATION_HEADING: 'Reenviar correo electronico de verificacion',
            RESEND_VERIFICATION_EMAIL: 'Introduzca su email y le enviaremos un enlace para verificar',
            RESEND_VERIFICATION_EMAIL_INVALID: 'Introduzca email valido',
            RESEND_VERIFICATION_EMAIL_REQUIRED: 'Introduzca su email',
            RESEND_VERIFICATION_BUTTON: 'Presentar',
            RESEND_VERIFICATION_SUCCESS_HEADING: 'Email enviado',
            RESEND_VERIFICATION_SUCCESS_MESSAGE: 'Hemos mandado el enlace de verificacion de cuenta. Por favor revise su correo electronico.',
            RESEND_VERIFICATION_USER_ERROR: 'Cuenta no encontrada o cuenta ya activada',
            RESEND_VERIFICATION_ERROR: 'Error al enviar el enlace de verificacion de la cuenta. Por favor pongase en contacto con servico al cliente',
            RESET_PASSWORD_HEADING: 'Reestablecer Contrasena',
            RESET_PASSWORD_NEW_PASSWORD: 'Nueva Contrasena',
            RESET_PASSWORD_CONFIRM_PASSWORD_REQUIRED: 'Confirme su Contrasena',
            RESET_PASSWORD_CONFIRM_PASSWORD: 'Confirmar Contrasena',
            RESET_PASSWORD_NEW_PASSWORD_NOT_COMPLEX: 'Contrasena debe tener al menos 6 caracteres, 1 letra mayuscula y 1 numero',
            RESET_PASSWORD_NEW_PASSWORD_REQUIRED: 'Introduzca su contrasena',
            RESET_PASSWORD_CONFIRM_PASSWORD_NO_MATCH: 'Contrasenas no coinciden',
            RESET_PASSWORD_BUTTON: 'Presentar',
            RESET_PASSWORD_USER_ERROR: 'No se puede cambiar su contrasena. Por favor pongase en contacto con servico al cliente',
            RESET_PASSWORD_CODE_ERROR: 'El enlace de restablecimiento de contrasena ha expirado y ya no es valida',
            RESET_PASSWORD_SUCCESS_HEADING: 'Contrasena Cambiada',
            RESET_PASSWORD_SUCCESS_MESSAGE: 'Su contrasena ha sido cambiada con exito',
            SHOWS_TITLE_SPORTS: 'deportes internacionales',
            SHOWS_TITLE_NEWS: 'NOTICIAS DE LATINOAMÉRICA Y GLOBAL',
            SHOWS_TITLE_ENTERTAINMENT: 'Entretenimiento',
            SHOWS_SPORTS_1_TITLE: 'copa america',
            SHOWS_SPORTS_1_DESCRIPTION: 'beIN Sports | es,en',
            SHOWS_SPORTS_1_CHANNEL_DESCRIPTION: '',
            SHOWS_SPORTS_2_TITLE: 'Boxeo',
            SHOWS_SPORTS_2_DESCRIPTION: 'TYC Sports',
            SHOWS_SPORTS_2_CHANNEL_DESCRIPTION: 'Mas de 60 combates nacionales e internacionales por año',
            SHOWS_SPORTS_3_TITLE: 'score final',
            SHOWS_SPORTS_3_DESCRIPTION: 'canal 52',
            SHOWS_SPORTS_3_CHANNEL_DESCRIPTION: '',
            SHOWS_SPORTS_4_TITLE: 'Super Bike',
            SHOWS_SPORTS_4_DESCRIPTION: 'beIN Sports',
            SHOWS_SPORTS_4_CHANNEL_DESCRIPTION: 'Vealo en vivo en beIN Sports',
            SHOWS_SPORTS_5_TITLE: 'Automovilismo',
            SHOWS_SPORTS_5_DESCRIPTION: 'TYC Sports',
            SHOWS_SPORTS_5_CHANNEL_DESCRIPTION: 'TC 2000, Super TC 200 y Top Race v-6',
            SHOWS_SPORTS_6_TITLE: 'locas por el fútbol',
            SHOWS_SPORTS_6_DESCRIPTION: '52mx',
            SHOWS_SPORTS_6_CHANNEL_DESCRIPTION: '',
            SHOWS_NEWS_1_TITLE: 'tele Fórmula',
            SHOWS_NEWS_1_DESCRIPTION: 'teleFórmula',
            SHOWS_NEWS_1_CHANNEL_DESCRIPTION: 'Mantente al dia con todo actual en Mexico y en el mundo por teleFórmula',
            SHOWS_NEWS_2_TITLE: 'Conexion',
            SHOWS_NEWS_2_DESCRIPTION: 'HolaTV',
            SHOWS_NEWS_2_CHANNEL_DESCRIPTION: 'Pop Shows',
            SHOWS_NEWS_3_TITLE: 'titulares de la hora',
            SHOWS_NEWS_3_DESCRIPTION: 'NTN24',
            SHOWS_NEWS_3_CHANNEL_DESCRIPTION: '',
            SHOWS_NEWS_4_TITLE: 'NTN24 Nuestra Tele Noticias',
            SHOWS_NEWS_4_DESCRIPTION: 'NTN24',
            SHOWS_NEWS_4_CHANNEL_DESCRIPTION: 'De latinos para latinos',
            SHOWS_NEWS_5_TITLE: 'impacto economico',
            SHOWS_NEWS_5_DESCRIPTION: 'telesur',
            SHOWS_NEWS_5_CHANNEL_DESCRIPTION: '',
            SHOWS_NEWS_6_TITLE: 'Espejo Publico Prsentadores',
            SHOWS_NEWS_6_DESCRIPTION: 'Antena 3',
            SHOWS_NEWS_6_CHANNEL_DESCRIPTION: '',
            SHOWS_ENTERTAINMENT_1_TITLE: 'Seinfeld',
            SHOWS_ENTERTAINMENT_1_DESCRIPTION: 'JBN',
            SHOWS_ENTERTAINMENT_1_CHANNEL_DESCRIPTION: 'Amigos que viven en Manhattan se obsesionan con las cosas pequeñas',
            SHOWS_ENTERTAINMENT_2_TITLE: 'El hormiguero',
            SHOWS_ENTERTAINMENT_2_DESCRIPTION: 'Antenna 3',
            SHOWS_ENTERTAINMENT_2_CHANNEL_DESCRIPTION: 'Antonio Banderas',
            SHOWS_ENTERTAINMENT_3_TITLE: 'iconos',
            SHOWS_ENTERTAINMENT_3_DESCRIPTION: 'Hola TV',
            SHOWS_ENTERTAINMENT_3_CHANNEL_DESCRIPTION: 'Biografías íntimas sobre celebridades, deportistas y personajes de la realeza.',
            SHOWS_ENTERTAINMENT_4_TITLE: 'El canal de música mexicana',
            SHOWS_ENTERTAINMENT_4_DESCRIPTION: 'Video Rola',
            SHOWS_ENTERTAINMENT_4_CHANNEL_DESCRIPTION: 'Conciertos, especiales, videos, exclusivos!',
            SHOWS_ENTERTAINMENT_5_TITLE: 'The Simpsons',
            SHOWS_ENTERTAINMENT_5_DESCRIPTION: 'Antenna 3',
            SHOWS_ENTERTAINMENT_5_CHANNEL_DESCRIPTION: '',
            SHOWS_ENTERTAINMENT_6_TITLE: 'El Tiempo Entre Costuras',
            SHOWS_ENTERTAINMENT_6_DESCRIPTION: 'Antenna 3',
            SHOWS_ENTERTAINMENT_6_CHANNEL_DESCRIPTION: '',
            SIGN_IN_HEADING: 'Ingresar',
            SIGN_IN_MESSAGE: 'Bienvenido de nuevo a YipTV. Inicie sesión a bajo para ver sus programas favoritos.',
            SIGN_IN_MESSAGE_2: '¿Todavía no se ha registrado? <a style="color:#A03269" class="underline-text" href="/sign-up/paid">¡Haz clic aquí para registrarte</a> y empieza a ver ahora!',
            SIGN_IN_EMAIL: 'Dirección de correo electrónico',
            SIGN_IN_EMAIL_REQUIRED: 'Introduzca su direccion de correo electronico',
            SIGN_IN_EMAIL_INVALID: 'Introduzca una dirreccion de correo electronico valida',
            SIGN_IN_PASSWORD: 'Contraseña',
            SIGN_IN_PASSWORD_REQUIRED: 'Introduzca su contrasena',
            SIGN_IN_SUBMIT_BUTTON: 'Iniciar sesion',
            SIGN_IN_FORGOT_PASSWORD: '¿Olvidó su contraseña?',
            SIGN_IN_RESET_PASSWORD: 'Restablecer contraseña',
            SIGN_IN_NOT_REGISTERED: '¿No está registrado?',
            SIGN_IN_SIGN_UP: 'Registrarse',
            SIGN_IN_FAILED_NOT_VERIFIED: 'Ingresa fracas. Su cuenta aun no ha sido verificada.',
            SIGN_IN_FAILED: 'Ingresa fracasada',
            SIGN_IN_NO_VERIFICATION_EMAIL: '¿No recibió el mensaje de correo electrónico de verificación?',
            SIGN_IN_RESEND_VERIFICATION: 'Solicitarlo nuevamente',
            SIGN_IN_UPGRADE_SUBSCRIPTION: 'Tienes que iniciar sesion antes de poder actualizar su suscripcion.',
            SIGN_IN_REACTIVATE_SUBSCRIPTION: 'Tienes que iniciar sesion antes de poder reactivar su suscripcion.',
            SIGN_IN_CANCELED_SUBSCRIPTION_MESSAGE: 'Usted no tiene una suscripcion activa. Desea reactivar su suscripcion?',
            SIGN_IN_TRIAL_ENDED_MESSAGE: 'Su prueba gratuita ha terminado. Desea actualizar su suscripcion?',
            SIGN_IN_COMP_ENDED_MESSAGE: 'Su suscripción gratuita de YipTV ha terminado! Desea actualizar su suscripción?',
            SIGN_IN_PAYMENT_PENDING_MESSAGE: 'Su pago no pudo ser procesado, por favor actualice la informacion de su tarjeta de credito.',
            SIGN_UP_QUESTIONS: 'Preguntas? Llama a servicio al cliente a',
            SIGN_UP_MESSAGE: 'Inscribete y empiece a ver mas de 60 canales inmediato! Ve desde tu móvil, PC, TV inteligente o tablet en cualquier lugar que tenga internet. Cable, ni otros dispositivos necesarios . Comparte tu cuenta YipTV con la familia en un máximo de 5 dispositivos.',
            SIGN_UP_ORDER_SUMMARY: 'Resumen de Orden',
            SIGN_UP_ORDER: 'Orden:',
            SIGN_UP_ORDER_DETAILS: '1 mes de Yiptv - Comparte con la Familia - hasta 5 dispositivos',
            SIGN_UP_FEE: 'Cuota mensual fija:',
            SIGN_UP_FEE_DETAILS: '<span class="bolder-text">$14.99</span> (No cargos ocultos)',
            SIGN_UP_TERMS: 'Terminos:',
            SIGN_UP_TERMS_DETAILS: 'No contratos, cancela en cualquier momento.',
            SIGN_UP_FIRST_NAME: 'Nombre',
            SIGN_UP_FIRST_NAME_REQUIRED: 'Ingrese su nombre',
            SIGN_UP_LAST_NAME_REQUIRED: 'Ingrese su apellido',
            SIGN_UP_FIRST_NAME_INVALID: 'Introduzca nombre valido',
            SIGN_UP_LAST_NAME_INVALID: 'Introduzca apellido valido',
            SIGN_UP_CARD_NAME_INVALID: 'Introduzca nombre valido',
            SIGN_UP_ADDRESS_INVALID: 'Introduzca direccion valida',
            SIGN_UP_CITY_INVALID: 'Introduzca ciudad valida',
            SIGN_UP_EMAIL: 'Correo electrónico',
            SIGN_UP_TELEPHONE: 'Teléfono',
            SIGN_UP_TELEPHONE_INVALID: 'Introduzca un numero de telefono valido de EE.UU',
            SIGN_UP_TELEPHONE_REQUIRED: 'Introduzca su numero de telefono',
            SIGN_UP_LAST_NAME: 'Apellido',
            SIGN_UP_EMAIL_INVALID: 'Introduzca una dirreccion de correo electronico valida',
            SIGN_UP_EMAIL_EXISTS: 'Usted ya tiene cuenta con nosotros. Por favor ingresar.',
            SIGN_UP_EMAIL_REQUIRED: 'Introduzca su direccion de correo electronico',
            SIGN_UP_PASSWORD: 'Contraseña',
            SIGN_UP_PASSWORD_REQUIRED: 'Introduzca su contrasena',
            SIGN_UP_PASSWORD_NOT_COMPLEX: 'Contrasena debe tener al menos 6 caracteres, 1 letra mayuscula y 1 numero',
            SIGN_UP_CONFIRM_PASSWORD: 'Confirmar contraseña',
            SIGN_UP_CONFIRM_PASSWORD_REQUIRED: 'Confirme su contrasena',
            SIGN_UP_CONFIRM_PASSWORD_NO_MATCH: 'Contrasenas no coinciden',
            SIGN_UP_BILLING_INFO: 'Información De Facturación',
            SIGN_UP_ACCOUNT_INFO: 'Información de la cuenta',
            SIGN_UP_CARD_NAME: 'Nombre en la tarjeta de crédito',
            SIGN_UP_CARD_NAME_REQUIRED: 'Ingrese nombre como aparece en su tarjeta de credito',
            SIGN_UP_ADDRESS: 'Dirección de facturación',
            SIGN_UP_ADDRESS_REQUIRED: 'Ingrese direccion como aparece en su tarjeta de credito',
            SIGN_UP_CITY: 'Ciudad',
            SIGN_UP_CITY_REQUIRED: 'Ingrese ciudad como aparece en su tarjeta de credito',
            SIGN_UP_STATE: 'Estado',
            SIGN_UP_STATE_REQUIRED: 'Ingrese estado como aparece en su tarjeta de credito',
            SIGN_UP_STATE_LOAD_ERROR: 'Error al cargar lista de estados',
            SIGN_UP_STATE_SELECT: 'Seleccione uno',
            SIGN_UP_CARD_NUMBER: 'Número de tarjeta de crédito',
            SIGN_UP_CARD_NUMBER_REQUIRED: 'Introduzca su numero de tarjeta de credito',
            SIGN_UP_CARD_NUMBER_ERROR: 'Introduzca un numero de tarjeta de credito valido',
            SIGN_UP_CVV: 'Código de seguridad',
            SIGN_UP_CVV_REQUIRED: 'Introduzca codigo CVV',
            SIGN_UP_CARD_NUMBER_CVV_ERROR: 'Introduzca codigo CVV valido',
            SIGN_UP_EXPIRY_DATE: 'Fecha de vencimiento',
            SIGN_UP_EXPIRY_DATE_REQUIRED: 'Introduzca fecha de expiracion de su tarjeta de credito',
            SIGN_UP_EXPIRY_DATE_INVALID: 'Introduzca fecha de expiracion valida',
            SIGN_UP_ZIP_CODE: 'Código Postal',
            SIGN_UP_ZIP_CODE_REQUIRED: 'Introduzca su codigo postal',
            SIGN_UP_ZIP_CODE_INVALID: 'Introduzca codigo postal valido',
            SIGN_UP_TERMS_OF_USE: 'términos de uso',
            SIGN_UP_AND: 'de YipTV y',
            SIGN_UP_SUBMIT_BUTTON: 'Ingresar mi orden',
            SIGN_UP_DISCLAIMER: 'Acepto los',
            SIGN_UP_DISCLAIMER_END: '',
            SIGN_UP_DISCLAIMER_REQUIRED: 'Para utilizar los servicios YipTV usted necesita aceptar nuestras condiciones de uso y politica de privacidad',
            SIGN_UP_PRIVACY_POLICY: 'póliza de privacidad',
            SIGN_UP_USER_EXISTS: 'Esta direccion de correo electronico ya esta registrada con YipTV. Por favor, use otra direccion de correo electronico',
            SIGN_UP_FAILED: 'Error al contratar Usuario. Por favor pongase en contacto con servico al cliente',
            SIGN_UP_PROBLEM: 'Tiene problemas al inscribirse? Llame sevicio al cliente a:',
            SIGN_UP_SUCCESS_HEADING: '¡Felicitaciones!',
            SIGN_UP_SUCCESS_MESSAGE: 'Se registró satisfactoriamente en YipTV. Haga clic en el botón o el enlace en el mensaje de correo electrónico que le enviamos para verificar su cuenta.',
            SIGN_UP_FREE_SUCCESS_HEADING: 'Gracias por registrarte para obtener una cuenta gratis de YipTV  por 7 días!',
            SIGN_UP_FREE_SUCCESS_MESSAGE_1: 'Por favor revisa tu correo electrónico y haz clic en el enlace para verificar tu cuenta',
            SIGN_UP_FREE_SUCCESS_MESSAGE_2: 'Ahora tienes acceso a ver algunos de nuestros canales. Cuando te veas la calidad increíble de YipTV, actualiza a una cuenta completa por sólo $14,99 al mes y tendrás acceso instantáneo a 60 canales internacionales!',
            SIGN_UP_FREE_SUCCESS_MESSAGE_3: 'Próximos Pasos:',
            SIGN_UP_FREE_SUCCESS_MESSAGE_4: 'Asegúrese de validar tu cuenta haciendo clic en el enlace del correo electrónico que te enviamos.',
            SIGN_UP_FREE_SUCCESS_MESSAGE_5: 'Si verá de su navegador web, puede ingresar y comenzar viendo aquí:',
            SIGN_UP_FREE_SUCCESS_MESSAGE_6: 'Ingresar',
            SIGN_UP_FREE_SUCCESS_MESSAGE_7: 'Descarga nuestra aplicación móvil gratis y empieza a ver TV en vivo en tu dispositivo móvil:',
            SIGN_UP_FREE_SUCCESS_MESSAGE_8: 'Cuando estés listo para actualizar',
            SIGN_UP_FREE_SUCCESS_MESSAGE_9: 'Haz clic en el enlace "Cuenta" en la parte superior de la página de cuenta, entonces haz clic en el botón "Actualizar subscripción" y completa el formulario de inscripción con una tarjeta de crédito valida. Una vez que te conviertes en un cliente, puedes disfrutar todos los canales desde tu teléfono, tablet, con nuestra aplicación TV móvil gratis, o en tu PC o TV conectado a la Internet usando cualquier navegador',
            SIGN_UP_SUCCESS_LOGIN_HEADING: '¡Felicitaciones!',
            SIGN_UP_SUCCESS_LOGIN_MESSAGE: 'Ha registrado a YipTV con éxito. <a class="underline-text" href="/sign-in">Ingresar</a> a YipTV ahora.',
            SIGN_UP_SUCCESS_PAYMENT_PENDING_HEADING: '¡Felicitaciones!',
            SIGN_UP_SUCCESS_PAYMENT_PENDING_MESSAGE: 'Recibimos la información de su suscripcion a YipTV pero desafortunadamente no hemos podido procesar el pago.  Por favor haga click en el botón siguiente o en el enlace adjunto para que nos ayude verificando y actualizando la información de su tarjeta de crédito.',
            SIGN_UP_SUCCESS_PAYMENT_PENDING_ACTIVE_HEADING: '¡Felicitaciones!',
            SIGN_UP_SUCCESS_PAYMENT_PENDING_ACTIVE_MESSAGE: 'You have successfully signed up with YipTV but we were unable to process payment on your credit card. Please <a class="underline-text" href="/sign-in">Sign In</a> and update your credit card information.',
            UNDER_CONSTRUCTION_HEADING: 'Bajo construccion',
            UNDER_CONSTRUCTION_MESSAGE: 'La pagina que usted busca esta bajo construccion y estara disponible en breve',
            UPGRADE_SUBSCRIPTION_HEADING: 'Actualizar Suscripcion',
            UPGRADE_SUBSCRIPTION_MESSAGE: 'Usted esta actualizando su cuenta a una cuenta de pago. Su tarjeta de credito sera cargada $14.99 cada mes. Usted puede cancelar su suscripcion en cualquier momento yendo a Cuenta > Cancelar Suscripcion.',
            UPGRADE_SUBSCRIPTION_BILLING_INFO: 'Introduzca sus datos de su tarjeta de credito. Si necesita ayuda, llame',
            UPGRADE_SUBSCRIPTION_CARD_NAME: 'Nombre en tarjeta de crédito',
            UPGRADE_SUBSCRIPTION_CARD_NAME_REQUIRED: 'Ingrese nombre como aparece en su tarjeta de credito',
            UPGRADE_SUBSCRIPTION_ADDRESS: 'Dirección de facturación',
            UPGRADE_SUBSCRIPTION_ADDRESS_REQUIRED: 'Ingrese direccion como aparece en su tarjeta de credito',
            UPGRADE_SUBSCRIPTION_CITY: 'Ciudad',
            UPGRADE_SUBSCRIPTION_CITY_REQUIRED: 'Ingrese ciudad como aparece en su tarjeta de credito',
            UPGRADE_SUBSCRIPTION_STATE: 'Estado',
            UPGRADE_SUBSCRIPTION_STATE_REQUIRED: 'Ingrese estado como aparece en su tarjeta de credito',
            UPGRADE_SUBSCRIPTION_STATE_LOAD_ERROR: 'Error al cargar lista de estados',
            UPGRADE_SUBSCRIPTION_STATE_SELECT: 'Seleccione uno',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER: 'Número de tarjeta de crédito',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER_REQUIRED: 'Introduzca su numero de tarjeta de credito',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER_ERROR: 'Introduzca un numero de tarjeta de credito valido',
            UPGRADE_SUBSCRIPTION_CVV: 'Código CVV',
            UPGRADE_SUBSCRIPTION_CVV_REQUIRED: 'Introduzca codigo CVV',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER_CVV_ERROR: 'Introduzca codigo CVV valido',
            UPGRADE_SUBSCRIPTION_EXPIRY_DATE: 'Fecha de expiración (MM/AAAA)',
            UPGRADE_SUBSCRIPTION_EXPIRY_DATE_REQUIRED: 'Introduzca fecha de expiracion de su tarjeta de credito',
            UPGRADE_SUBSCRIPTION_EXPIRY_DATE_INVALID: 'Introduzca fecha de expiracion valida',
            UPGRADE_SUBSCRIPTION_ZIP_CODE: 'Código postal',
            UPGRADE_SUBSCRIPTION_ZIP_CODE_REQUIRED: 'Introduzca su codigo postal',
            UPGRADE_SUBSCRIPTION_ZIP_CODE_INVALID: 'Introduzca codigo postal valido',
            UPGRADE_SUBSCRIPTION_CARD_NAME_INVALID: 'Introduzca nombre valido',
            UPGRADE_SUBSCRIPTION_ADDRESS_INVALID: 'Introduzca direccion valida',
            UPGRADE_SUBSCRIPTION_CITY_INVALID: 'Introduzca ciudad valida',
            UPGRADE_SUBSCRIPTION_SUBMIT_BUTTON: 'Actualizar',
            UPGRADE_SUBSCRIPTION_FAILED: 'Suscripcion de actualizacion fallo. Por favor, pongase en contacto con atencion al cliente',
            UPGRADE_SUBSCRIPTION_PROBLEM: 'Problemas actualizando? Pongase en contacto con atencion al cliente',
            UPGRADE_SUBSCRIPTION_ACCOUNT_REFRESH_ERROR: 'Por favor cierre y vuelva a abrir la ventana del navegador de la aplicacion YipTV.',
            UPGRADE_SUBSCRIPTION_ALREADY_UPGRADED: 'No se puede actualizar la suscripcion porque uste lla es un usuario pagado.',
            UPGRADE_SUBSCRIPTION_COMP_ACTIVE_USER: 'No se puede actualizar su suscripción porque usted tiene una suscripción gratuita.',
            UPGRADE_SUBSCRIPTION_SUCCESS_HEADING: 'Cuenta actualizada',
            UPGRADE_SUBSCRIPTION_SUCCESS_MESSAGE: 'Felicidades! Usted ha sido actualizado a un usuario pagado.',
            UPGRADE_SUBSCRIPTION_SUCCESS_PAYMENT_PENDING_HEADING: 'Cuenta actualizada',
            UPGRADE_SUBSCRIPTION_SUCCESS_PAYMENT_PENDING_MESSAGE: 'Congrats! You have been upgraded to a paid user but we were unable to process payment on your card. Go to Account > Change Credit Card and re-enter your credit card details',
            USER_HOME_WATCH_NOW: 'Mirar ahora',
            USER_HOME_UPGRADE_SUBSCRIPTION: 'Actualizar suscripcion',
            USER_HOME_REACTIVATE_SUBSCRIPTION: 'Reactivar suscripcion',
            USER_HOME_ACCOUNT: 'Cuenta',
            USER_HOME_REFER_FRIEND: 'Recomendar a un amigo',
            USER_HOME_CONTACT_US: 'Contáctenos',
            VERIFY_USER_HEADING_SUCCESS: 'Cuenta verificada',
            VERIFY_USER_HEADING_ERROR: 'Error',
            VERIFY_USER_MESSAGE_SUCCESS: 'Su cuenta se ha verificado satisfactoriamente. Haga clic en el botón Ingresar arriba para ingresar a YipTV.',
            VERIFY_USER_MESSAGE_ERROR: 'No se puede verificar su cuenta o su cuenta ya ha sido verificada. Comuníquese con el servicio al cliente al',
        });
    }]);
}(angular.module('app')));
