'use strict';

var path = require('path'),
    rootPath = path.normalize(__dirname + '/../../..');

module.exports = {
    root: rootPath,
    factProviders: {},
    postProcessors: {},
    appName: 'YipTV',
    paidBasicPackageAmount: '14.99',
    customerCareNumber: '855-919-4788',
    contactUsEmailSubject: 'YipTV Contact Request Received',
    contactUsEmailBody: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Thank you for contacting YipTV. We are committed to your satisfaction. A summary of your request is below. Please allow us 1 business day to review your concern and provide you with superior customer service.</p> <p>&nbsp;</p> <p>Thank you.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="font-weight: bold">Name:</td> <td>{1}</td> </tr> <tr> <td style="font-weight: bold">Email:</td> <td>{2}</td> </tr> <tr> <td style="font-weight: bold">Telephone:&nbsp;</td> <td>{3}</td> </tr> <tr> <td style="font-weight: bold">Country:</td> <td>{4}</td> </tr> <tr> <td style="font-weight: bold">Interest:</td> <td>{5}</td> </tr> <tr> <td valign="top" style="font-weight: bold;vertical-align: text-top">Details:</td> <td>{6}</td> </tr> </table> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
    accountVerificationEmailSubject: {
        en: 'Welcome to YipTV',
        es: 'Welcome to YipTV'
    },
    accountVerificationEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Congratulations!</p><br/> <p>You are just one step away from becoming a Member of YipTV. To get started watching TV on mobiles and more, just click the "Verify Account" button below or copy and paste the link into your browser.</p> <p>Please be sure to add our email address to your contacts so you never miss an important message from YipTV.</p> <p>If you are having any difficulty verifying your account, please contact Customer Support at <a href="mailto:support@yiptv.com">support@yiptv.com</a> or at {1}.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{2}">Verify Account</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{2}">{2}</a></p><br/> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Congratulations!</p><br/> <p>You are just one step away from becoming a Member of YipTV. To get started watching TV on mobiles and more, just click the "Verify Account" button below or copy and paste the link into your browser.</p> <p>Please be sure to add our email address to your contacts so you never miss an important message from YipTV.</p> <p>If you are having any difficulty verifying your account, please contact Customer Support at <a href="mailto:support@yiptv.com">support@yiptv.com</a> or at {1}.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{2}">Verify Account</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{2}">{2}</a></p><br/> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    forgotPasswordEmailSubject: {
        en: 'YipTV Password Reset',
        es: 'YipTV Password Reset'
    },
    forgotPasswordEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>We received a request to reset the password associated with your YipTV membership. If you made this request, click the button below. If you did not make this request you can ignore this email.</p> <p>If you are having any difficulty accessing your account, please contact Customer Support at <a href="mailto:support@yiptv.com">support@yiptv.com</a> or at {3}.</p> <p>&nbsp;</p> <p>Thank you.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{4}">Reset Password</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{4}">{4}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>We received a request to reset the password associated with your YipTV membership. If you made this request, click the button below. If you did not make this request you can ignore this email.</p> <p>If you are having any difficulty accessing your account, please contact Customer Support at <a href="mailto:support@yiptv.com">support@yiptv.com</a> or at {3}.</p> <p>&nbsp;</p> <p>Thank you.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{4}">Reset Password</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{4}">{4}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    passwordChangedEmailSubject: {
        en: 'YipTV Password Changed',
        es: 'YipTV Password Changed'
    },
    passwordChangedEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>You recently changed the password associated with your YipTV membership. If you did not make this change, please contact Customer Support at <a href="mailto:support@yiptv.com">support@yiptv.com</a> or at {3}.</p> <p>&nbsp;</p> <p>Thank you.</p> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>You recently changed the password associated with your YipTV membership. If you did not make this change, please contact Customer Support at <a href="mailto:support@yiptv.com">support@yiptv.com</a> or at {3}.</p> <p>&nbsp;</p> <p>Thank you.</p> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    referAFriendEmailSubject: 'You gotta try YipTV for FREE!',
    referAFriendEmailBody: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Friend,</p><br/> <p>I just got a FREE YipTV Membership without providing a credit card! I’m watching LIVE, sports and entertainment from Latin America and around the world for FREE! This is high-quality, FREE Internet television service that works on Internet-connect TVs and mobiles! You gotta try this!</p> <p>The FREE Membership lets me watch 17 international channels unlimited, and for my first 7 days, I’m getting 9 bonus channels, including beIN SPORTS and ¡Hola! TV! I can watch at home or on the go with the YipTV FREE app.</p> <p>Once you’ve joined, be sure to click the Refer A Friend link so you can invite others to join. Premium Membership is only $14.99/mo with NO contract. Become a Premium Member and when your friends become one too, you <span style="text-decoration:underline">BOTH</span> get a <span style="text-decoration:underline">FREE</span> month of Premium Membership! </p> <p>See our terms and conditions at <a href="http://www.yiptv.com">yiptv.com</a> for more information.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td bgcolor="#A03269" style="border-radius:5px;padding:10px;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{1}">Join YipTV</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{1}">{1}</a></p><br/> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
    reminderEmailSubject: {
        en: 'Your YipTV free trial ends in {0} days!',
        es: '¡Su prueba gratuita de YipTV finaliza en {0} días!'
    },
    reminderEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>We sincerely hope that you have been enjoying YipTV\'s premium channels for the last {3} days. We would like to take this opportunity to thank you again for signing up with us. </p> <p>Pay a flat $14.99/mo and become a YipTV paid subscriber today to watch all YipTV channels! Click the button below to upgrade now!</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{4}">Upgrade</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{4}">{4}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>Sinceramente esperamos que haya disfrutado de los canales premium de YipTV en los últimos {3} días. Nos gustaría aprovechar esta oportunidad para agradecerle nuevamente por haberse registrado con nosotros.</p> <p>Pague una tarifa fija de $14.99/mes y conviértase en un abonado de YipTV hoy mismo para poder disfrutar de todos los canales de YipTV. Haga clic en el botón debajo para actualizar su servicio ahora mismo.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{4}">Actualizar</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>O haga clic en el siguiente enlace:</p> <p><a href="{4}">{4}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> No responda este mensaje; se envió desde una dirección de correo electrónico no supervisada. Este es un mensaje de correo electrónico de servicio relacionado con su uso de YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    lastButOneReminderEmailSubject: {
        en: 'Your YipTV free trial ends in 1 day!',
        es: '¡Su prueba gratuita de YipTV finaliza en un día!'
    },
    lastButOneReminderEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>We sincerely hope that you have been enjoying YipTV\'s premium channels for the last 6 days. We would like to take this opportunity to thank you again for signing up with us. </p> <p>Pay a flat $14.99/mo and become a YipTV paid subscriber today to watch all YipTV channels! Click the button below to upgrade now!</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{3}">Upgrade</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{3}">{3}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>Sinceramente esperamos que haya disfrutado de los canales premium de YipTV en los últimos 6 días. Nos gustaría aprovechar esta oportunidad para agradecerle nuevamente por haberse registrado con nosotros.</p> <p>Pague una tarifa fija de $14.99/mes y conviértase en un abonado de YipTV hoy mismo para poder disfrutar de todos los canales de YipTV. Haga clic en el botón debajo para actualizar su servicio ahora mismo.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{3}">Actualizar</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>O haga clic en el siguiente enlace:</p> <p><a href="{3}">{3}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> No responda este mensaje; se envió desde una dirección de correo electrónico no supervisada. Este es un mensaje de correo electrónico de servicio relacionado con su uso de YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    lastReminderEmailSubject: {
        en: 'Your YipTV free trial ends today!',
        es: '¡Su prueba gratuita de YipTV finaliza hoy!'
    },
    lastReminderEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>We sincerely hope that you have been enjoying YipTV\'s premium channels for the last 7 days. We would like to take this opportunity to thank you again for signing up with us. </p> <p>Pay a flat $14.99/mo and become a YipTV paid subscriber today to watch all YipTV channels! Click the button below to upgrade now!</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{3}">Upgrade</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{3}">{3}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>Sinceramente esperamos que haya disfrutado de los canales premium de YipTV en los últimos 7 días. Nos gustaría aprovechar esta oportunidad para agradecerle nuevamente por haberse registrado con nosotros.</p> <p>Pague una tarifa fija de $14.99/mes y conviértase en un abonado de YipTV hoy mismo para poder disfrutar de todos los canales de YipTV. Haga clic en el botón debajo para actualizar su servicio ahora mismo.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{3}">Actualizar</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>O haga clic en el siguiente enlace:</p> <p><a href="{3}">{3}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> No responda este mensaje; se envió desde una dirección de correo electrónico no supervisada. Este es un mensaje de correo electrónico de servicio relacionado con su uso de YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    trialPeriodCompleteEmailSubject: {
        en: 'Your YipTV free trial has ended!',
        es: '¡Su prueba gratuita de YipTV ha finalizado!'
    },
    trialPeriodCompleteEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>Your YipTV free trial has ended! You can watch all YipTV channels for $14.99/mo. Click button below to upgrade now!</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{3}">Upgrade</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{3}">{3}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>Su prueba gratuita de YipTV ha finalizado. Puede ver todos los canales de YipTV por $14.99/mes. Haga clic en el botón debajo para actualizar su servicio ahora mismo.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{3}">Actualizar</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>O haga clic en el siguiente enlace:</p> <p><a href="{3}">{3}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> No responda este mensaje; se envió desde una dirección de correo electrónico no supervisada. Este es un mensaje de correo electrónico de servicio relacionado con su uso de YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    reacquireUserEmailSubject: {
        en: 'We miss you at YipTV!',
        es: '¡Lo extrañamos en YipTV!'
    },
    reacquireUserEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br/> <p>Your YipTV free trial ended yesterday and we miss you already! You can upgrade to a paid account by paying $14.99/mo and watch all YipTV channels. Click button below to upgrade now! </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{3}">Upgrade</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{3}">{3}</a></p><br/> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br/> <p>¡Su prueba gratuita de YipTV finalizó ayer y ya lo extrañamos! Puede actualizar su servicio a una cuenta de prepago abonando $14.99/mes y disfrutar de todos los canales de YipTV. Haga clic en el botón debajo para actualizar su servicio ahora mismo. </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{3}">Actualizar</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>O haga clic en el siguiente enlace:</p> <p><a href="{3}">{3}</a></p><br/> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> No responda este mensaje; se envió desde una dirección de correo electrónico no supervisada. Este es un mensaje de correo electrónico de servicio relacionado con su uso de YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    complimentaryAccountEndedEmailSubject: {
        en: 'Your YipTV complimentary subscription has ended!',
        es: 'Su suscripción gratuita de YipTV ha terminado!'
    },
    complimentaryAccountEndedEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>Your YipTV complimentary subscription has ended! To continue watching YipTV upgrade now!</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{3}">Upgrade</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{3}">{3}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>Su suscripción gratuita de YipTV ha terminado! Actualize su cuenta ahora para continuar viendo YipTV!</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{3}">Actualizar</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>O haga clic en el siguiente enlace:</p> <p><a href="{3}">{3}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> No responda este mensaje; se envió desde una dirección de correo electrónico no supervisada. Este es un mensaje de correo electrónico de servicio relacionado con su uso de YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    upgradeSubscriptionEmailSubject: {
        en: 'YipTV Subscription Activated',
        es: 'YipTV Suscripción Activado'
    },
    upgradeSubscriptionEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>Thank you for your subscription. You can login now to enjoy your service.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{3}">Sign In</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{3}">{3}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br/> <p>Gracias por su suscripción. Ya puede iniciar una sesión para disfrutar de su servicio.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{3}">Ingresar</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>O haga clic en el siguiente enlace:</p> <p><a href="{3}">{3}</a></p><br/> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> No responda este mensaje; se envió desde una dirección de correo electrónico no supervisada. Este es un mensaje de correo electrónico de servicio relacionado con su uso de YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    upgradeSubscriptionFailedEmailSubject: {
        en: 'YipTV Subscription Activated',
        es: 'YipTV Suscripción Activado'
    },
    upgradeSubscriptionFailedEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>Thank you for your subscription. You can login now to enjoy your service.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{3}">Sign In</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{3}">{3}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br/> <p>Gracias por su suscripción. Ya puede iniciar una sesión para disfrutar de su servicio.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{3}">Ingresar</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>O haga clic en el siguiente enlace:</p> <p><a href="{3}">{3}</a></p><br/> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> No responda este mensaje; se envió desde una dirección de correo electrónico no supervisada. Este es un mensaje de correo electrónico de servicio relacionado con su uso de YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    convertToComplimentaryEmailSubject: {
        en: 'YipTV Subscription Activated',
        es: 'YipTV Suscripción Activado'
    },
    convertToComplimentaryEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>Thank you for your subscription. You can login now to enjoy your service.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{3}">Sign In</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{3}">{3}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br/> <p>Gracias por su suscripción. Ya puede iniciar una sesión para disfrutar de su servicio.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{3}">Ingresar</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>O haga clic en el siguiente enlace:</p> <p><a href="{3}">{3}</a></p><br/> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> No responda este mensaje; se envió desde una dirección de correo electrónico no supervisada. Este es un mensaje de correo electrónico de servicio relacionado con su uso de YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    cancelSubscriptionEmailSubject: {
        en: 'Your YipTV Service Canceled',
        es: 'Your YipTV Service Canceled'
    },
    cancelSubscriptionEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br/> <p>We hate to see you go!</p> <p>As promised, YipTV members can cancel anytime. Your membership has been canceled and service will continue until the end of your current billing cycle ({3}). No further payments will be required.</p> <p>&nbsp;</p> <p>Thank you.</p> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br/> <p>We hate to see you go!</p> <p>As promised, YipTV members can cancel anytime. Your membership has been canceled and service will continue until the end of your current billing cycle ({3}). No further payments will be required.</p> <p>&nbsp;</p> <p>Thank you.</p> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    subscriptionCanceledEmailSubject: {
        en: 'Your YipTV Membership Deactivated',
        es: 'Your YipTV Membership Deactivated'
    },
    subscriptionCanceledEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br/> <p>We hate to see you go!</p> <p>As promised, YipTV members can cancel anytime. Your membership has been canceled and service has been discontinued. No further payments will be required.</p> <p>Remember, you will still be able to watch a limited number of live TV channels FREE with your same account. If you change your mind, you can upgrade to Premier Membership at any time.</p> <p>Please know that at anytime, you can reactivate your membership by simply logging in, go to Account > Upgrade to Premium Membership.</p> <p>Help us understand how we can best serve valuable customers like you. Please contact Customer Support at <a href="mailto:support@yiptv.com">support@yiptv.com</a> or at {3}.</p> <p>&nbsp;</p> <p>Thank you.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{4}">Upgrade to Premium Membership</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{4}">{4}</a></p><br/> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br/> <p>We hate to see you go!</p> <p>As promised, YipTV members can cancel anytime. Your membership has been canceled and service has been discontinued. No further payments will be required.</p> <p>Remember, you will still be able to watch a limited number of live TV channels FREE with your same account. If you change your mind, you can upgrade to Premier Membership at any time.</p> <p>Please know that at anytime, you can reactivate your membership by simply logging in, go to Account > Upgrade to Premium Membership.</p> <p>Help us understand how we can best serve valuable customers like you. Please contact Customer Support at <a href="mailto:support@yiptv.com">support@yiptv.com</a> or at {3}.</p> <p>&nbsp;</p> <p>Thank you.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{4}">Upgrade to Premium Membership</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{4}">{4}</a></p><br/> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    changeCreditCardEmailSubject: {
        en: 'Your YipTV Credit Card Info Updated',
        es: 'Your YipTV Credit Card Info Updated'
    },
    changeCreditCardEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br/> <p>Your credit card information has been updated. If you did not change your credit card information or if this was done in error, please contact Customer Support at <a href="mailto:support@yiptv.com">support@yiptv.com</a> or at {3}.</p> <p>&nbsp;</p> <p>Thank you.</p> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br/> <p>Your credit card information has been updated. If you did not change your credit card information or if this was done in error, please contact Customer Support at <a href="mailto:support@yiptv.com">support@yiptv.com</a> or at {3}.</p> <p>&nbsp;</p> <p>Thank you.</p> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    creditCardPaymentFailureEmailSubject: {
        en: 'Your YipTV Payment',
        es: 'Your YipTV Payment'
    },
    creditCardPaymentFailureEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br/> <p>We were unable to process your payment using the credit card information associated with your YipTV membership. To avoid interruption of service, please log in, go to Account > Upgrade to Premium Membership and update your card information.</p> <p>If you are having any difficulty, please contact Customer Support at <a href="mailto:support@yiptv.com">support@yiptv.com</a> or at {3}.</p> <p>&nbsp;</p> <p>Thank you.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{4}">Log In</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{4}">{4}</a></p><br/> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br/> <p>We were unable to process your payment using the credit card information associated with your YipTV membership. To avoid interruption of service, please log in, go to Account > Upgrade to Premium Membership and update your card information.</p> <p>If you are having any difficulty, please contact Customer Support at <a href="mailto:support@yiptv.com">support@yiptv.com</a> or at {3}.</p> <p>&nbsp;</p> <p>Thank you.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{4}">Log In</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{4}">{4}</a></p><br/> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    accountVerifiedEmailSubject: {
        en: 'YipTV Member Verification',
        es: 'YipTV Member Verification'
    },
    accountVerifiedEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Hello New YipTV Member,</p><br/> <p>You did it! You are now a member of YipTV. Start enjoying FREE TV on mobiles and more as much as you like. Don’t wait to log in because for the next 7 days, you have access to 9 awesome bonus channels as our gift to you!</p> <p>Thank you for joining YipTV. We hope you enjoy your FREE TV!</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{1}">Log In</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{1}">{1}</a></p><br/> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png"/></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Hello New YipTV Member,</p><br/> <p>You did it! You are now a member of YipTV. Start enjoying FREE TV on mobiles and more as much as you like. Don’t wait to log in because for the next 7 days, you have access to 9 awesome bonus channels as our gift to you!</p> <p>Thank you for joining YipTV. We hope you enjoy your FREE TV!</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{1}">Log In</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{1}">{1}</a></p><br/> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br/><br/> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    }
};
