'use strict';

var path = require('path'),
    rootPath = path.normalize(__dirname + '/../../..');

module.exports = {
    root: rootPath,
    email: {
        host: 'smtp.office365.com',
        port: 587,
        user: 'noreply@yiptv.com',
        password: 'Sept_25*',
        fromEmail: 'noreply@yiptv.com',
        fromName: 'YipTV'
    },
    contactUsEmailSubject: 'New Contact Us Request',
    contactUsEmailBody: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> <td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>New Contact Us Request</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="font-weight: bold">Name:</td> <td>{1}</td> </tr> <tr> <td style="font-weight: bold">Email:</td> <td>{2}</td> </tr> <tr> <td style="font-weight: bold">Telephone:&nbsp;</td> <td>{3}</td> </tr> <tr> <td style="font-weight: bold">Country:</td> <td>{4}</td> </tr> <tr> <td style="font-weight: bold">Interest:</td> <td><{5}</td> </tr> <tr> <td valign="top" style="font-weight: bold;vertical-align: text-top">Details:</td> <td>{6}</td> </tr> </table> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
    accountVerificationEmailSubject: {
        en: 'Welcome to YipTV',
        es: 'Welcome to YipTV'
    },
    accountVerificationEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> <td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>Welcome to YipTV. Please verify your YipTV account by clicking the button below. You will be able to use YipTV only after verifying your account. All future notifications will be sent to this email address.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{3}">Verify Account</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{3}">{3}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> <td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>Welcome to YipTV. Please verify your YipTV account by clicking the button below. You will be able to use YipTV only after verifying your account. All future notifications will be sent to this email address.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{3}">Verify Account</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{3}">{3}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    forgotPasswordEmailSubject: {
        en: 'Reset Password',
        es: 'Reset Password'
    },
    forgotPasswordEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> <td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>We received a request to reset the password for your account. If you made this request, click the button below. If you did not make this request you can ignore this email.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{3}">Reset Password</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{3}">{3}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> <td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>We received a request to reset the password for your account. If you made this request, click the button below. If you did not make this request you can ignore this email.</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{3}">Reset Password</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{3}">{3}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    passwordChangedEmailSubject: {
        en: 'Password Changed',
        es: 'Password Changed'
    },
    passwordChangedEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> <td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>You recently changed the password associated with your YipTV account. If you did not make this change and believe your YipTV account has been compromised, please contact YipTV customer care.</p> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> <td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>{1} {2},</p><br /> <p>You recently changed the password associated with your YipTV account. If you did not make this change and believe your YipTV account has been compromised, please contact YipTV customer care.</p> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>'
    },
    referAFriendEmailSubject: 'YipTV is here!',
    referAFriendEmailBody: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff; width:100%;height:100%"> <tr> <td align="center"> <table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"> <tr style="background-color:#f4f1ec"> <td style="padding:10px"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td> <td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Hello,</p><br /> <p>I have subscribed to YipTV and I get unlimited TV channels for $14.99. Click the button below to join YipTV now!</p> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <table cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding:10px;border-radius:5px;border:1px solid #A03269;background-color:#A03269;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;color:#fff" href="{1}">Join YipTV</a></td> </tr> </table> </td> </tr> <tr> <td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"> <p>Or click the link below:</p> <p><a href="{1}">{1}</a></p><br /> </td> </tr> <tr style="background-color:#f4f1ec"> <td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /> <p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p> </td> </tr> </table> </td> </tr></table>',
    factProviders: {},
    postProcessors: {},
    reminderEmailSubject: {
        en: 'Your YipTV free trial ends in {0} days!',
        es: 'Your YipTV free trial ends in {0} days!'
    },
    reminderEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#e4e7ea; width:100%;height:100%"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"><tr style="background-color:#f2f2f2"><td style="padding:10px"><table cellpadding="0" cellspacing="0" border="0"><tr><td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td><td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td></tr></table></td></tr><tr><td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"><p>{1} {2},</p><br /><p>We sincerely hope that you have been enjoying YipTV\'s premium channels for the {3}. We would like to take this opportunity to thank you again for signing up with us. </p><p>We are also pleased to bring to you our <b><i>Refer A Friend</i></b> program where you can earn free months when you refer your friends to join YipTV!<sup>*</sup></p><p>Pay a flat fee and become a YipTV paid subscriber today! Being a paid subscriber has many more benefits. Click the button below to pay using our secure payment gateway... </p></td></tr><tr><td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"><table cellpadding="0" cellspacing="0" border="0"><tr><td style="padding:10px;border-radius:5px;border:1px solid #17a08c;background-color:#1caf9a;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{4}">Join Revolution</a></td></tr></table></td></tr><tr style="background-color:#eeeeee"><td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"><sup>*</sup>Free months will be credited only if you are a paid subscriber and your friend becomes a paid subscriber.<br />Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV.<br /><br /><p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p></td></tr></table></td></tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#e4e7ea; width:100%;height:100%"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"><tr style="background-color:#f2f2f2"><td style="padding:10px"><table cellpadding="0" cellspacing="0" border="0"><tr><td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td><td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td></tr></table></td></tr><tr><td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"><p>{1} {2},</p><br /><p>We sincerely hope that you have been enjoying YipTV\'s premium channels for the {3}. We would like to take this opportunity to thank you again for signing up with us. </p><p>We are also pleased to bring to you our <b><i>Refer A Friend</i></b> program where you can earn free months when you refer your friends to join YipTV!<sup>*</sup></p><p>Pay a flat fee and become a YipTV paid subscriber today! Being a paid subscriber has many more benefits. Click the button below to pay using our secure payment gateway... </p></td></tr><tr><td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"><table cellpadding="0" cellspacing="0" border="0"><tr><td style="padding:10px;border-radius:5px;border:1px solid #17a08c;background-color:#1caf9a;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{4}">Join Revolution</a></td></tr></table></td></tr><tr style="background-color:#eeeeee"><td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"><sup>*</sup>Free months will be credited only if you are a paid subscriber and your friend becomes a paid subscriber.<br />Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV.<br /><br /><p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p></td></tr></table></td></tr></table>'
    },
    lastReminderEmailSubject: {
        en: 'Your YipTV free trial ends today!',
        es: 'Your YipTV free trial ends today!'
    },
    lastReminderEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#e4e7ea; width:100%;height:100%"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"><tr style="background-color:#f2f2f2"><td style="padding:10px"><table cellpadding="0" cellspacing="0" border="0"><tr><td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td><td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td></tr></table></td></tr><tr><td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"><p>{1} {2},</p><br /><p>We sincerely hope that you have been enjoying YipTV\'s premium channels for the {3}. We would like to take this opportunity to thank you again for signing up with us. </p><p>We are also pleased to bring to you our <b><i>Refer A Friend</i></b> program where you can earn free months when you refer your friends to join YipTV!<sup>*</sup></p><p>Pay a flat fee and become a YipTV paid subscriber today! Being a paid subscriber has many more benefits. Click the button below to pay using our secure payment gateway... </p></td></tr><tr><td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"><table cellpadding="0" cellspacing="0" border="0"><tr><td style="padding:10px;border-radius:5px;border:1px solid #17a08c;background-color:#1caf9a;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{4}">Join Revolution</a></td></tr></table></td></tr><tr style="background-color:#eeeeee"><td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"><sup>*</sup>Free months will be credited only if you are a paid subscriber and your friend becomes a paid subscriber.<br />Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV.<br /><br /><p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p></td></tr></table></td></tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#e4e7ea; width:100%;height:100%"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"><tr style="background-color:#f2f2f2"><td style="padding:10px"><table cellpadding="0" cellspacing="0" border="0"><tr><td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td><td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td></tr></table></td></tr><tr><td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"><p>{1} {2},</p><br /><p>We sincerely hope that you have been enjoying YipTV\'s premium channels for the {3}. We would like to take this opportunity to thank you again for signing up with us. </p><p>We are also pleased to bring to you our <b><i>Refer A Friend</i></b> program where you can earn free months when you refer your friends to join YipTV!<sup>*</sup></p><p>Pay a flat fee and become a YipTV paid subscriber today! Being a paid subscriber has many more benefits. Click the button below to pay using our secure payment gateway... </p></td></tr><tr><td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"><table cellpadding="0" cellspacing="0" border="0"><tr><td style="padding:10px;border-radius:5px;border:1px solid #17a08c;background-color:#1caf9a;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{4}">Join Revolution</a></td></tr></table></td></tr><tr style="background-color:#eeeeee"><td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"><sup>*</sup>Free months will be credited only if you are a paid subscriber and your friend becomes a paid subscriber.<br />Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV.<br /><br /><p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p></td></tr></table></td></tr></table>'
    },
    trialPeriodCompleteEmailSubject: {
        en: 'Your YipTV trial has ended!',
        es: 'Your YipTV trial has ended!'
    },
    trialPeriodCompleteEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#e4e7ea; width:100%;height:100%"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"><tr style="background-color:#f2f2f2"><td style="padding:10px"><table cellpadding="0" cellspacing="0" border="0"><tr><td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td><td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td></tr></table></td></tr><tr><td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"><p>{1} {2},</p><br /><p>Your YipTV trial has expired. If you would like to continue receiving the world\'s best internet TV, click below to subscribe instantly..</p><table cellpadding="0" cellspacing="0" border="0"><tr><td style="padding:10px;border-radius:5px;border:1px solid #17a08c;background-color:#1caf9a;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{3}">Join Revolution</a></td></tr></table><p>You can also subscribe using the link <a href="{3}">{3}</a></p><p>Subscribing to YipTV allows you to get free months and watch premium content among other benefits.<sup>*</sup></p></td></tr><tr style="background-color:#eeeeee"><td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"><sup>*</sup>Free months will be credited only if you are a paid subscriber and your friend becomes a paid subscriber.<br />Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /><p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p></td></tr></table></td></tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#e4e7ea; width:100%;height:100%"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"><tr style="background-color:#f2f2f2"><td style="padding:10px"><table cellpadding="0" cellspacing="0" border="0"><tr><td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td><td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td></tr></table></td></tr><tr><td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"><p>{1} {2},</p><br /><p>Your YipTV trial has expired. If you would like to continue receiving the world\'s best internet TV, click below to subscribe instantly..</p><table cellpadding="0" cellspacing="0" border="0"><tr><td style="padding:10px;border-radius:5px;border:1px solid #17a08c;background-color:#1caf9a;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{3}">Join Revolution</a></td></tr></table><p>You can also subscribe using the link <a href="{3}">{3}</a></p><p>Subscribing to YipTV allows you to get free months and watch premium content among other benefits.<sup>*</sup></p></td></tr><tr style="background-color:#eeeeee"><td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"><sup>*</sup>Free months will be credited only if you are a paid subscriber and your friend becomes a paid subscriber.<br />Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV. <br /><br /><p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p></td></tr></table></td></tr></table>'
    },
    reacquireUserEmailSubject: {
        en: 'We miss you at YipTV!',
        es: 'We miss you at YipTV!'
    },
    reacquireUserEmailBody: {
        en: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#e4e7ea; width:100%;height:100%"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"><tr style="background-color:#f2f2f2"><td style="padding:10px"><table cellpadding="0" cellspacing="0" border="0"><tr><td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td><td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td></tr></table></td></tr><tr><td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"><p>{1} {2},</p><br /><p>Your YipTV trial expired yesterday and we miss you already. If you would like to reactivate your account and continue watching the world\'s best internet TV, click below to re-activate instantly. <table cellpadding="0" cellspacing="0" border="0"><tr><td style="padding:10px;border-radius:5px;border:1px solid #17a08c;background-color:#1caf9a;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{3}">Re-Activate</a></td></tr></table><p>You can also reactivate using the link <a href="{3}">{3}</a></p><p>A YipTV paid subscription allows you to get free months and watch premium content among other benefits.<sup>*</sup></p></td></tr><tr style="background-color:#eeeeee"><td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"><sup>*</sup>Free months will be credited only if you are a paid subscriber and your friend becomes a paid subscriber.<br /> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV.<br /><br /><p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p></td></tr></table></td></tr></table>',
        es: '<table cellpadding="0" cellspacing="0" border="0" style="background-color:#e4e7ea; width:100%;height:100%"><tr><td align="center"><table cellpadding="0" cellspacing="0" border="0" style="background-color:#fff;color:#000;width:80%;font-size:14px;font-family:Verdana"><tr style="background-color:#f2f2f2"><td style="padding:10px"><table cellpadding="0" cellspacing="0" border="0"><tr><td><img width="87" height="80" style="vertical-align:middle" title="YipTV" alt="YipTV" src="{0}logo.png" /></td><td><span style="font-weight:bold;font-size:36px;vertical-align:middle;font-family:Verdana">YipTV</span></td></tr></table></td></tr><tr><td style="width:90%;padding:20px 50px;color: #000;font-size:14px;font-family:Verdana;text-align:justify"><p>{1} {2},</p><br /><p>Your YipTV trial expired yesterday and we miss you already. If you would like to reactivate your account and continue watching the world\'s best internet TV, click below to re-activate instantly. <table cellpadding="0" cellspacing="0" border="0"><tr><td style="padding:10px;border-radius:5px;border:1px solid #17a08c;background-color:#1caf9a;font-family:Verdana;font-weight:bold"><a style="display:inline-block;text-decoration:none;cursor:pointer;color:#fff" href="{3}">Re-Activate</a></td></tr></table><p>You can also reactivate using the link <a href="{3}">{3}</a></p><p>A YipTV paid subscription allows you to get free months and watch premium content among other benefits.<sup>*</sup></p></td></tr><tr style="background-color:#eeeeee"><td align="center" style="padding:20px;font-family:Verdana;font-size: 12px"><sup>*</sup>Free months will be credited only if you are a paid subscriber and your friend becomes a paid subscriber.<br /> Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of YipTV.<br /><br /><p style="color:#808080">YipTV Inc., West Palm Beach, FL, USA</p></td></tr></table></td></tr></table>'
    }
};
