(function (app) {
    'use strict';

    app.config(['$translateProvider', function ($translateProvider) {
        $translateProvider.translations('es', {
            CHANGE_CREDIT_CARD_BILLING_INFO: 'Ingresa datos nuevos de tu tarjeta de crédito. Si necesitas ayuda llame al',
            CHANGE_CREDIT_CARD_CARD_NAME: 'Nombre en tarjeta de crédito',
            CHANGE_CREDIT_CARD_CARD_NAME_REQUIRED: 'Ingresa nombre como aparece en tu tarjeta de crédito',
            CHANGE_CREDIT_CARD_ADDRESS: 'Domicilio de facturación de tu tarjeta de crédito',
            CHANGE_CREDIT_CARD_ADDRESS_REQUIRED: 'Ingresa dirección como aparece en tu tarjeta de crédito',
            CHANGE_CREDIT_CARD_CITY: 'Ciudad',
            CHANGE_CREDIT_CARD_CITY_REQUIRED: 'Ingresa ciudad como aparece en tu tarjeta de crédito',
            CHANGE_CREDIT_CARD_STATE: 'Estado',
            CHANGE_CREDIT_CARD_STATE_REQUIRED: 'Ingresa nombre de estado como aparece en tu tarjeta de crédito',
            CHANGE_CREDIT_CARD_STATE_LOAD_ERROR: 'Error al subir lista de estados',
            CHANGE_CREDIT_CARD_STATE_SELECT: 'Selecciona uno',
            CHANGE_CREDIT_CARD_CARD_NUMBER: 'Número de tarjeta de crédito',
            CHANGE_CREDIT_CARD_CARD_NUMBER_REQUIRED: 'Ingresa tu número de tarjeta de crédito',
            CHANGE_CREDIT_CARD_CARD_NUMBER_ERROR: 'Ingresa un número de tarjeta de crédito válido',
            CHANGE_CREDIT_CARD_CVV: 'CVV (Clave de Seguridad de 3 dígitos)',
            CHANGE_CREDIT_CARD_CVV_REQUIRED: 'Ingresa tu clave CVV',
            CHANGE_CREDIT_CARD_CARD_NUMBER_CVV_ERROR: 'Ingresa tu clave CVV válida',
            CHANGE_CREDIT_CARD_EXPIRY_DATE: 'Fecha de expiración',
            CHANGE_CREDIT_CARD_EXPIRY_DATE_REQUIRED: 'Ingresa fecha de expiración de tu tarjeta de crédito',
            CHANGE_CREDIT_CARD_EXPIRY_DATE_INVALID: 'Ingresa fecha de expiración válida',
            CHANGE_CREDIT_CARD_ZIP_CODE: 'Código postal',
            CHANGE_CREDIT_CARD_ZIP_CODE_REQUIRED: 'Ingresa tu código postal',
            CHANGE_CREDIT_CARD_ZIP_CODE_INVALID: 'Ingresa código postal válido',
            CHANGE_CREDIT_CARD_CARD_NAME_INVALID: 'Ingresa nombre válido',
            CHANGE_CREDIT_CARD_ADDRESS_INVALID: 'Ingresa dirección válida',
            CHANGE_CREDIT_CARD_CITY_INVALID: 'Ingresa ciudad válida',
            CHANGE_CREDIT_CARD_SUBMIT_BUTTON: 'Envía',
            CHANGE_CREDIT_CARD_SUCCESS: 'Tu tarjeta de crédito ha sido cambiada',
            CHANGE_CREDIT_CARD_FAILED: 'Error al cambiar tu tarjeta de crédito. Por favor contacta servicio al cliente',
            CHANGE_CREDIT_CARD_PROBLEM: '¿Problemas al cambiar tu tarjeta de crédito? Por favor contacta servicio al cliente',
            CHANGE_CREDIT_CARD_ACCESS_ERROR: 'No puedes cambiar tu tarjeta de crédito. Por favor contacta servicio al cliente',
            CHANGE_CREDIT_CARD_PAYMENT_ERROR: 'No pudimos procesar el pago con tu tarjeta. Verifica tu información de tarjeta de crédito.',
            CHANGE_CREDIT_CARD_FREE_USER_ERROR: 'Los usuarios con membresías temporales no pueden agregar una tarjeta de crédito a su cuenta',
            CHANGE_CREDIT_CARD_COMP_USER_ERROR: 'Los usuarios con membresías de cortesía no pueden agregar una tarjeta de crédito a su cuenta',
            CHANGE_CREDIT_CARD_ACCOUNT_REFRESH_ERROR: 'Por favor cierra y vuelva a abrir la ventana del navegador de la aplicación de YipTV.',
            CHANGE_PASSWORD_CURRENT_PASSWORD: 'Contraseña actual',
            CHANGE_PASSWORD_NEW_PASSWORD: 'Contraseña nueva',
            CHANGE_PASSWORD_BUTTON: 'Envía',
            CHANGE_PASSWORD_CURRENT_PASSWORD_REQUIRED: 'Ingresa tu contraseña actual',
            CHANGE_PASSWORD_NEW_PASSWORD_REQUIRED: 'Ingresa contraseña nueva',
            CHANGE_PASSWORD_NEW_PASSWORD_NOT_COMPLEX: 'Tu contraseña debe tener al menos 6 caracteres, 1 letra mayúscula y un número',
            CHANGE_PASSWORD_NEW_PASSWORD_SAME: 'Tu contraseña nueva no puede ser la misma contraseña actual',
            CHANGE_PASSWORD_ERROR: 'Hubo un error al cambiar la contraseña',
            CHANGE_PASSWORD_INCORRECT_PASSWORD: 'La contraseña que ingresaste es incorrecta',
            CHANGE_PASSWORD_SUCCESS: 'Tu contraseña ha sido cambiada',
            CHANNEL_GUIDE_ON_NOW: 'Transmitiendo Ahora: ',
            CHANNEL_GUIDE_LOAD_ERROR: 'Error al subir guía de canales',
            COMP_SIGN_UP_HEADING: 'Regístrate',
            COMP_SIGN_UP_MESSAGE: 'Regístrate para obtener una cuenta gratis de YipTV.',
            COMP_SIGN_UP_VERIFYING: 'Verificando…',
            COMP_SIGN_UP_CODE_EXPIRED: 'Tu código de invitación no es válido o ha expirado!',
            COMP_SIGN_UP_FIRST_NAME: 'Nombre',
            COMP_SIGN_UP_FIRST_NAME_REQUIRED: 'Ingresa tu nombre',
            COMP_SIGN_UP_LAST_NAME_REQUIRED: 'Ingresa tu apellido',
            COMP_SIGN_UP_FIRST_NAME_INVALID: 'Ingresa un nombre válido',
            COMP_SIGN_UP_LAST_NAME_INVALID: 'Ingresa un apellido válido',
            COMP_SIGN_UP_EMAIL: 'Correo Electrónico o Número de Celular',
            COMP_SIGN_UP_VERIFICATION: 'Una verificación de número de PIN se enviará al número de celular<sup>*</sup> o correo electrónico que proporcionaste.',
            COMP_SIGN_UP_TELEPHONE_INVALID: 'Ingresa un número de celular válido de EE.UU',
            COMP_SIGN_UP_SEND_SMS_VERIFICATION_FINE_PRINT: '<sup>*</sup>Podrían aplicar cargos de data',
            COMP_SIGN_UP_LAST_NAME: 'Apellido',
            COMP_SIGN_UP_EMAIL_INVALID: 'Ingresa una dirección de correo electrónico o número de celular válido',
            COMP_SIGN_UP_EMAIL_EXISTS: 'Ya tienes cuenta con nosotros. Por favor ingresa.',
            COMP_SIGN_UP_EMAIL_REQUIRED: 'Ingresa tu dirección de correo electrónico o número de celular',
            COMP_SIGN_UP_PASSWORD: 'Contraseña',
            COMP_SIGN_UP_PASSWORD_INFO: '(Por favor utiliza 6 caracteres o más, y cuando menos 1 número, y 1 letra mayúscula)',
            COMP_SIGN_UP_PASSWORD_REQUIRED: 'Ingresa tu contraseña',
            COMP_SIGN_UP_PASSWORD_NOT_COMPLEX: 'Tu contraseña debe tener al menos 6 caracteres, 1 letra mayúscula y 1 número',
            COMP_SIGN_UP_TERMS_OF_USE: 'Términos de uso',
            COMP_SIGN_UP_AND: 'y la',
            COMP_SIGN_UP_SUBMIT_BUTTON: 'Regístrate',
            COMP_SIGN_UP_FORM_INVALID: 'Hubo un problema con la información que ingresaste en una o más secciones del formulario. Por favor revisa tus entradas y haz clic en “Envía”.',
            COMP_SIGN_UP_HAVE_ACCOUNT: '¿Ya tienes una cuenta?',
            COMP_SIGN_UP_SIGN_IN: 'Ingresa',
            COMP_SIGN_UP_EMAIL_SMS_SUBSCRIPTION: 'Favor de envíarme notificaciones al número de celular<sup>*</sup> o al correo electrónico ingresado anteriormente.',
            COMP_SIGN_UP_DISCLAIMER: 'Acepto los',
            COMP_SIGN_UP_DISCLAIMER_END: 'de YipTV.',
            COMP_SIGN_UP_DISCLAIMER_REQUIRED: 'Para utilizar los servicios de YipTV necesitas aceptar nuestras condiciones de uso y pólitica de privacidad',
            COMP_SIGN_UP_PRIVACY_POLICY: 'Política de privacidad',
            COMP_SIGN_UP_USER_EXISTS: 'Ésta dirección de correo electrónico o número de teléfono móvil ya está registrada con YipTV. Por favor usa otra dirección de correo electrónico o número de teléfono móvil',
            COMP_SIGN_UP_FAILED: 'Error al ingresar usuario. Por favor contacta servicio al cliente',
            COMP_SIGN_UP_PROBLEM: '¿Tienes problemas para registrarte? Contacta servicio al cliente',
            COMP_SIGN_UP_TELEPHONE_MOBILE: '&#10003; Número de Celular Verificado',
            COMP_SIGN_UP_TELEPHONE_CHECKING_IF_MOBILE: 'Verificando número de celular. Por favor espera...',
            CONTACT_US_HEADING: 'Contáctanos',
            CONTACT_US_NAME: 'Nombre',
            CONTACT_US_INTEREST: 'Interés',
            CONTACT_US_INTEREST_SELECT: 'Selecciona uno',
            CONTACT_US_INTEREST_INVESTOR: 'Se inversionista de YipTV',
            CONTACT_US_INTEREST_TECHNICAL: 'Apoyo técnico',
            CONTACT_US_INTEREST_BILLING: 'Apoyo en facturación',
            CONTACT_US_EMAIL: 'Correo Electrónico o Número de Celular<sup>*</sup>',
            CONTACT_US_SMS_FINE_PRINT: '<sup>*</sup>Podrían aplicar cargos de data',
            CONTACT_US_DETAILS: '¿Cómo podemos ayudarte?',
            CONTACT_US_COUNTRY: 'País',
            CONTACT_US_COUNTRY_SELECT: 'Selecciona uno',
            CONTACT_US_COUNTRY_REQUIRED: 'Selecciona tu Pais',
            CONTACT_US_SUBMIT_BUTTON: 'Envía',
            CONTACT_US_NAME_REQUIRED: 'Ingresa tu nombre',
            CONTACT_US_INTEREST_REQUIRED: 'Ingresa tu tipo de interes',
            CONTACT_US_EMAIL_REQUIRED: 'Ingresa tu correo electrónico o número de celular',
            CONTACT_US_EMAIL_INVALID: 'Ingresa correo electrónico o número de celular válido',
            CONTACT_US_DETAILS_REQUIRED: '¿Como podemos ayudarte?',
            CONTACT_US_TELEPHONE_REQUIRED: 'Ingresa tu número de celular',
            CONTACT_US_ERROR: 'Error al enviar tu solicitud',
            CONTACT_US_COUNTRY_LOAD_ERROR: 'Error al subir la lista de países',
            CONTACT_US_SUCCESS_HEADING: 'Contáctanos',
            CONTACT_US_SUCCESS_MESSAGE: 'Tu solicitud ha sido enviada',
            FORGOT_PASSWORD_HEADING: 'Olvidaste tu Contraseña',
            FORGOT_PASSWORD_EMAIL: 'Correo Electrónico o Número de Celular<sup>*</sup>',
            FORGOT_PASSWORD_BUTTON: 'Envía',
            FORGOT_PASSWORD_EMAIL_INVALID: 'Ingresa correo electrónico o número de celular válidos',
            FORGOT_PASSWORD_EMAIL_REQUIRED: 'Ingresa tu correo electrónico o número de celular',
            FORGOT_PASSWORD_ERROR: 'Error al enviar nuevo PIN de contraseña. Por favor contacta servicio al cliente',
            FORGOT_PASSWORD_SMS_FINE_PRINT: '<sup>*</sup>Podrían aplicar cargos de data',
            FREE_SIGN_UP_HEADING: 'Mi MEMBRESÍA GRATIS YipTV',
            FREE_SIGN_UP_MESSAGE: 'Sin Periodo De Prueba, Sin Trampas, Solo Televisión por Internet Gratis!',
            FREE_SIGN_UP_BULLET1: '18+ Canales Gratis de TV Internacional en vivo',
            FREE_SIGN_UP_BULLET2: 'Además – 9 Canales Premier Gratis por los primeros 7 días',
            FREE_SIGN_UP_BULLET3: 'No Requiere Tarjeta de Crédito, Contrato, o Paquete de Cable',
            FREE_SIGN_UP_BULLET4: 'Quédate con tu Membresía GRÁTIS indefinidamente, o cambia a la Membresía Premier y recibe 100+ canales, ¡tu decides!',
            FREE_SIGN_UP_FIRST_NAME: 'Primer nombre',
            FREE_SIGN_UP_FIRST_NAME_REQUIRED: 'Ingresa tu nombre',
            FREE_SIGN_UP_LAST_NAME_REQUIRED: 'Ingresa tu apellido',
            FREE_SIGN_UP_FIRST_NAME_INVALID: 'Ingresa un nombre válido',
            FREE_SIGN_UP_LAST_NAME_INVALID: 'Ingresa un apellido válido',
            FREE_SIGN_UP_EMAIL: 'Correo Electrónico o Número de Celular',
            FREE_SIGN_UP_VERIFICATION: 'Una clave de PIN se enviará al número de celular<sup>*</sup> o correo electrónico que proporcionaste.',
            FREE_SIGN_UP_SEND_SMS_VERIFICATION_FINE_PRINT: '<sup>*</sup>Podrían aplicar cargos de data',
            FREE_SIGN_UP_LAST_NAME: 'Tu apellido',
            FREE_SIGN_UP_EMAIL_INVALID: 'Ingresa una dirección de correo electrónico o número de celular de EE.UU. válido',
            FREE_SIGN_UP_EMAIL_EXISTS: 'Ya tienes cuenta con nosotros. Por favor ingresa.',
            FREE_SIGN_UP_EMAIL_REQUIRED: 'Ingresa tu dirección de correo electrónico o número de celular',
            FREE_SIGN_UP_TELEPHONE_INVALID: 'Ingresa un número de celular valido de EE.UU.',
            FREE_SIGN_UP_TELEPHONE_MOBILE: '&#10003; Número de Celular Verificado',
            FREE_SIGN_UP_TELEPHONE_CHECKING_IF_MOBILE: 'Verificando tu número de celular. Por favor espera...',
            FREE_SIGN_UP_PASSWORD: 'Contraseña',
            FREE_SIGN_UP_PASSWORD_INFO: '(Por favor utiliza 6 caracteres o mas, y cuando menos 1 número, y 1 letra mayúscula)',
            FREE_SIGN_UP_PASSWORD_REQUIRED: 'Ingresa tu contraseña',
            FREE_SIGN_UP_PASSWORD_NOT_COMPLEX: 'Contraseña debe tener al menos 6 caracteres, una letra mayúscula y 1 número',
            FREE_SIGN_UP_TERMS_OF_USE: 'Términos de Uso',
            FREE_SIGN_UP_AND: 'y',
            FREE_SIGN_UP_SUBMIT_BUTTON: 'Comienza Mi Membresía Gratis',
            FREE_SIGN_UP_FORM_INVALID: 'Hubo un problema con la información que ingresaste en una o más secciones del formulario. Por favor revisa tus entradas y haz clic en "Comienza Mi Membresía Gratis".',
            FREE_SIGN_UP_HAVE_ACCOUNT: '¿Ya tienes una cuenta?',
            FREE_SIGN_UP_SIGN_IN: 'Ingresa',
            FREE_SIGN_UP_EMAIL_SMS_SUBSCRIPTION: 'Por favor enviarme notificaciones al número de celular<sup>*</sup> o al correo electrónico ingresado anteriormente.',
            FREE_SIGN_UP_DISCLAIMER: 'Estoy de acuerdo con los',
            FREE_SIGN_UP_DISCLAIMER_END: 'de YipTV.',
            FREE_SIGN_UP_DISCLAIMER_REQUIRED: 'Para utilizar los servicios YipTV necesitas aceptar nuestras las condiciones de uso y pólitica de privacidad',
            FREE_SIGN_UP_PRIVACY_POLICY: 'Pólítica de Privacidad',
            FREE_SIGN_UP_USER_EXISTS: 'Ésta dirección de correo electrónico o número de teléfono móvil ya está registrada con YipTV. Por favor usa otra dirección de correo electrónico o número de teléfono móvil',
            FREE_SIGN_UP_FAILED: 'Error al ingresar usuario. Por favor contacta servicio al cliente',
            FREE_SIGN_UP_PROBLEM: '¿Tienes problemas para inscribirte? Contacta servicio al cliente',
            FREE_SIGN_UP_SUCCESS_HEADING: '¡Gracias – Bienvenido a YipTV!',
            FREE_SIGN_UP_SUCCESS_SUB_HEADING: '¡Empecemos!',
            FREE_SIGN_UP_SUCCESS_LINE1_PART1: '¡Felicidades, ya eres <span class="bolder-text">Miembro GRÁTIS de YipTV!</span>',
            FREE_SIGN_UP_SUCCESS_LINE3_PART1: 'Puedes ver TV directamente en tu computadora o en tu navegador iOS, televisión inteligente, o cualquier dispositivo conectado al Internet. Si tienes preguntas sobre como ver televisión en tu dispositivo, visita nuestra sección de',
            FREE_SIGN_UP_SUCCESS_LINE3_PART2: 'o llama servicio al cliente:',
            FREE_SIGN_UP_SUCCESS_FAQS: 'Preguntas frecuentes',
            FREE_SIGN_UP_SUCCESS_LINE4: 'Baja el App Gratis y ve YipTV en vivo en tu celular',
            FREE_SIGN_UP_SUCCESS_LINE5: 'Tu Membresía Gratis Incluye:',
            FREE_SIGN_UP_SUCCESS_BULLET1: '18+ Canales Internacionales de Televisión en Vivo Gratis',
            FREE_SIGN_UP_SUCCESS_BULLET2: 'Además – disfruta de 9 canales de la Membresía Premier durante los primeros 7 días',
            FREE_SIGN_UP_SUCCESS_BULLET3: 'Ve en 2 dispositivos',
            FREE_SIGN_UP_SUCCESS_BULLET4: 'Quédate con tu <span class="bolder-text">Membresía Gratis</span> indefinidamente, o cambia a la Membresía Premier y recibe 100+ canales, ¡tu decides!',
            FREE_SIGN_UP_SUCCESS_QUESTIONS: '¿Preguntas? Llama servicio al cliente:',
            INDEX_TOP: 'Superior ^',
            INDEX_OTHER_LANGUAGE: 'English',
            INDEX_SIGN_IN: 'Ingresa',
            INDEX_OK_BUTTON: 'Ok',
            INDEX_YES_BUTTON: 'Sí',
            INDEX_NO_BUTTON: 'No',
            INDEX_CONTACT_NUMBER: 'Llámanos grátis: 855-919-4788',
            INDEX_SOCIAL_MEDIA: '<a target="_blank" href="https://www.facebook.com/yiptvespanol"><img src="images/facebook.png" alt=""/></a><a target="_blank" href="https://twitter.com/YipTV"><img src="images/twitter.png" alt=""/></a>',
            INDEX_COPYRIGHT: 'Derechos de Autor ® 2012-2016 YIPTV. Uso del servicio de YIPTV y de ésta página web constituye aceptación de nuestros términos de uso y política de privacidad.',
            INDEX_LABEL_JOIN_FREE: 'Únete Gratis',
            INDEX_LABEL_$1PREMIUM: '$1 Premier',
            INDEX_LABEL_JOIN_PREMIUM: 'Únete A Premier $1',
            INDEX_LABEL_CHANNELS: 'Canales',
            INDEX_LABEL_FAQ: 'Preguntas frecuentes',
            INDEX_LABEL_WATCH_NOW: 'Ingresar/Ver Ahora',
            INDEX_LABEL_CALL_US: 'Ver Ahora: 855-909-4788',
            INDEX_LABEL_HOW_TO_WATCH: 'Cómo Ver',
            INDEX_LABEL_TERMS_OF_SERVICE: 'Términos de uso',
            INDEX_LABEL_END_USER: 'Acuerdo de Licencia de software para Usuario',
            INDEX_LABEL_LEGAL1: 'Derechos de Autor © 2016 Tv en Vivo Gratis – Ver TV Gratis por Internet en YipTV.. Uso de el servicio de YIPTV y de esta pagina web constituye aceptación de nuestros términos de uso y póliza de privacidad.',
            INDEX_LABEL_FAQS: 'Preguntas Frecuentes',
            INDEX_LABEL_PRIVACY_POLICY: 'Política de privacidad',
            MAIN_ERROR_APP_CONFIG: 'Error para capturar configuración de la aplicación',
            MAIN_SIGN_OUT_CONFIRMATION: '¿Seguro que deseas salir de YipTV?',
            MAIN_LANGUAGE_CHANGE_SAVE_CHECK: 'Deseas cambiar tu idioma preferido a',
            MAIN_LANGUAGE_CHANGE_SAVE_SUCCESS: 'Preferencia de idioma guardadas.',
            MAIN_LANGUAGE_CHANGE_SAVE_ERROR: 'Error al cambiar tu preferencia de idioma. Por favor contacta servicio al cliente',
            NOT_FOUND_HEADING: 'Página no disponible',
            NOT_FOUND_MESSAGE: 'La página que buscas no existe',
            NOT_SUPPORTED_HEADING: 'Descarga la aplicación móvil YipTV',
            NOT_SUPPORTED_MESSAGE: 'Para acceder a YipTV en móvil dispositivos por favor descargar nuestra aplicación móvil',
            PIN_VERIFICATION_HEADING: 'Verifica tu Cuenta',
            PIN_VERIFICATION_MESSAGE: 'Por favor ingresa tu PIN antes de cerrar ventana',
            PIN_VERIFICATION_PIN: 'Ingresa el PIN (recibido por mensaje de texto o correo electrónico)',
            PIN_VERIFICATION_PIN_REQUIRED: 'Ingresa tu PIN',
            PIN_VERIFICATION_PIN_INVALID: 'Ingresa un PIN válido',
            PIN_VERIFICATION_BUTTON: 'Envía tu PIN',
            PIN_VERIFICATION_PIN_MISMATCH: 'PIN ingresado no es correcto. Por favor, ingresa el PIN recibido por mensaje de texto o correo electrónico',
            PIN_VERIFICATION_ERROR: 'No se puede verificar la cuenta o la cuenta ya está verificada. Por favor contacta servicio al cliente en:',
            PIN_VERIFICATION_SUCCESS_HEADING: 'Cuenta verificada',
            PIN_VERIFICATION_SUCCESS_MESSAGE: 'Tu cuenta se ha verificado. Haz clic en el botón "Ingresa" para ver YipTV.',
            PLAYER_ON_NOW: 'Transmitiendo ahora: ',
            PLAYER_TIME: 'Tiempo: ',
            PLAYER_NOT_AVAILABLE: 'Programación no Disponible',
            PLAYER_DURATION: 'Duración: ',
            PLAYER_DESCRIPTION: 'Descripción: ',
            PLAYER_TITLE: 'Título: ',
            PLAYER_MINUTES: 'Minutos',
            PLAYER_RESULTS: 'Resultados:',
            PLAYER_CHANNELS_FOUND: 'canal(es) encontrados!',
            PLAYER_REGION: 'Región',
            PLAYER_CHANNEL_FILTER: 'Filtro de Canal',
            PLAYER_CHANNEL_LOAD_ERROR: 'Error al subir canal',
            PLAYER_CHANNEL_LIST_LOAD_ERROR: 'Error al subir lista de canales',
            PLAYER_CHANNEL_GUIDE_LOAD_ERROR: 'Error al subir guía de canales',
            PLAYER_PROMO_CHANNEL_LIST_LOAD_ERROR: 'Error al subir lista de canales promocionales',
            PLAYER_MENU_PREVIOUS_CHANNEL: 'Canal Anterior',
            PLAYER_MENU_NEXT_CHANNEL: 'Siguiente Canal',
            PLAYER_MENU_INFORMATION: 'Información',
            PLAYER_NO_FAVORITES: 'No Hay Favoritos Seleccionados',
            PLAYER_NO_FILTERED_CHANNELS: 'No Hay Canales',
            PLAYER_NO_RECENT_CHANNELS: 'No Hay Canales Recientes',
            FILTER_FILTERED_CHANNELS_FOUND: 'canal(es) encontrados: ',
            FILTER_CATEGORIES: 'Categorías',
            FILTER_CLEAR_ALL: 'Borrar Todo',
            FILTER_CLOSE: 'Cerrar',
            FILTER_GENRE: 'Género',
            FILTER_ORIGIN: 'Origen',
            FILTER_AUDIENCE: 'Audiencia',
            FILTER_MENU_RECENT: 'Reciente',
            FILTER_MENU_ALL: 'Todos',
            FILTER_LANGUAGE: 'Idioma',
            FILTER_MENU_FAVORITE: 'Favoritos',
            FILTER_MENU_FILTER: 'Filtrar',
            FILTER_MENU_ADD_REMOVE_FAVORITE: 'Añade/Remueve Favorito',
            FILTER_PROG_TITLE_UNAVAILABLE: 'Ningún Título Disponible',
            FILTER_PROG_DESCRIPTION_UNAVAILABLE: 'No hay descripción disponible',
            PREFERENCES_PREFERRED_LANGUAGE: 'Elige tu idioma preferido',
            PREFERENCES_PREFERRED_LANGUAGE_REQUIRED: 'Elige tu idioma preferido',
            PREFERENCES_EMAIL_SMS_SUBSCRIPTION: 'Favor de enviarme notificaciones al número de celular<sup>*</sup> o correo electrónico con el cual ingresé',
            PREFERENCES_SUBMIT_BUTTON: 'Envía',
            PREFERENCES_FETCH_ERROR: 'No se pudieron obtener tus preferencias. Por favor contacta servicio al cliente',
            PREFERENCES_SAVE_ERROR: 'Error al guardar tus preferencias. Por favor contacta servicio al cliente',
            PREFERENCES_SAVED: 'Tus preferencias han sido guardadas.',
            PREFERENCES_SMS_FINE_PRINT: '<sup>*</sup>Podrían aplicar cargos de data',
            RAF_HEADING: 'Recomienda un amigo',
            RAF_MESSAGE: 'Recomienda YipTV Grátis a todos tus amigos, y todos recibirán TV Gratis. Por cada uno de tus amigos que se inscriba como Miembro Premier, cada uno de ustedes recibirá un mes GRÁTIS. ¡Invítalos a todos,la oferta es ilimitada!',
            RAF_FINE_PRINT: '<sup>*</sup>Si tu (el Referente) recomiendas YipTV a otra persona (el Referido), y se completa satisfactoriamente su registro para suscribirse, el Referente recibirá un crédito por un mes de su costo mensual de servicio y el Referido también recibirá un crédito por un mes de su costo mensual de servicio (hasta $14,99 de crédito, al mes) únicamente si, y después de que, el Referido haya mantenido la suscripción con YipTV por sesenta y un (61) días consecutivos. El crédito no aplica para los costos adicionales, incluyendo, entre otros, los servicios o características Premier. La cancelación por parte del Referente o el Referido antes de los sesenta y un (61) días consecutivos, desde la fecha en que el Referido se suscribe a YipTV, resultará en la pérdida y/o reembolso de los créditos asociados. En caso de que el Referente o el Referido tuvieran un saldo adeudado, entonces se aplicará un crédito. Los créditos obtenidos no tienen valor en efectivo, y equivalen a un mes de servicio, independientemente de posibles cambios, pasados o futuros, en el precio de suscripción del servicio. Si el cliente cancela el servicio y le quedan créditos por recomendaciones, entonces esos créditos, de haberlos, se perderán. El crédito no tiene valor en efectivo, es intransferible y no es reembolsable. Ciertos tipos de recomendaciones, incluyendo entre otros, referir a ti mismo o a alguien que viva en la misma residencia que tu, están prohibidos. La oferta, los precios y los cargos están sujetos a cambios sin previo aviso. Se pueden aplicar otros términos y condiciones. Consulta los términos de uso para más información. Nulo donde esté prohibido. La oferta no puede ser combinada y está sujeta a restricciones y limitaciones.',
            RAF_MY_EMAIL: 'Mi dirección de correo electrónico',
            RAF_EMAIL_REQUIRED: 'Ingresa tu correo electrónico',
            RAF_EMAIL_INVALID: 'Ingrese un correo electrónico válido',
            RAF_IMPORT_CONTACT_LIST: 'Importa mi lista de contactos',
            RAF_LOADING: 'Cargando...',
            RAF_OR: 'o',
            RAF_ENTER_FRIENDS_EMAIL: 'Ingresa las direcciones de correos electrónicos de tus amigos, sepáralas con comas',
            RAF_SEND_INVITE: 'Envía invitación',
            RAF_EMAIL_SEND_ERROR: 'Error al enviar invitación de YipTV a tus amigos',
            RAF_EMAIL_LIST_REQUIRED: 'Ingresa por lo menos una dirección de correo electrónico',
            RAF_EMAIL_LIST_INVALID: 'Una o mas direcciones de correos electrónicos no son válidas',
            RAF_SUCCESS_HEADING: 'Recomienda a un amigo',
            RAF_SUCCESS_MESSAGE: 'Hemos enviado una invitación a tus amigos',
            REDIRECT_MESSAGE: 'Redireccionando…',
            RESEND_VERIFICATION_HEADING: 'Reenvía PIN de verificación',
            RESEND_VERIFICATION_EMAIL: 'Correo electrónico o número de celular <sup>*</sup>',
            RESEND_VERIFICATION_EMAIL_INVALID: 'Ingresa una dirección de correo electrónico o número de celular válidos',
            RESEND_VERIFICATION_EMAIL_REQUIRED: 'Ingresa tu dirección de correo electrónico o número de celular',
            RESEND_VERIFICATION_SEND_SMS_VERIFICATION_FINE_PRINT: '<sup>*</sup>Podrían aplicar cargos de data',
            RESEND_VERIFICATION_BUTTON: 'Envía',
            RESEND_VERIFICATION_USER_ERROR: 'Cuenta no encontrada o ya está activada',
            RESEND_VERIFICATION_ERROR: 'Error al enviar el enlace de verificación de la cuenta. Contacta servicio al cliente',
            RESET_PASSWORD_HEADING: 'Cambia tu contraseña',
            RESET_PASSWORD_PIN: 'Ingresa el PIN para cambiar tu contraseña (PIN recibido en mensaje de texto o correo electrónico)',
            RESET_PASSWORD_PIN_INVALID: 'PIN para cambiar contraseña es válido',
            RESET_PASSWORD_PIN_REQUIRED: 'Ingresa PIN para cambiar tu contraseña',
            RESET_PASSWORD_NEW_PASSWORD: 'Nueva Contraseña',
            RESET_PASSWORD_NEW_PASSWORD_NOT_COMPLEX: 'Tu contraseña debe tener al menos 6 caracteres, 1 letra mayúscula y 1 número',
            RESET_PASSWORD_NEW_PASSWORD_REQUIRED: 'Ingresa tu contraseña',
            RESET_PASSWORD_BUTTON: 'Envía',
            RESET_PASSWORD_RESET_ERROR: 'No se puede cambiar la contraseña. Por favor, contacta servicio al cliente',
            RESET_PASSWORD_PIN_ERROR: 'El PIN para cambiar tu contraseña es incorrecto',
            RESET_PASSWORD_SUCCESS_HEADING: 'Cambia Contraseña',
            RESET_PASSWORD_SUCCESS_MESSAGE: 'Tu contraseña ha sido cambiada.',
            SIGN_IN_HEADING: 'Bienvenido de nuevo a YipTV. Inicia sesión para ver tus programas favoritos.',
            SIGN_IN_SUB_HEADING_PART1: '¿Todavía no te has registrado? ¡Haz clic',
            SIGN_IN_SUB_HEADING_PART2: 'aquí para registrarte',
            SIGN_IN_SUB_HEADING_PART3: 'y empieza a ver TV ahora!',
            SIGN_IN_EMAIL: 'Correo Electrónico o Número de Celular',
            SIGN_IN_EMAIL_REQUIRED: 'Ingresa tu dirección de correo electrónico o número de celular',
            SIGN_IN_EMAIL_INVALID: 'Ingresa tu dirección de correo electrónico o número de celular válidos',
            SIGN_IN_PASSWORD: 'Contraseña',
            SIGN_IN_PASSWORD_REQUIRED: 'Ingresa tu contraseña',
            SIGN_IN_SUBMIT_BUTTON: 'Inicia sesión',
            SIGN_IN_FORGOT_PASSWORD: '¿Olvidaste tu contraseña?',
            SIGN_IN_RESET_PASSWORD: 'Cambia tu contraseña',
            SIGN_IN_NOT_REGISTERED: '¿Aún no estás registrado?',
            SIGN_IN_SIGN_UP: 'Regístrate',
            SIGN_IN_FAILED_NOT_VERIFIED: 'Error al ingresar. Tu cuenta aún no ha sido verificada.',
            SIGN_IN_FAILED: 'Error al ingresar',
            SIGN_IN_NO_VERIFICATION_EMAIL: '¿No has recibió el PIN de verificación?',
            SIGN_IN_RESEND_VERIFICATION: 'Solcítalo de nuevo',
            SIGN_IN_UPGRADE_SUBSCRIPTION: 'Tienes que ingresar de nuevo antes de poder cambiar a Membresía a Premier.',
            SIGN_UP_SUB_HEADING: 'MI MEMBRESÍA PREMIER de YIPTV',
            SIGN_UP_QUESTIONS: '¿Preguntas? Contacta servicio al cliente:',
            SIGN_UP_ORDER_SUMMARY: 'Datos de Pedido - Membresía Premier',
            SIGN_UP_BULLET0: '¡Solo paga $1 por tu primer mes!',
            SIGN_UP_BULLET1: '100+ Canales Internacionales en Vivo',
            SIGN_UP_BULLET2: 'Incluye acceso para usar en hasta 5 dispositivos',
            SIGN_UP_BULLET3: 'Sin Contrato – Cancela en Cualquier Momento',
            SIGN_UP_ITEM1: '1 Mes de Membresía Premier:',
            SIGN_UP_AMOUNT1: '$14.99',
            SIGN_UP_ITEM2: 'Descuento Promocional:',
            SIGN_UP_AMOUNT2: '-$13.99',
            SIGN_UP_ITEM3: 'Impuestos & Costos Ocultos:',
            SIGN_UP_AMOUNT3: '$0.00',
            SIGN_UP_ITEM_TOTAL: 'Costo Mensual Total:',
            SIGN_UP_AMOUNT_TOTAL: '$1.00',
            SIGN_UP_ITEM1_DISCOUNT: '1 Mes de Membresía Premier:',
            SIGN_UP_AMOUNT1_DISCOUNT: '$11.99',
            SIGN_UP_ITEM2_DISCOUNT: 'Impuestos & Costos Ocultos:',
            SIGN_UP_AMOUNT2_DISCOUNT: '$0.00',
            SIGN_UP_ITEM_TOTAL_DISCOUNT: 'Costo Mensual Total:',
            SIGN_UP_AMOUNT_TOTAL_DISCOUNT: '$11.99',
            SIGN_UP_FIRST_NAME: 'Primer Nombre',
            SIGN_UP_FIRST_NAME_REQUIRED: 'Ingresa tu nombre',
            SIGN_UP_LAST_NAME_REQUIRED: 'Ingresa tu apellido',
            SIGN_UP_FIRST_NAME_INVALID: 'Ingresa un nombre válido',
            SIGN_UP_LAST_NAME_INVALID: 'Ingresa un apellido válido',
            SIGN_UP_CARD_NAME_INVALID: 'Ingresa un nombre válido',
            SIGN_UP_ADDRESS_INVALID: 'Ingresa una dirección válida',
            SIGN_UP_CITY_INVALID: 'Ingresa ciudad válida',
            SIGN_UP_EMAIL: 'Correo Electrónico o Número de Celular',
            SIGN_UP_VERIFICATION: 'Una verificación de número de PIN será enviado al número de celular<sup>*</sup> o correo electrónico que proporcionaste.',
            SIGN_UP_TELEPHONE_INVALID: 'Ingresa un número de celular válido de EE.UU',
            SIGN_UP_SEND_SMS_VERIFICATION_FINE_PRINT: '<sup>*</sup>Podrían aplicar cargos de data',
            SIGN_UP_LAST_NAME: 'Apellido',
            SIGN_UP_EMAIL_INVALID: 'Ingresa un correo electrónico o número de celular válido',
            SIGN_UP_EMAIL_EXISTS: 'Ya tienes cuenta con nosotros. Por favor ingresa.',
            SIGN_UP_EMAIL_REQUIRED: 'Ingresa tu dirección de correo electrónico o número de celular',
            SIGN_UP_PASSWORD: 'Contraseña',
            SIGN_UP_PASSWORD_INFO: '(Por favor utiliza 6 caracteres o mas, y cuando menos 1 número, y 1 letra mayúscula) ',
            SIGN_UP_PASSWORD_REQUIRED: 'Ingresa tu contraseña',
            SIGN_UP_PASSWORD_NOT_COMPLEX: 'Contraseña debe tener al menos 6 caracteres, 1 letra mayúscula y 1 número',
            SIGN_UP_CONFIRM_PASSWORD: 'Confirma contraseña',
            SIGN_UP_CONFIRM_PASSWORD_REQUIRED: 'Confirma tu contraseña',
            SIGN_UP_CONFIRM_PASSWORD_NO_MATCH: 'Contraseñas no coinciden',
            SIGN_UP_BILLING_INFO: 'Información De Facturación',
            SIGN_UP_ACCOUNT_INFO: 'Información De Cuenta',
            SIGN_UP_CARD_NAME: 'Nombre en Tarjeta de Crédito',
            SIGN_UP_CARD_NAME_REQUIRED: 'Ingresa nombre como aparece en tu tarjeta de crédito',
            SIGN_UP_ADDRESS: 'Domicilio de Facturación',
            SIGN_UP_ADDRESS_REQUIRED: 'Ingresa dirección como aparece en tu tarjeta de crédito',
            SIGN_UP_CITY: 'Ciudad',
            SIGN_UP_CITY_REQUIRED: 'Ingresa ciudad como aparece en tu tarjeta de crédito',
            SIGN_UP_STATE: 'Estado',
            SIGN_UP_STATE_REQUIRED: 'Ingrese estado como aparece en tu tarjeta de crédito',
            SIGN_UP_STATE_LOAD_ERROR: 'Error al subir lista de estados',
            SIGN_UP_STATE_SELECT: 'Elije uno',
            SIGN_UP_CARD_NUMBER: 'Número de Tarjeta de Crédito',
            SIGN_UP_CARD_NUMBER_REQUIRED: 'Ingresa tu número de tarjeta de crédito',
            SIGN_UP_CARD_NUMBER_ERROR: 'Ingresa un número válido de tarjeta de crédito',
            SIGN_UP_CVV: 'CVV (Clave de Seguridad de 3 números)',
            SIGN_UP_CVV_REQUIRED: 'Ingresa tu clave CVV',
            SIGN_UP_CARD_NUMBER_CVV_ERROR: 'Ingresa clave CVV válido',
            SIGN_UP_EXPIRY_DATE: 'Fecha de Expiración (Mes/Año)',
            SIGN_UP_EXPIRY_DATE_REQUIRED: 'Ingresa fecha de expiración de tu tarjeta de crédito',
            SIGN_UP_EXPIRY_DATE_INVALID: 'Ingresa fecha de expiración válida',
            SIGN_UP_ZIP_CODE: 'Código Postal',
            SIGN_UP_ZIP_CODE_REQUIRED: 'Ingresa tu código postal',
            SIGN_UP_ZIP_CODE_INVALID: 'Ingresa código postal válido',
            SIGN_UP_TERMS_OF_USE: 'Términos de Uso',
            SIGN_UP_AND: 'y',
            SIGN_UP_SUBMIT_BUTTON: 'Inicia Mi Membresía Premier',
            SIGN_UP_EMAIL_SMS_SUBSCRIPTION: 'Favor enviarme notificaciones al número de celular<sup>*</sup> o correo electrónico ingresado anteriormente.',
            SIGN_UP_DISCLAIMER: 'Convengo a los',
            SIGN_UP_DISCLAIMER_END: 'de YipTV',
            SIGN_UP_DISCLAIMER_REQUIRED: 'Para utilizar los servicios YipTV necesitas aceptar nuestras condiciones de uso y pólitica de privacidad',
            SIGN_UP_PRIVACY_POLICY: 'Política de Privacidad',
            SIGN_UP_FORM_INVALID: 'Hubo un problema con la información que has ingresado en una o más secciones del formulario. Por favor revisa tus entradas y haz clic de nuevo en "Inicia Mi Membresía Premier" .',
            SIGN_UP_USER_EXISTS: 'Ésta dirección de correo electrónico o número de teléfono móvil ya está registrada con YipTV. Por favor usa otra dirección de correo electrónico o número de teléfono móvil',
            SIGN_UP_FAILED: 'Error al ingresar usuario. Por favor contacta servicio al cliente',
            SIGN_UP_PROBLEM: '¿Tienes problemas al inscribirte? Contacta sevicio al cliente:',
            SIGN_UP_TELEPHONE_MOBILE: '&#10003; Número de Celular Verificados',
            SIGN_UP_TELEPHONE_CHECKING_IF_MOBILE: 'Verificando número de celular. Por favor espera...',
            SIGN_UP_SUCCESS_HEADING: '!BIENVENIDO A TU MEMBRESÍA PREMIER!',
            SIGN_UP_SUCCESS_SUB_HEADING: '¡Empecemos!',
            SIGN_UP_SUCCESS_LINE1_PART1: '¡Felicidades, ya eres <span class="bolder-text">Miembro Premier de YipTV!</span>',
            SIGN_UP_SUCCESS_LINE3_PART1: 'Puedes ver TV directamente en tu computadora o en tu navegador iOS, televisión inteligente, o cualquier dispositivo conectado al internet. Si tienes preguntas sobre como ver televisión en tu dispositivo, visita nuestra sección de',
            SIGN_UP_SUCCESS_LINE3_PART2: 'o llama a nuestro servicio al cliente:',
            SIGN_UP_SUCCESS_FAQS: 'Preguntas Frecuentes',
            SIGN_UP_SUCCESS_LINE4: 'Baja el App Gratis y ve YipTV en vivo en tu celular',
            SIGN_UP_SUCCESS_LINE5: 'Tu Membresía Premier Incluye:',
            SIGN_UP_SUCCESS_BULLET1: '100+ Canales Internacionales de Televisión en Vivo',
            SIGN_UP_SUCCESS_BULLET2: 'Además tendrás acceso a todos los canales nuevos agregados a la Membresía Premier',
            SIGN_UP_SUCCESS_BULLET3: 'Comparte con tu familia en hasta 5 dispositivos',
            SIGN_UP_SUCCESS_QUESTIONS: '¿Preguntas? Llama servicio al cliente:',
            SIGN_UP_SUCCESS_LOGIN_HEADING: '¡BIENVENIDO A TU MEMBRESÍA PREMIER!',
            SIGN_UP_SUCCESS_LOGIN_SUB_HEADING: '¡Empecemos!',
            SIGN_UP_SUCCESS_LOGIN_LINE1: '¡Felicidades, ya eres <span class="bolder-text">Miembro Premier de YipTV!</span>',
            SIGN_UP_SUCCESS_LOGIN_LINE2_PART1: 'Puedes ver TV directamente en tu computadora o en tu navegador iOS, televisión inteligente, o cualquier dispositivo conectado al Internet. Si tienes preguntas sobre como ver televisión en tu dispositivo, visita nuestra sección de',
            SIGN_UP_SUCCESS_LOGIN_LINE2_PART2: 'o llama servicio al cliente:',
            SIGN_UP_SUCCESS_LOGIN_FAQS: 'Preguntas Frecuentes',
            SIGN_UP_SUCCESS_LOGIN_LINE3: 'Baja el App Gratis y ve YipTV en vivo en tu celular',
            SIGN_UP_SUCCESS_LOGIN_LINE4: 'Tu Membresía Premier Incluye:',
            SIGN_UP_SUCCESS_LOGIN_BULLET1: '100+ Canales Internacionales de Televisión en Vivo',
            SIGN_UP_SUCCESS_LOGIN_BULLET2: 'Además tendrás acceso a todos los canales nuevos agregados a la Membresía Premier',
            SIGN_UP_SUCCESS_LOGIN_BULLET3: 'Comparte con tu familia en hasta 5 dispositivos',
            SIGN_UP_SUCCESS_LOGIN_QUESTIONS: '¿Preguntas? Llama servicio al cliente:',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_HEADING: 'Problema al procesar el pago',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LINE1_PART1: 'Tuvimos un problema al procesar la información de tu tarjeta de crédito. La buena noticia es que ahora eres un <span class="bolder-text">Miembro GRÁTIS</span> y puedes empezar a ver la televisión en directo GRÁTIS',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LINE2: 'Para completar tu <span class="bolder-text">Membresía Premier</span> y obtener acceso a más de 100+ canales, por favor, sigue estos pasos:',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_BULLET2: 'Ingresa a tu cuenta',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_BULLET3: 'Haz clic en el botón <span class="bolder-text">Cambia a Membresía Premier</span>',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LINE3_PART1: 'O si prefieres, llame Servicio al Cliente:',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LINE3_PART2: 'Estamos para ayudarte.',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LOGIN_HEADING: 'Problema al procesar el pago',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LOGIN_LINE1: 'Disculpe, ha ocurrido un problema al procesar la información de tu tarjeta de crédito. Para completar tu <span class="bolder-text">Membresía Premier</span> y obtener acceso a más de 100+ canales, por favor, sigue estos pasos:',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LOGIN_BULLET1: 'Asegúrate de haber <a class="bolder-text" href="/sign-in">Ingresado</a> a tu cuenta',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LOGIN_BULLET2: 'Haz clic en el botón <span class="bolder-text">Cambia a Membresía Premier</span> y vuelve a ingresar tu información de tarjeta de crédito',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LOGIN_LINE2_PART1: 'O si prefieres, llame servicio al cliente:',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LOGIN_LINE2_PART2: 'Estamos para ayudarte.',
            SIGN_UP_VERIFICATION_HEADING: 'Verifica Cuenta',
            SIGN_UP_VERIFICATION_MESSAGE: 'Por favor ingresa tu PIN antes de cerrar ventana',
            SIGN_UP_VERIFICATION_PIN: 'Ingresa el PIN (recibido por mensaje de texto o correo electrónico)',
            SIGN_UP_VERIFICATION_PIN_REQUIRED: 'Ingresa tu PIN',
            SIGN_UP_VERIFICATION_PIN_INVALID: 'Ingresa un PIN válido',
            SIGN_UP_VERIFICATION_BUTTON: 'Envía PIN',
            SIGN_UP_VERIFICATION_RESEND: 'Envía PIN de verificación de nuevo',
            SIGN_UP_VERIFICATION_PIN_MISMATCH: 'PIN ingresado es incorrecto. Por favor, ingresa el PIN recibido por mensaje de texto o correo electrónico',
            SIGN_UP_VERIFICATION_ERROR: 'No se puede verificar la cuenta. Por favor contacta servicio al cliente:',
            SIGN_UP_VERIFICATION_RESEND_SUCCESS: 'El PIN ha sido enviado a tu celular o correo electrónico.',
            SIGN_UP_VERIFICATION_USER_ALREADY_ACTIVE: 'Esta cuenta ya está verificada.',
            SIGN_UP_VERIFICATION_RESEND_ERROR: 'Error al enviar el texto de verificación de mensaje o correo electrónico. Por favor contacta servicio al cliente:',
            UPGRADE_SUBSCRIPTION_MESSAGE: 'Está actualizando a una suscripción premier. Se cargarán $14.99 cada mes en tu tarjeta de crédito. Puedes cancelar tu suscripción en cualquier momento yendo a Cuenta > Cancelar Suscripción.',
            UPGRADE_SUBSCRIPTION_BILLING_INFO: 'Ingresa los datos de tu tarjeta de crédito. Si necesitas ayuda, llama',
            UPGRADE_SUBSCRIPTION_CARD_NAME: 'Nombre en tarjeta de crédito',
            UPGRADE_SUBSCRIPTION_CARD_NAME_REQUIRED: 'Ingresa nombre como aparece en tu tarjeta de crédito',
            UPGRADE_SUBSCRIPTION_ADDRESS: 'Domicilio De Facturación',
            UPGRADE_SUBSCRIPTION_ADDRESS_REQUIRED: 'Ingresa dirección como aparece en tu tarjeta de crédito',
            UPGRADE_SUBSCRIPTION_CITY: 'Ciudad',
            UPGRADE_SUBSCRIPTION_CITY_REQUIRED: 'Ingresa ciudad como aparece en tu tarjeta de crédito',
            UPGRADE_SUBSCRIPTION_STATE: 'Estado',
            UPGRADE_SUBSCRIPTION_STATE_REQUIRED: 'Ingresa estado como aparece en tu tarjeta de crédito',
            UPGRADE_SUBSCRIPTION_STATE_LOAD_ERROR: 'Error al subir lista de estados',
            UPGRADE_SUBSCRIPTION_STATE_SELECT: 'Elije uno',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER: 'Número de tarjeta de crédito',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER_REQUIRED: 'Ingresa tu número de tarjeta de crédito',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER_ERROR: 'Ingresa un número de tarjeta de crédito válido',
            UPGRADE_SUBSCRIPTION_CVV: 'CVV (Clave de seguridad de 3 números) ',
            UPGRADE_SUBSCRIPTION_CVV_REQUIRED: 'Ingresa clave CVV',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER_CVV_ERROR: 'Ingresa clave CVV válida',
            UPGRADE_SUBSCRIPTION_EXPIRY_DATE: 'Fecha de expiración (Mes/Año)',
            UPGRADE_SUBSCRIPTION_EXPIRY_DATE_REQUIRED: 'Ingresa fecha de expiración de tu tarjeta de crédito',
            UPGRADE_SUBSCRIPTION_EXPIRY_DATE_INVALID: 'Ingresa fecha de expiración válida',
            UPGRADE_SUBSCRIPTION_ZIP_CODE: 'Código postal',
            UPGRADE_SUBSCRIPTION_ZIP_CODE_REQUIRED: 'Ingresa tu código postal',
            UPGRADE_SUBSCRIPTION_ZIP_CODE_INVALID: 'Ingresa código postal válido',
            UPGRADE_SUBSCRIPTION_CARD_NAME_INVALID: 'Ingresa nombre válido',
            UPGRADE_SUBSCRIPTION_ADDRESS_INVALID: 'Ingresa dirección válida',
            UPGRADE_SUBSCRIPTION_CITY_INVALID: 'Ingresa ciudad válida',
            UPGRADE_SUBSCRIPTION_SUBMIT_BUTTON: 'Envía',
            UPGRADE_SUBSCRIPTION_FAILED: 'Suscripción para cambiar a Membresía Premier falló. Por favor contacta servicio al cliente',
            UPGRADE_SUBSCRIPTION_PAYMENT_FAILED: 'No se puedo cobrar en tu tarjeta. Por favor revisa los detalles de tu tarjeta y haz clic en “Envía” de nuevo.',
            UPGRADE_SUBSCRIPTION_PROBLEM: 'Problemas para cambiar a Premier? Contacta servicio al cliente:',
            UPGRADE_SUBSCRIPTION_ACCOUNT_REFRESH_ERROR: 'Por favor cierra y vuelva a abrir la ventana del navegador de la aplicación YipTV.',
            UPGRADE_SUBSCRIPTION_ALREADY_UPGRADED: 'No se puede actualizar la suscripción como ya está tiene una suscripción premier.',
            UPGRADE_SUBSCRIPTION_COMP_ACTIVE_USER: 'No puedes cambiar de suscripción porque ya tienes Membresía GRÁTIS.',
            USER_HOME_OTHER_LANGUAGE: 'English',
            USER_HOME_SIGN_OUT: 'Desconectar',
            USER_HOME_PROFILE: 'Perfil',
            USER_HOME_ACCOUNT: 'Cuenta',
            USER_HOME_PREFERENCES: 'Preferencias',
            USER_HOME_CHANGE_PASSWORD: 'Cambio de Contraseña',
            USER_HOME_USER_INFO: 'Información de Usuario',
            USER_HOME_UPGRADE_SUBSCRIPTION: 'Cambia a Premier',
            USER_HOME_CANCEL_SUBSCRIPTION: 'Cancela Suscripción',
            USER_HOME_CHANGE_CREDIT_CARD: 'Cambia Tarjeta de Crédito',
            USER_HOME_UPGRADE_SUBSCRIPTION_SUCCESS: '¡Felicidades! Usted ha sido actualizado a la suscripción premier.',
            USER_HOME_CANCEL_SUBSCRIPTION_CONFIRMATION: '¿Seguro que deseas cancelar tu suscripción?',
            USER_HOME_CANCEL_SUBSCRIPTION_SUCCESS: 'Tu suscripción ha sido cancelada.',
            USER_HOME_SUBSCRIPTION_FAILURE: 'Cancelación de suscripción falló. Por favor contacta servicio al cliente:',
            USER_HOME_SUBSCRIPTION_ACCOUNT_REFRESH_ERROR: 'Por favor cierra y vuelva a abrir la ventana del navegador de la aplicación YipTV',
            USER_HOME_CANCEL_ON: 'Tu suscripción de YipTV ha sido cancelada. Tu servicio continuará hasta el final de tu ciclo de facturación actual ',
            USER_HOME_NO_RECENT_CHANNELS: 'No Hay Canales Recientes',
            USER_HOME_MENU_USER_INFO: 'Menú De Usario',
            USER_HOME_EPG_REFRESH: 'Actualizar la Guia',
            USER_INFO_FIRST_NAME: 'Primer Nombre',
            USER_INFO_FIRST_NAME_REQUIRED: 'Ingresa tu nombre',
            USER_INFO_LAST_NAME_REQUIRED: 'Ingresa tu apellido',
            USER_INFO_FIRST_NAME_INVALID: 'Ingresa un nombre válido',
            USER_INFO_LAST_NAME_INVALID: 'Ingresa un apellido válido',
            USER_INFO_TELEPHONE: 'Número de Celular',
            USER_INFO_TELEPHONE_INVALID: 'Ingresa un número de celular válido de EE.UU',
            USER_INFO_TELEPHONE_REQUIRED: 'Ingresa tu número de celular',
            USER_INFO_LAST_NAME: 'Apellido',
            USER_INFO_SUBMIT_BUTTON: 'Envía',
            USER_INFO_UPDATE_SUCCESS: ' Información de usuario actualizada',
            USER_INFO_UPDATE_FAILURE: 'Error al subir información de usuario',
            USER_INFO_ACCOUNT_REFRESH_ERROR: 'Por favor cierra y vuelva a abrir la ventana del navegador de la aplicación YipTV',
            USER_INFO_TELEPHONE_MOBILE: '&#10003; Número de Celular Verificado',
            USER_INFO_TELEPHONE_CHECKING_IF_MOBILE: 'Verificando número de celular. Por favor espera...',
            VERIFY_USER_HEADING_SUCCESS: 'Cuenta verificada',
            VERIFY_USER_HEADING_ERROR: 'Error',
            VERIFY_USER_MESSAGE_SUCCESS: 'Tu cuenta se ha verificado. Haz clic en el botón "Ingresa" para ingresar a YipTV.',
            VERIFY_USER_MESSAGE_ERROR: 'No se puede verificar tu cuenta o tu cuenta ya ha sido verificada. Contacta servicio al cliente:',
            WP_URL_FAQS: 'index.php/es/preguntas-frecuentes/',
            WP_URL_PRIVACY_POLICY: 'index.php/es/privacy-policy-es/',
            WP_URL_TOUS: 'index.php/es/terms-of-service-es/',
            WP_URL_END_USER: 'index.php/es/acuerdo-de-licencia/',
            WP_URL_CHANNELS: 'index.php/es/redes-y-canales/',
            WP_URL_HOW_TO_WATCH: 'index.php/es/nosotros/',
            WP_URL_HOME: 'index.php/es/'
        });
    }]);
}(angular.module('app')));
