(function (app) {
    'use strict';

    app.config(['$translateProvider', function ($translateProvider) {
        $translateProvider.translations('es', {
            CHANGE_CREDIT_CARD_BILLING_INFO: 'Introduzca sus nuevos datos de la tarjeta de crédito. Si necesita ayuda llame al',
            CHANGE_CREDIT_CARD_CARD_NAME: 'Nombre en tarjeta de crédito',
            CHANGE_CREDIT_CARD_CARD_NAME_REQUIRED: 'Ingrese nombre como aparece en su tarjeta de credito',
            CHANGE_CREDIT_CARD_ADDRESS: 'Domicilio De Facturación',
            CHANGE_CREDIT_CARD_ADDRESS_REQUIRED: 'Ingrese direccion como aparece en su tarjeta de credito',
            CHANGE_CREDIT_CARD_CITY: 'Ciudad',
            CHANGE_CREDIT_CARD_CITY_REQUIRED: 'Ingrese ciudad como aparece en su tarjeta de credito',
            CHANGE_CREDIT_CARD_STATE: 'Estado',
            CHANGE_CREDIT_CARD_STATE_REQUIRED: 'Ingrese estado como aparece en su tarjeta de credito',
            CHANGE_CREDIT_CARD_STATE_LOAD_ERROR: 'Error al cargar lista de estados',
            CHANGE_CREDIT_CARD_STATE_SELECT: 'Seleccione uno',
            CHANGE_CREDIT_CARD_CARD_NUMBER: 'Número de tarjeta de crédito',
            CHANGE_CREDIT_CARD_CARD_NUMBER_REQUIRED: 'Introduzca su numero de tarjeta de credito',
            CHANGE_CREDIT_CARD_CARD_NUMBER_ERROR: 'Introduzca un numero de tarjeta de credito valido',
            CHANGE_CREDIT_CARD_CVV: 'CVV (Clave de Seguridad de 3 números)',
            CHANGE_CREDIT_CARD_CVV_REQUIRED: 'Introduzca codigo CVV',
            CHANGE_CREDIT_CARD_CARD_NUMBER_CVV_ERROR: 'Introduzca codigo CVV valido',
            CHANGE_CREDIT_CARD_EXPIRY_DATE: 'Fecha de expiración',
            CHANGE_CREDIT_CARD_EXPIRY_DATE_REQUIRED: 'Introduzca fecha de expiracion de su tarjeta de credito',
            CHANGE_CREDIT_CARD_EXPIRY_DATE_INVALID: 'Introduzca fecha de expiracion valida',
            CHANGE_CREDIT_CARD_ZIP_CODE: 'Código postal',
            CHANGE_CREDIT_CARD_ZIP_CODE_REQUIRED: 'Introduzca su codigo postal',
            CHANGE_CREDIT_CARD_ZIP_CODE_INVALID: 'Introduzca codigo postal valido',
            CHANGE_CREDIT_CARD_CARD_NAME_INVALID: 'Introduzca nombre valido',
            CHANGE_CREDIT_CARD_ADDRESS_INVALID: 'Introduzca direccion valida',
            CHANGE_CREDIT_CARD_CITY_INVALID: 'Introduzca ciudad valida',
            CHANGE_CREDIT_CARD_SUBMIT_BUTTON: 'Presentar',
            CHANGE_CREDIT_CARD_SUCCESS: 'Su tarjeta de credito ha sido cambiada con exito',
            CHANGE_CREDIT_CARD_FAILED: 'Error al cambiar su tarjeta de credito. Por favor pongase en contacto con atencion al cliente',
            CHANGE_CREDIT_CARD_PROBLEM: 'Problemas al cambiar su tarjeta de credito? Pongase en contacto con atencion al cliente',
            CHANGE_CREDIT_CARD_ACCESS_ERROR: 'Usted no puede cambiar su tarjeta de credito. Por favor pongase en contacto con servicio al cliente',
            CHANGE_CREDIT_CARD_PAYMENT_ERROR: 'No pudimos procesar el pago con su tarjeta. Verifique su información de tarjeta de crédito.',
            CHANGE_CREDIT_CARD_FREE_USER_ERROR: 'Los usuarios con versiones de prueba no pueden agregar una tarjeta de crédito a su cuenta',
            CHANGE_CREDIT_CARD_COMP_USER_ERROR: 'Los usuarios con versiones de cortesía no pueden agregar una tarjeta de crédito a su cuenta',
            CHANGE_CREDIT_CARD_ACCOUNT_REFRESH_ERROR: 'Por favor cierre y vuelva a abrir la ventana del navegador de la aplicacion YipTV.',
            CHANGE_PASSWORD_CURRENT_PASSWORD: 'Contrasena actual',
            CHANGE_PASSWORD_NEW_PASSWORD: 'Contrasena nueva',
            CHANGE_PASSWORD_CONFIRM_PASSWORD: 'Confirme contrasena nueva',
            CHANGE_PASSWORD_BUTTON: 'Presentar',
            CHANGE_PASSWORD_CURRENT_PASSWORD_REQUIRED: 'Introduzca su contrasena actual',
            CHANGE_PASSWORD_NEW_PASSWORD_REQUIRED: 'Introduzca contrasena nueva',
            CHANGE_PASSWORD_NEW_PASSWORD_NOT_COMPLEX: 'Contrasena debe tener al menos 6 caracteres, 1 letra mayuscula y 1 numero',
            CHANGE_PASSWORD_NEW_PASSWORD_SAME: 'Contrasena nueva no puede ser la misma contrasena actual',
            CHANGE_PASSWORD_CONFIRM_PASSWORD_REQUIRED: 'Confirme su contrasena',
            CHANGE_PASSWORD_CONFIRM_PASSWORD_NO_MATCH: 'Contrasenas no coinciden',
            CHANGE_PASSWORD_ERROR: 'Se produjo un error al cambiar la contrasena',
            CHANGE_PASSWORD_INCORRECT_PASSWORD: 'Contrasena introducida es incorrecta',
            CHANGE_PASSWORD_SUCCESS: 'Su contrasena ha sido cambiada con exito',
            CHANNEL_GUIDE_ON_NOW: 'Transmitiendo Ahora: ',
            CHANNEL_GUIDE_LOAD_ERROR: 'Error al subir guía de canales',
            COMP_SIGN_UP_HEADING: 'Registrarse',
            COMP_SIGN_UP_MESSAGE: 'Regístrate para obtener una cuenta gratuito a YipTV.',
            COMP_SIGN_UP_VERIFYING: 'Verificación...',
            COMP_SIGN_UP_CODE_EXPIRED: 'Su código de invitación no es válido o ha expirado!',
            COMP_SIGN_UP_FIRST_NAME: 'Nombre',
            COMP_SIGN_UP_FIRST_NAME_REQUIRED: 'Ingrese su nombre',
            COMP_SIGN_UP_LAST_NAME_REQUIRED: 'Ingrese su apellido',
            COMP_SIGN_UP_FIRST_NAME_INVALID: 'Introduzca nombre valido',
            COMP_SIGN_UP_LAST_NAME_INVALID: 'Introduzca apellido valido',
            COMP_SIGN_UP_EMAIL: 'Dirección de correo electrónico',
            COMP_SIGN_UP_TELEPHONE: 'Número de Celular',
            COMP_SIGN_UP_TELEPHONE_INVALID: 'Introduzca un número de celular valido de EE.UU',
            COMP_SIGN_UP_TELEPHONE_REQUIRED: 'Introduzca su número de celular',
            COMP_SIGN_UP_LAST_NAME: 'Apellido',
            COMP_SIGN_UP_EMAIL_INVALID: 'Introduzca una dirreccion de correo electronico valida',
            COMP_SIGN_UP_EMAIL_EXISTS: 'Usted ya tiene cuenta con nosotros. Por favor ingresar.',
            COMP_SIGN_UP_EMAIL_REQUIRED: 'Introduzca su direccion de correo electronico',
            COMP_SIGN_UP_PASSWORD: 'Contraseña',
            COMP_SIGN_UP_PASSWORD_INFO: '(Por favor utiliza 6 caracteres o mas, y cuando menos un número, y letra mayúscula)',
            COMP_SIGN_UP_PASSWORD_REQUIRED: 'Introduzca su contrasena',
            COMP_SIGN_UP_PASSWORD_NOT_COMPLEX: 'Contrasena debe tener al menos 6 caracteres, 1 letra mayuscula y 1 numero',
            COMP_SIGN_UP_CONFIRM_PASSWORD: 'Confirmar contraseña',
            COMP_SIGN_UP_CONFIRM_PASSWORD_REQUIRED: 'Confirme su contrasena',
            COMP_SIGN_UP_CONFIRM_PASSWORD_NO_MATCH: 'Contrasenas no coinciden',
            COMP_SIGN_UP_TERMS_OF_USE: 'Términos de uso',
            COMP_SIGN_UP_AND: 'y la',
            COMP_SIGN_UP_SUBMIT_BUTTON: 'Registrarse',
            COMP_SIGN_UP_FORM_INVALID: 'Había un problema con la información que has introducido en una o más secciones del el formulario de arriba. Por favor revise tu entradas y haz clic en "Registrarse" de nuevo.',
            COMP_SIGN_UP_HAVE_ACCOUNT: 'Ya tienes una cuenta?',
            COMP_SIGN_UP_SIGN_IN: 'Ingresar',
            COMP_SIGN_UP_EMAIL_SMS_SUBSCRIPTION: 'Por favor, envíenme actualizaciones a través de mensaje de texto y correo electrónico',
            COMP_SIGN_UP_DISCLAIMER: 'Acepto los',
            COMP_SIGN_UP_DISCLAIMER_END: 'de YipTV.',
            COMP_SIGN_UP_DISCLAIMER_REQUIRED: 'Para utilizar los servicios YipTV usted necesita aceptar nuestras condiciones de uso y politica de privacidad',
            COMP_SIGN_UP_PRIVACY_POLICY: 'Política de privacidad',
            COMP_SIGN_UP_USER_EXISTS: 'Esta direccion de correo electronico ya esta registrada con YipTV. Por favor, use otra direccion de correo electronico',
            COMP_SIGN_UP_FAILED: 'Error al contratar Usuario. Por favor pongase en contacto con servico al cliente',
            COMP_SIGN_UP_PROBLEM: '¿Tiene problemas para registrarse? Comuníquese con el servicio al cliente al',
            COMP_SIGN_UP_TELEPHONE_MOBILE: '&#10003; Número de Celular Verificados',
            COMP_SIGN_UP_TELEPHONE_CHECKING_IF_MOBILE: 'Verificando de número de celular. Por favor espera...',
            CONTACT_US_HEADING: 'Contáctenos',
            CONTACT_US_NAME: 'Nombre',
            CONTACT_US_INTEREST: 'Interés',
            CONTACT_US_INTEREST_SELECT: 'Seleccione uno',
            CONTACT_US_INTEREST_INVESTOR: 'Ser un inversionista de YipTV',
            CONTACT_US_INTEREST_TECHNICAL: 'Soporte técnico',
            CONTACT_US_INTEREST_BILLING: 'Soporte de facturación',
            CONTACT_US_EMAIL: 'Dirección de correo electrónico',
            CONTACT_US_TELEPHONE: 'Teléfono',
            CONTACT_US_TELEPHONE_INVALID: 'Introduzca un numero de telefono valido de EE.UU',
            CONTACT_US_DETAILS: '¿Cómo podemos ayudarlo?',
            CONTACT_US_COUNTRY: 'País',
            CONTACT_US_COUNTRY_SELECT: 'Seleccione uno',
            CONTACT_US_COUNTRY_REQUIRED: 'Seleccione su Pais',
            CONTACT_US_SUBMIT_BUTTON: 'Enviar',
            CONTACT_US_NAME_REQUIRED: 'Introduzca su nombre',
            CONTACT_US_INTEREST_REQUIRED: 'Introduzca su tipo de interes',
            CONTACT_US_EMAIL_REQUIRED: 'Introduzca su Email',
            CONTACT_US_EMAIL_INVALID: 'Introduzca Email valido',
            CONTACT_US_DETAILS_REQUIRED: 'Como podemos ayudarle?',
            CONTACT_US_TELEPHONE_REQUIRED: 'Introduzca su numero de telefono',
            CONTACT_US_ERROR: 'Error al enviar su solicitud',
            CONTACT_US_COUNTRY_LOAD_ERROR: 'Error al cargar la lista de paises',
            CONTACT_US_SUCCESS_HEADING: 'Contáctenos',
            CONTACT_US_SUCCESS_MESSAGE: 'Su solicitud ha sido enviado con exito',
            FORGOT_PASSWORD_HEADING: 'Olvidado Contrasena',
            FORGOT_PASSWORD_EMAIL: 'Introduzca su direccion de correo electronico y le enviaremos un enlace para restablecer su contrasena',
            FORGOT_PASSWORD_BUTTON: 'Presentar',
            FORGOT_PASSWORD_EMAIL_INVALID: 'Introduzca email valido',
            FORGOT_PASSWORD_EMAIL_REQUIRED: 'Introduzca su email',
            FORGOT_PASSWORD_ERROR: 'Error al enviar el enlace de restablecimiento de contrasena. Por favor pongase en contacto con servico al cliente',
            FORGOT_PASSWORD_SUCCESS_HEADING: 'Olvidado Contrasena',
            FORGOT_PASSWORD_SUCCESS_MESSAGE: 'Enlace de restablecimiento de contrasena y instrucciones han sido enviado a su direccion de email',
            FREE_SIGN_UP_HEADING: 'Mi MEMBRESÍA GRATIS YipTV',
            FREE_SIGN_UP_MESSAGE: 'Sin periodo de prueba, sin trampas, solamente televisión gratis.',
            FREE_SIGN_UP_BULLET1: '16 Canales GRATIS de TV Internacional en vivo ',
            FREE_SIGN_UP_BULLET2: 'Además – 9 Canales Premier gratis por 7 días, (incluyendo beIN DEPORTES y Hola TV)',
            FREE_SIGN_UP_BULLET3: 'No Requiere Tarjeta de Crédito, Contrato, o Paquete de Cable ',
            FREE_SIGN_UP_BULLET4: 'Quédate con tu Membresía GRATIS indefinidamente, o cambia a la Membresía Premier y recibe 85+ canales, ¡tu decides!',
            FREE_SIGN_UP_FIRST_NAME: 'Primer Nombre',
            FREE_SIGN_UP_FIRST_NAME_REQUIRED: 'Ingrese su nombre',
            FREE_SIGN_UP_LAST_NAME_REQUIRED: 'Ingrese su apellido',
            FREE_SIGN_UP_FIRST_NAME_INVALID: 'Introduzca nombre valido',
            FREE_SIGN_UP_LAST_NAME_INVALID: 'Introduzca apellido valido',
            FREE_SIGN_UP_EMAIL: 'Correo Electrónico',
            FREE_SIGN_UP_TELEPHONE: 'Número de Celular',
            FREE_SIGN_UP_TELEPHONE_INVALID: 'Introduzca un número de celular valido de EE.UU',
            FREE_SIGN_UP_TELEPHONE_REQUIRED: 'Introduzca su número de celular',
            FREE_SIGN_UP_LAST_NAME: 'Apellido',
            FREE_SIGN_UP_EMAIL_INVALID: 'Introduzca una dirreccion de correo electronico valida',
            FREE_SIGN_UP_EMAIL_EXISTS: 'Usted ya tiene cuenta con nosotros. Por favor ingresar.',
            FREE_SIGN_UP_EMAIL_REQUIRED: 'Introduzca su direccion de correo electronico',
            FREE_SIGN_UP_PASSWORD: 'Contraseña',
            FREE_SIGN_UP_PASSWORD_INFO: '(Por favor utiliza 6 caracteres o mas, y cuando menos un número, y letra mayúscula)',
            FREE_SIGN_UP_PASSWORD_REQUIRED: 'Introduzca su contrasena',
            FREE_SIGN_UP_PASSWORD_NOT_COMPLEX: 'Contrasena debe tener al menos 6 caracteres, 1 letra mayuscula y 1 numero',
            FREE_SIGN_UP_CONFIRM_PASSWORD: 'Confirma Contraseña',
            FREE_SIGN_UP_CONFIRM_PASSWORD_REQUIRED: 'Confirme su contrasena',
            FREE_SIGN_UP_CONFIRM_PASSWORD_NO_MATCH: 'Contrasenas no coinciden',
            FREE_SIGN_UP_TERMS_OF_USE: 'Términos de Uso',
            FREE_SIGN_UP_AND: 'y',
            FREE_SIGN_UP_SUBMIT_BUTTON: 'Comience Mi Membresía Gratis',
            FREE_SIGN_UP_FORM_INVALID: 'Había un problema con la información que has introducido en una o más secciones del el formulario de arriba. Por favor revise tu entradas y haz clic en "Comience Mi Membresía Gratis" de nuevo.',
            FREE_SIGN_UP_HAVE_ACCOUNT: 'Ya tienes una cuenta?',
            FREE_SIGN_UP_SIGN_IN: 'Ingresar',
            FREE_SIGN_UP_EMAIL_SMS_SUBSCRIPTION: 'Por favor, envíenme actualizaciones a través de mensaje de texto y correo electrónico',
            FREE_SIGN_UP_DISCLAIMER: 'Convengo a los',
            FREE_SIGN_UP_DISCLAIMER_END: 'de YipTV.',
            FREE_SIGN_UP_DISCLAIMER_REQUIRED: 'Para utilizar los servicios YipTV usted necesita aceptar nuestras condiciones de uso y politica de privacidad',
            FREE_SIGN_UP_PRIVACY_POLICY: 'Política de Privacidad',
            FREE_SIGN_UP_USER_EXISTS: 'Esta direccion de correo electronico ya esta registrada con YipTV. Por favor, use otra direccion de correo electronico',
            FREE_SIGN_UP_FAILED: 'Error al contratar Usuario. Por favor pongase en contacto con servico al cliente',
            FREE_SIGN_UP_PROBLEM: '¿Tienes problemas en inscribirte? Contacta nuestro servicio de suporte en:',
            FREE_SIGN_UP_TELEPHONE_MOBILE: '&#10003; Número de Celular Verificados',
            FREE_SIGN_UP_TELEPHONE_CHECKING_IF_MOBILE: 'Verificando de número de celular. Por favor espera...',
            FREE_SIGN_UP_SUCCESS_HEADING: '¡Gracias – Bienvenido a YipTV!',
            FREE_SIGN_UP_SUCCESS_SUB_HEADING: '¡Empecemos!',
            FREE_SIGN_UP_SUCCESS_LINE1: '¡Felicidades, ya eres <span class="bolder-text">Miembro GRATIS de YipTV!</span> Solo falta una cosa antes de empezar a ver TV online:',
            FREE_SIGN_UP_SUCCESS_LINE2: '<span class="bolder-text">Por favor confirma tu correo electrónico haciendo clic al enlace dentro del correo electrónico que te enviamos.</span>',
            FREE_SIGN_UP_SUCCESS_LINE3_PART1: 'Puedes ver TV directamente en tu computadora o en tu navegador iOS, televisión inteligente, o cualquier dispositivo conectado al internet. Si tienes preguntas sobre como ver televisión en tu dispositivo, visita nuestra sección de',
            FREE_SIGN_UP_SUCCESS_LINE3_PART2: 'o llama a nuestro servicio al cliente:',
            FREE_SIGN_UP_SUCCESS_FAQS: 'preguntas frecuentes',
            FREE_SIGN_UP_SUCCESS_LINE4: 'Baja el App GRATIS y ve YipTV en vivo en tu celular',
            FREE_SIGN_UP_SUCCESS_LINE5: 'Tu Membresía Gratis Incluye:',
            FREE_SIGN_UP_SUCCESS_BULLET1: '17 Canales Internacionales de Televisión en Vivo Gratis',
            FREE_SIGN_UP_SUCCESS_BULLET2: 'Además – disfruta de 9 canales de la Membresía Premier por 7 días (incluyendo beIN DEPORTES y Hola TV)',
            FREE_SIGN_UP_SUCCESS_BULLET3: 'Ve en 2 dispositivos',
            FREE_SIGN_UP_SUCCESS_BULLET4: 'Quédate con tu <span class="bolder-text">Membresía Gratis</span> indefinidamente, o cambia a la Membresía Premier y recibe 70+ canales, ¡tu decides!',
            FREE_SIGN_UP_SUCCESS_QUESTIONS: '¿Preguntas? Llama servicio al cliente:',
            INDEX_TOP: 'Superior ^',
            INDEX_OTHER_LANGUAGE: 'English',
            INDEX_SIGN_IN: 'Ingresar',
            INDEX_OK_BUTTON: 'Okay',
            INDEX_YES_BUTTON: 'Sí',
            INDEX_NO_BUTTON: 'No',
            INDEX_CONTACT_NUMBER: 'Llámanos gratis: <a href=\'tel:+18559194788\'>855-919-4788</a>',
            INDEX_SOCIAL_MEDIA: '<a target="_blank" href="https://www.facebook.com/yiptvespanol"><img src="images/facebook.png" alt=""/></a><a target="_blank" href="https://twitter.com/YipTV"><img src="images/twitter.png" alt=""/></a>',
            INDEX_COPYRIGHT: 'Derechos de Autor ® 2012-2015 YIPTV. Uso de el servicio de YIPTV y de esta pagina web constituye aceptación de nuestros términos de uso y póliza de privacidad.',
            MAIN_ERROR_APP_CONFIG: 'Error frente configuracion de la aplicacion',
            MAIN_SIGN_OUT_CONFIRMATION: 'Seguro que deseas salir de YipTV?',
            MAIN_LANGUAGE_CHANGE_SAVE_CHECK: 'Desea cambiar su idioma preferido a',
            MAIN_LANGUAGE_CHANGE_SAVE_SUCCESS: 'Preferencia de idioma guardado con exito',
            MAIN_LANGUAGE_CHANGE_SAVE_ERROR: 'Error al cambiar su preferencia de idioma. Por favor pongase en contacto con servicio al cliente',
            NOT_FOUND_HEADING: 'Pagina no disponible',
            NOT_FOUND_MESSAGE: 'La pagina que usted busca no existe',
            PLAYER_ON_NOW: 'Transmitiendo Ahora: ',
            PLAYER_TIME: 'Tiempo: ',
            PLAYER_NOT_AVAILABLE: 'No Disponible',
            PLAYER_DURATION: 'Duración: ',
            PLAYER_DESCRIPTION: 'Descripción: ',
            PLAYER_TITLE: 'Título: ',
            PLAYER_MINUTES: 'minutos',
            PLAYER_RESULTS: 'Resultados:',
            PLAYER_CHANNELS_FOUND: 'canal(es) encontrados!',
            PLAYER_CATEGORIES: 'Categorías',
            PLAYER_CLEAR_ALL: 'Limpiar Todo',
            PLAYER_GENRE: 'Género',
            PLAYER_REGION: 'Región',
            PLAYER_AUDIENCE: 'Audiencia',
            PLAYER_LANGUAGE: 'Idioma',
            PLAYER_CHANNEL_FILTER: 'Filtro de Canal',
            PLAYER_CHANNEL_LOAD_ERROR: 'Error al subir canal',
            PLAYER_CHANNEL_LIST_LOAD_ERROR: 'Error al subir lista de canales',
            PLAYER_CHANNEL_GUIDE_LOAD_ERROR: 'Error al subir guía de canales',
            PLAYER_PROMO_CHANNEL_LIST_LOAD_ERROR: 'Error al subir lista de canales promo',
            PREFERENCES_PREFERRED_LANGUAGE: 'Elige su idioma preferido',
            PREFERENCES_PREFERRED_LANGUAGE_REQUIRED: 'Elige su idioma preferido',
            PREFERENCES_SMS_SUBSCRIPTION: 'Envíeme actualizaciones a través de mensaje de texto',
            PREFERENCES_EMAIL_SUBSCRIPTION: 'Envíeme actualizaciones por correo electrónico',
            PREFERENCES_SUBMIT_BUTTON: 'Presentar',
            PREFERENCES_FETCH_ERROR: 'No se pudo obtener sus preferencias. Por favor pongase en contacto con servicio al cliente',
            PREFERENCES_SAVE_ERROR: 'Error al guardar sus preferencias. Por favor pongase en contacto con servicio al cliente',
            PREFERENCES_SAVED: 'Sus preferencias han sido guardada con exito.',
            RAF_HEADING: 'Recomendar a un amigo',
            RAF_MESSAGE: 'Da a conocer YipTV a todos tus amigos y todos recibirán TV GRATIS. Por cada uno de tus amigos que se inscriban como nuevo cliente, cada uno de ustedes recibirá un mes GRATIS. ¡Invítalos a todos a inscribirse, porque esta oferta es ilimitada!',
            RAF_FINE_PRINT: '<sup>*</sup>Si usted (el Referente) recomienda YipTV a otra persona (el Referido) y ésta completa satisfactoriamente el registro para suscribirse, el Referente recibirá un crédito por un mes de su cargo mensual de servicio y el Referido recibirá un crédito por un mes de su cargo mensual de servicio (hasta $14,99 de crédito, al mes) únicamente si, y después de que, el Referido haya mantenido la suscripción con YipTV por sesenta y un (61) días consecutivos. El crédito no aplica para los cargos adicionales, incluyendo, entre otros, los servicios o características premium. La cancelación por parte del Referente o el Referido antes de los sesenta y un (61) días consecutivos, desde la fecha en que el Referido se suscribe a YipTV, resultará en la pérdida y/o reembolso de los créditos asociados. En caso de que el Referente o el Referido tuvieran un saldo adeudado, entonces se aplicará un crédito. Los créditos obtenidos no tienen valor en efectivo, y equivalen a un mes de servicio, independientemente de posibles cambios, pasados o futuros, en el precio de suscripción del servicio. Si el cliente cancela el servicio y le quedan créditos por recomendaciones, entonces esos créditos, de haberlos, se perderán. El crédito no tiene valor en efectivo, es intransferible y no es reembolsable. Ciertos tipos de recomendaciones, incluyendo entre otros, referir a usted mismo o a alguien que viva en la misma residencia que usted, están prohibidos. La oferta, los precios y los cargos están sujetos a cambios sin previo aviso. Se pueden aplicar otros términos y condiciones. Consulte los términos de uso para más información. Nulo donde esté prohibido. La oferta no puede ser combinada y está sujeta a restricciones y limitaciones.',
            RAF_MY_EMAIL: 'Mi dirección de correo electrónico',
            RAF_EMAIL_REQUIRED: 'Ingrese su Email',
            RAF_EMAIL_INVALID: 'Ingrese un Email valido',
            RAF_IMPORT_CONTACT_LIST: 'Importar mi lista de contactos',
            RAF_LOADING: 'Cargando...',
            RAF_OR: 'o',
            RAF_ENTER_FRIENDS_EMAIL: 'Ingresar las direcciones de correo electrónico de mis amigos separadas por comas',
            RAF_SEND_INVITE: 'Enviar invitación',
            RAF_EMAIL_SEND_ERROR: 'Error al enviar invitacion de YipTV a sus amigos',
            RAF_EMAIL_LIST_REQUIRED: 'Ingrese por lo menos una direccion de correo electronico',
            RAF_EMAIL_LIST_INVALID: 'Uno o mas direcciones de correo electronico no son valida',
            RAF_SUCCESS_HEADING: 'Recomendar a un amigo',
            RAF_SUCCESS_MESSAGE: 'Hemos enviado una invitacion a sus amigos',
            REDIRECT_MESSAGE: 'Redireccionamiento...',
            RESEND_VERIFICATION_HEADING: 'Reenvío de Verificación de Correo Electrónico y Mensaje de Texto',
            RESEND_VERIFICATION_EMAIL: 'Introduzca su direccion de correo electronico',
            RESEND_VERIFICATION_EMAIL_INVALID: 'Introduzca email valido',
            RESEND_VERIFICATION_EMAIL_REQUIRED: 'Introduzca su email',
            RESEND_VERIFICATION_BUTTON: 'Presentar',
            RESEND_VERIFICATION_SUCCESS_HEADING: 'Reenvío de Verificación de Correo Electrónico y Mensaje de Texto',
            RESEND_VERIFICATION_SUCCESS_MESSAGE: 'Correo electrónico y mensaje de texto para verificar su cuenta han sido enviado. Para introducir el PIN recibido por mensaje de texto clic',
            RESEND_VERIFICATION_SUCCESS_HERE: 'aquí',
            RESEND_VERIFICATION_USER_ERROR: 'Cuenta no encontrada o cuenta ya activada',
            RESEND_VERIFICATION_ERROR: 'Error al enviar el enlace de verificacion de la cuenta. Por favor pongase en contacto con servico al cliente',
            RESET_PASSWORD_HEADING: 'Reestablecer Contrasena',
            RESET_PASSWORD_NEW_PASSWORD: 'Nueva Contrasena',
            RESET_PASSWORD_CONFIRM_PASSWORD_REQUIRED: 'Confirme su Contrasena',
            RESET_PASSWORD_CONFIRM_PASSWORD: 'Confirmar Contrasena',
            RESET_PASSWORD_NEW_PASSWORD_NOT_COMPLEX: 'Contrasena debe tener al menos 6 caracteres, 1 letra mayuscula y 1 numero',
            RESET_PASSWORD_NEW_PASSWORD_REQUIRED: 'Introduzca su contrasena',
            RESET_PASSWORD_CONFIRM_PASSWORD_NO_MATCH: 'Contrasenas no coinciden',
            RESET_PASSWORD_BUTTON: 'Presentar',
            RESET_PASSWORD_USER_ERROR: 'No se puede cambiar su contrasena. Por favor pongase en contacto con servico al cliente',
            RESET_PASSWORD_CODE_ERROR: 'El enlace de restablecimiento de contrasena ha expirado y ya no es valida',
            RESET_PASSWORD_SUCCESS_HEADING: 'Reestablecer Contrasena',
            RESET_PASSWORD_SUCCESS_MESSAGE: 'Su contrasena ha sido cambiada con exito',
            SIGN_IN_HEADING: 'Bienvenido de nuevo a YipTV. Inicie sesión a bajo para ver sus programas favoritos.',
            SIGN_IN_SUB_HEADING: '¿Todavía no se ha registrado? ¡Haz clic <a style="color:#A03269" class="underline-text" href="/sign-up/free">aquí para registrarte</a> y empieza a ver ahora!',
            SIGN_IN_EMAIL: 'Dirección de correo electrónico',
            SIGN_IN_EMAIL_REQUIRED: 'Introduzca su direccion de correo electronico',
            SIGN_IN_EMAIL_INVALID: 'Introduzca una dirreccion de correo electronico valida',
            SIGN_IN_PASSWORD: 'Contraseña',
            SIGN_IN_PASSWORD_REQUIRED: 'Introduzca su contrasena',
            SIGN_IN_SUBMIT_BUTTON: 'Iniciar sesion',
            SIGN_IN_FORGOT_PASSWORD: '¿Olvidó su contraseña?',
            SIGN_IN_RESET_PASSWORD: 'Restablecer contraseña',
            SIGN_IN_NOT_REGISTERED: '¿No está registrado?',
            SIGN_IN_SIGN_UP: 'Registrarse',
            SIGN_IN_FAILED_NOT_VERIFIED: 'Ingresa fracas. Su cuenta aun no ha sido verificada.',
            SIGN_IN_FAILED: 'Ingresa fracasada',
            SIGN_IN_NO_VERIFICATION_EMAIL: '¿No has recibido la verificación de correo electrónico / mensaje de texto ?',
            SIGN_IN_RESEND_VERIFICATION: 'Solicitarlo nuevamente',
            SIGN_IN_UPGRADE_SUBSCRIPTION: 'Tienes que iniciar sesion antes de poder actualiza a membresía premium.',
            SIGN_UP_SUB_HEADING: 'MI MEMBRESÍA PREMIER de YIPTV',
            SIGN_UP_QUESTIONS: '¿Preguntas? Llama servicio al cliente:',
            SIGN_UP_ORDER_SUMMARY: 'Datos de Pedido - Membresía Premier',
            SIGN_UP_BULLET1: '85+ <span style="text-decoration: underline">Canales</span> Internacionales en Vivo',
            SIGN_UP_BULLET2: 'Incluye acceso en hasta 5 dispositivos',
            SIGN_UP_BULLET3: 'Sin Contrato – Cancela en Cualquier Momento',
            SIGN_UP_ITEM1: 'Primer Mes Membresía Premier:',
            SIGN_UP_AMOUNT1: '$14.99',
            SIGN_UP_ITEM2: 'Impuestos & Costos Ocultos:',
            SIGN_UP_AMOUNT2: '$0.00',
            SIGN_UP_ITEM_TOTAL: 'Costo Mensual Total:',
            SIGN_UP_AMOUNT_TOTAL: '$14.99',
            SIGN_UP_FIRST_NAME: 'Primer Nombre',
            SIGN_UP_FIRST_NAME_REQUIRED: 'Ingrese su nombre',
            SIGN_UP_LAST_NAME_REQUIRED: 'Ingrese su apellido',
            SIGN_UP_FIRST_NAME_INVALID: 'Introduzca nombre valido',
            SIGN_UP_LAST_NAME_INVALID: 'Introduzca apellido valido',
            SIGN_UP_CARD_NAME_INVALID: 'Introduzca nombre valido',
            SIGN_UP_ADDRESS_INVALID: 'Introduzca direccion valida',
            SIGN_UP_CITY_INVALID: 'Introduzca ciudad valida',
            SIGN_UP_EMAIL: 'Correo electrónico',
            SIGN_UP_TELEPHONE: 'Número de Celular',
            SIGN_UP_TELEPHONE_INVALID: 'Introduzca un número de celular valido de EE.UU',
            SIGN_UP_TELEPHONE_REQUIRED: 'Introduzca su número de celular',
            SIGN_UP_LAST_NAME: 'Apellido',
            SIGN_UP_EMAIL_INVALID: 'Introduzca una dirreccion de correo electronico valida',
            SIGN_UP_EMAIL_EXISTS: 'Usted ya tiene cuenta con nosotros. Por favor ingresar.',
            SIGN_UP_EMAIL_REQUIRED: 'Introduzca su direccion de correo electronico',
            SIGN_UP_PASSWORD: 'Contraseña',
            SIGN_UP_PASSWORD_INFO: '(Por favor utiliza 6 caracteres o mas, y cuando menos un número, y letra mayúscula) ',
            SIGN_UP_PASSWORD_REQUIRED: 'Introduzca su contrasena',
            SIGN_UP_PASSWORD_NOT_COMPLEX: 'Contrasena debe tener al menos 6 caracteres, 1 letra mayuscula y 1 numero',
            SIGN_UP_CONFIRM_PASSWORD: 'Confirmar contraseña',
            SIGN_UP_CONFIRM_PASSWORD_REQUIRED: 'Confirme su contrasena',
            SIGN_UP_CONFIRM_PASSWORD_NO_MATCH: 'Contrasenas no coinciden',
            SIGN_UP_BILLING_INFO: 'Información De Facturación',
            SIGN_UP_ACCOUNT_INFO: 'Información De Cuenta',
            SIGN_UP_CARD_NAME: 'Nombre en Tarjeta de Crédito',
            SIGN_UP_CARD_NAME_REQUIRED: 'Ingrese nombre como aparece en su tarjeta de credito',
            SIGN_UP_ADDRESS: 'Domicilio de Facturación',
            SIGN_UP_ADDRESS_REQUIRED: 'Ingrese direccion como aparece en su tarjeta de credito',
            SIGN_UP_CITY: 'Ciudad',
            SIGN_UP_CITY_REQUIRED: 'Ingrese ciudad como aparece en su tarjeta de credito',
            SIGN_UP_STATE: 'Estado',
            SIGN_UP_STATE_REQUIRED: 'Ingrese estado como aparece en su tarjeta de credito',
            SIGN_UP_STATE_LOAD_ERROR: 'Error al cargar lista de estados',
            SIGN_UP_STATE_SELECT: 'Elije uno',
            SIGN_UP_CARD_NUMBER: 'Número de Tarjeta de Crédito',
            SIGN_UP_CARD_NUMBER_REQUIRED: 'Introduzca su numero de tarjeta de credito',
            SIGN_UP_CARD_NUMBER_ERROR: 'Introduzca un numero de tarjeta de credito valido',
            SIGN_UP_CVV: 'CVV (Clave de Seguridad de 3 números)',
            SIGN_UP_CVV_REQUIRED: 'Introduzca codigo CVV',
            SIGN_UP_CARD_NUMBER_CVV_ERROR: 'Introduzca codigo CVV valido',
            SIGN_UP_EXPIRY_DATE: 'Fecha de Expiración (Mes/Año)',
            SIGN_UP_EXPIRY_DATE_REQUIRED: 'Introduzca fecha de expiracion de su tarjeta de credito',
            SIGN_UP_EXPIRY_DATE_INVALID: 'Introduzca fecha de expiracion valida',
            SIGN_UP_ZIP_CODE: 'Código Postal',
            SIGN_UP_ZIP_CODE_REQUIRED: 'Introduzca su codigo postal',
            SIGN_UP_ZIP_CODE_INVALID: 'Introduzca codigo postal valido',
            SIGN_UP_TERMS_OF_USE: 'Términos de Uso',
            SIGN_UP_AND: 'y',
            SIGN_UP_SUBMIT_BUTTON: 'Inicia Mi Membresía Premier',
            SIGN_UP_EMAIL_SMS_SUBSCRIPTION: 'Por favor, envíenme actualizaciones a través de mensaje de texto y correo electrónico',
            SIGN_UP_DISCLAIMER: 'Convengo a los',
            SIGN_UP_DISCLAIMER_END: 'de YipTV',
            SIGN_UP_DISCLAIMER_REQUIRED: 'Para utilizar los servicios YipTV usted necesita aceptar nuestras condiciones de uso y politica de privacidad',
            SIGN_UP_PRIVACY_POLICY: 'Política de Privacidad',
            SIGN_UP_FORM_INVALID: 'Había un problema con la información que has introducido en una o más secciones del el formulario de arriba. Por favor revise tu entradas y haz clic en "Inicia Mi Membresía Premier" de nuevo.',
            SIGN_UP_USER_EXISTS: 'Esta direccion de correo electronico ya esta registrada con YipTV. Por favor, use otra direccion de correo electronico',
            SIGN_UP_FAILED: 'Error al contratar Usuario. Por favor pongase en contacto con servico al cliente',
            SIGN_UP_PROBLEM: 'Tiene problemas al inscribirse? Llame sevicio al cliente a:',
            SIGN_UP_TELEPHONE_MOBILE: '&#10003; Número de Celular Verificados',
            SIGN_UP_TELEPHONE_CHECKING_IF_MOBILE: 'Verificando de número de celular. Por favor espera...',
            SIGN_UP_SUCCESS_HEADING: '!BIENVENIDO A TU MEMBRESÍA PREMIER!',
            SIGN_UP_SUCCESS_SUB_HEADING: '¡Empecemos!',
            SIGN_UP_SUCCESS_LINE1: '¡Felicidades, ya eres <span class="bolder-text">Miembro Premier de YipTV!</span> Solo falta una cosa antes de empezar a ver TV online:',
            SIGN_UP_SUCCESS_LINE2: '<span class="bolder-text">Por favor confirma tu correo electrónico haciendo clic al enlace dentro del correo electrónico que te enviamos.</span>',
            SIGN_UP_SUCCESS_LINE3_PART1: 'Puedes ver TV directamente en tu computadora o en tu navegador iOS, televisión inteligente, o cualquier dispositivo conectado al internet. Si tienes preguntas sobre como ver televisión en tu dispositivo, visita nuestra sección de',
            SIGN_UP_SUCCESS_LINE3_PART2: 'o llama a nuestro servicio al cliente:',
            SIGN_UP_SUCCESS_FAQS: 'preguntas frecuentes',
            SIGN_UP_SUCCESS_LINE4: 'Baja el App GRATIS y ve YipTV en vivo en tu celular',
            SIGN_UP_SUCCESS_LINE5: 'Tu Membresía Premier Incluye:',
            SIGN_UP_SUCCESS_BULLET1: '70+ Canales Internacionales de Televisión en Vivo',
            SIGN_UP_SUCCESS_BULLET2: 'Además tendrás acceso a mas y mas canales nuevos agregados a la Membresía Premier',
            SIGN_UP_SUCCESS_BULLET3: 'Comparte con tu familia en hasta 5 dispositivos',
            SIGN_UP_SUCCESS_BULLET4: 'Refiere a un amigo a la Membresía Premier, y ambos reciben ¡un mes de YipTV GRATIS!',
            SIGN_UP_SUCCESS_QUESTIONS: '¿Preguntas? Llama servicio al cliente:',
            SIGN_UP_SUCCESS_LOGIN_HEADING: '¡BIENVENIDO A TU MEMBRESÍA PREMIER!',
            SIGN_UP_SUCCESS_LOGIN_SUB_HEADING: '¡Empecemos!',
            SIGN_UP_SUCCESS_LOGIN_LINE1: '¡Felicidades, ya eres <span class="bolder-text">Miembro Premier de YipTV!</span>',
            SIGN_UP_SUCCESS_LOGIN_LINE2_PART1: 'Puedes ver TV directamente en tu computadora o en tu navegador iOS, televisión inteligente, o cualquier dispositivo conectado al internet. Si tienes preguntas sobre como ver televisión en tu dispositivo, visita nuestra sección de',
            SIGN_UP_SUCCESS_LOGIN_LINE2_PART2: 'o llama a nuestro servicio al cliente:',
            SIGN_UP_SUCCESS_LOGIN_FAQS: 'preguntas frecuentes',
            SIGN_UP_SUCCESS_LOGIN_LINE3: 'Baja el App GRATIS y ve YipTV en vivo en tu celular',
            SIGN_UP_SUCCESS_LOGIN_LINE4: 'Tu Membresía Premier Incluye:',
            SIGN_UP_SUCCESS_LOGIN_BULLET1: '70+ Canales Internacionales de Televisión en Vivo',
            SIGN_UP_SUCCESS_LOGIN_BULLET2: 'Además tendrás acceso a mas y mas canales nuevos agregados a la Membresía Premier',
            SIGN_UP_SUCCESS_LOGIN_BULLET3: 'Comparte con tu familia en hasta 5 dispositivos',
            SIGN_UP_SUCCESS_LOGIN_BULLET4: 'Refiere a un amigo a la Membresía Premier, y ambos reciben ¡un mes de YipTV GRATIS!',
            SIGN_UP_SUCCESS_LOGIN_QUESTIONS: '¿Preguntas? Llama servicio al cliente:',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_HEADING: 'Problema al procesar el pago',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LINE1: 'Tuvimos un problema al procesar la información de la tarjeta de crédito. La buena noticia es que ahora tienes una <span class="bolder-text">Membresía Gratis</span> y una vez que le hagas <span class="bolder-text">clic al enlace en el correo electrónico de verificación</span> que te enviamos, puedes empezar a ver TV en vivo GRATIS!',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LINE2: 'Para completar tu <span class="bolder-text">Membresía Premier</span> y obtener acceso a más de 70 canales, por favor, sigue estos pasos:',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_BULLET1: 'Haz clic en el enlace de verificación en el correo electrónico que le enviamos.',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_BULLET2: 'Ingresa a tu cuenta',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_BULLET3: 'Haz clic en el botón <span class="bolder-text">Actualiza a Membresía Premium</span>',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LINE3_PART1: 'Si prefiere, llame a Atención al Cliente al:',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LINE3_PART2: 'y estaremos encantados en ayudarle.',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LOGIN_HEADING: 'Problema al procesar el pago',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LOGIN_LINE1: 'Disculpe, ha ocurrido un problema al procesar la información de la tarjeta de crédito. Para completar tu <span class="bolder-text">Membresía Premier</span> y obter acceso a más de 70 canales, por favor, sigue estos pasos:',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LOGIN_BULLET1: 'Asegúrate de haber <a class="bolder-text" href="/sign-in">Ingresado</a> a tu cuenta',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LOGIN_BULLET2: 'Haz clic en el botón <span class="bolder-text">Actualiza a Membresía Premium</span> y vulve a ingresar tu información de tarjeta de crédito',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LOGIN_LINE2_PART1: 'Si prefiere, llame a Atención al Cliente al:',
            SIGN_UP_SUCCESS_PAYMENT_FAILURE_LOGIN_LINE2_PART2: 'y estaremos encantados en ayudarle.',
            UPGRADE_SUBSCRIPTION_MESSAGE: 'Usted esta actualizando su cuenta a una cuenta de pago. Su tarjeta de credito sera cargada $14.99 cada mes. Usted puede cancelar su suscripcion en cualquier momento yendo a Cuenta > Cancelar Suscripcion.',
            UPGRADE_SUBSCRIPTION_BILLING_INFO: 'Introduzca sus datos de su tarjeta de credito. Si necesita ayuda, llame',
            UPGRADE_SUBSCRIPTION_CARD_NAME: 'Nombre en tarjeta de crédito',
            UPGRADE_SUBSCRIPTION_CARD_NAME_REQUIRED: 'Ingrese nombre como aparece en su tarjeta de credito',
            UPGRADE_SUBSCRIPTION_ADDRESS: 'Domicilio De Facturación',
            UPGRADE_SUBSCRIPTION_ADDRESS_REQUIRED: 'Ingrese direccion como aparece en su tarjeta de credito',
            UPGRADE_SUBSCRIPTION_CITY: 'Ciudad',
            UPGRADE_SUBSCRIPTION_CITY_REQUIRED: 'Ingrese ciudad como aparece en su tarjeta de credito',
            UPGRADE_SUBSCRIPTION_STATE: 'Estado',
            UPGRADE_SUBSCRIPTION_STATE_REQUIRED: 'Ingrese estado como aparece en su tarjeta de credito',
            UPGRADE_SUBSCRIPTION_STATE_LOAD_ERROR: 'Error al cargar lista de estados',
            UPGRADE_SUBSCRIPTION_STATE_SELECT: 'Elije uno',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER: 'Número de tarjeta de crédito',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER_REQUIRED: 'Introduzca su numero de tarjeta de credito',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER_ERROR: 'Introduzca un numero de tarjeta de credito valido',
            UPGRADE_SUBSCRIPTION_CVV: 'CVV (Clave De Seguridad De 3 Números) ',
            UPGRADE_SUBSCRIPTION_CVV_REQUIRED: 'Introduzca codigo CVV',
            UPGRADE_SUBSCRIPTION_CARD_NUMBER_CVV_ERROR: 'Introduzca codigo CVV valido',
            UPGRADE_SUBSCRIPTION_EXPIRY_DATE: 'Fecha de expiración (Mes/Año)',
            UPGRADE_SUBSCRIPTION_EXPIRY_DATE_REQUIRED: 'Introduzca fecha de expiracion de su tarjeta de credito',
            UPGRADE_SUBSCRIPTION_EXPIRY_DATE_INVALID: 'Introduzca fecha de expiracion valida',
            UPGRADE_SUBSCRIPTION_ZIP_CODE: 'Código postal',
            UPGRADE_SUBSCRIPTION_ZIP_CODE_REQUIRED: 'Introduzca su codigo postal',
            UPGRADE_SUBSCRIPTION_ZIP_CODE_INVALID: 'Introduzca codigo postal valido',
            UPGRADE_SUBSCRIPTION_CARD_NAME_INVALID: 'Introduzca nombre valido',
            UPGRADE_SUBSCRIPTION_ADDRESS_INVALID: 'Introduzca direccion valida',
            UPGRADE_SUBSCRIPTION_CITY_INVALID: 'Introduzca ciudad valida',
            UPGRADE_SUBSCRIPTION_SUBMIT_BUTTON: 'Actualizar',
            UPGRADE_SUBSCRIPTION_FAILED: 'Suscripcion de actualizacion fallo. Por favor, pongase en contacto con atencion al cliente',
            UPGRADE_SUBSCRIPTION_PAYMENT_FAILED: 'No se puedo cobrar en su tarjeta. Por favor, revise los detalles de su tarjeta y haga clic en "Actualizar" de nuevo.',
            UPGRADE_SUBSCRIPTION_PROBLEM: 'Problemas actualizando? Pongase en contacto con atencion al cliente',
            UPGRADE_SUBSCRIPTION_ACCOUNT_REFRESH_ERROR: 'Por favor cierre y vuelva a abrir la ventana del navegador de la aplicacion YipTV.',
            UPGRADE_SUBSCRIPTION_ALREADY_UPGRADED: 'No se puede actualizar la suscripcion porque uste lla es un usuario pagado.',
            UPGRADE_SUBSCRIPTION_COMP_ACTIVE_USER: 'No se puede actualizar su suscripción porque usted tiene una suscripción gratuita.',
            USER_HOME_OTHER_LANGUAGE: 'English',
            USER_HOME_SIGN_OUT: 'Desconectar',
            USER_HOME_PROFILE: 'Perfil',
            USER_HOME_ACCOUNT: 'Cuenta',
            USER_HOME_PREFERENCES: 'Preferencias',
            USER_HOME_CHANGE_PASSWORD: 'Cambio de Contrasena',
            USER_HOME_USER_INFO: 'Informacion de Usuario',
            USER_HOME_UPGRADE_SUBSCRIPTION: 'Actualiza a Membresía Premium',
            USER_HOME_CANCEL_SUBSCRIPTION: 'Cancelar Suscripcion',
            USER_HOME_CHANGE_CREDIT_CARD: 'Cambio de Tarjeta de Credito',
            USER_HOME_UPGRADE_SUBSCRIPTION_SUCCESS: 'Felicidades! Usted ha sido actualizado a un usuario pagado.',
            USER_HOME_CANCEL_SUBSCRIPTION_CONFIRMATION: 'Seguro que desea cancelar su suscripcion?',
            USER_HOME_CANCEL_SUBSCRIPTION_SUCCESS: 'Su suscripcion ha sido cancelada con exito',
            USER_HOME_SUBSCRIPTION_FAILURE: 'Cancelacion de suscripcion fallo. Por favor pongase en contacto con atencion al cliente',
            USER_HOME_SUBSCRIPTION_ACCOUNT_REFRESH_ERROR: 'Por favor cierre y vuelva a abrir la ventana del navegador de la aplicacion YipTV',
            USER_HOME_CANCEL_ON: 'Su suscripción de YipTV ha sido cancelada. Su servicio continuará hasta el final de su ciclo de facturación actual ',
            USER_INFO_FIRST_NAME: 'Primer Nombre',
            USER_INFO_FIRST_NAME_REQUIRED: 'Ingrese su nombre',
            USER_INFO_LAST_NAME_REQUIRED: 'Ingrese su apellido',
            USER_INFO_FIRST_NAME_INVALID: 'Introduzca nombre valido',
            USER_INFO_LAST_NAME_INVALID: 'Introduzca apellido valido',
            USER_INFO_TELEPHONE: 'Número de Celular',
            USER_INFO_TELEPHONE_INVALID: 'Introduzca un número de celular valido de EE.UU',
            USER_INFO_TELEPHONE_REQUIRED: 'Introduzca su número de celular',
            USER_INFO_LAST_NAME: 'Apellido',
            USER_INFO_SUBMIT_BUTTON: 'Actualizar',
            USER_INFO_UPDATE_SUCCESS: ' Info de usuario actualizada',
            USER_INFO_UPDATE_FAILURE: 'Error al subir info de usuario',
            USER_INFO_ACCOUNT_REFRESH_ERROR: 'Por favor cierre y vuelva a abrir la ventana del navegador de la aplicacion YipTV',
            USER_INFO_TELEPHONE_MOBILE: '&#10003; Número de Celular Verificados',
            USER_INFO_TELEPHONE_CHECKING_IF_MOBILE: 'Verificando de número de celular. Por favor espera...',
            VERIFY_USER_HEADING_SUCCESS: 'Cuenta verificada',
            VERIFY_USER_HEADING_ERROR: 'Error',
            VERIFY_USER_MESSAGE_SUCCESS: 'Su cuenta se ha verificado satisfactoriamente. Haga clic en el botón Ingresar arriba para ingresar a YipTV.',
            VERIFY_USER_MESSAGE_ERROR: 'No se puede verificar su cuenta o su cuenta ya ha sido verificada. Comuníquese con el servicio al cliente al',
            WP_URL_FAQS: 'index.php/es/preguntas-frecuentes/',
            WP_URL_PRIVACY_POLICY: 'index.php/es/privacy-policy-2/',
            WP_URL_TOUS: 'index.php/es/terms-of-service-2/'
        });
    }]);
}(angular.module('app')));
