module.exports = {
    config: true,
    ctrlConfig: { newCustomer: true,
        logIn: true,
        editInfo: true,
        orderPackage: true,
        renewInfo: true,
        cancelPackage: true,
        listPackages: true },
    serverContents1: { newCustomer:{error: null, custnum: null, session_id: null},
                     logIn:{error: null, session_id: null},
                     editInfo:{error: null},
                     orderPackage:{error: null},
                     renewInfo:{error: null, dates:[{bill_date: null}]},
                     cancelPackage:{error: null},
                     listPackages:{error: null, cust_pkg: null} },
    serverOptions: { host: 'localhost', 
        port: 9090 },
};
