module.exports = {
    config: true,
    ctrlConfig: { newCustomer: true,
        logIn: true,
        editInfo: true,
        orderPackage: true,
        renewInfo: true,
        cancelPackage: true,
        listPackages: true },
    serverContents: { customNum: null, 
        sessionID: null, 
        error: null, 
        dates:[{'bill_date': null}], 
        customPackage: null },
    serverOptions: { host: 'localhost', 
        port: 9090 },
};
